### ISSUE TITLE
Add routine to sum "deduped" when we have both county and state data

### ISSUE THREAD

**Issue by lazd** [covidatlas/coronadatascraper#100]
We want to keep both types of data in the output, but we want to come up with a simple routine that folks can use to sum data without getting duplicates. This would look at the granularity of the data vs the completeness somehow.

**Comment by S-Wallace-OH** [comment]
What if we just move the state totals to another column? So County Cases, State Cases and possibly Country Cases.

If you want state level, just sum(State Cases), for all rows that are counties it'll be 0 and only the State rows will have it populated. If you want just County cases, sum(County Cases)?

**Comment by lazd** [comment]
@S-Wallace-OH hmm, that's a possibility. What do others think?

**Comment by S-Wallace-OH** [comment]
You could also just implement a set of flags to check, so StateFlag=1 or CountryFlag=1 and those rows are the only ones populated.

Either way makes it fairly straightforward for the calculation to work in most visualization tools.

**Comment by S-Wallace-OH** [comment]
Also, just realized I'm commenting under my work account and not my normal SteveWallace account :D

**Comment by lazd** [comment]
Ah, that's why I didn't recognize you :P

**Comment by chschoenenberger** [comment]
**Idea**:
I just had a look at the data and for Canada, the state for the whole country aggregation is "Total". A possibility might be to add "Total" in county & state for pre-aggregated rows. Something like this
![image](https://user-images.githubusercontent.com/22217265/77549189-d334b380-6eaf-11ea-9b48-2794db439935.png)
Then, depending on the wanted aggregation one could just filter out those rows.

**Comment by Jord-Holt** [comment]
A few thoughts:

What about separate data files? (ex. data-state.json, data-county.json, etc.). or if that would be confusing, modifying the current single data file with added root level schema structure making our intent obvious... 

`state_level: [...], 
 county_level: [...] `

This may seem like overkill, but given the underlying difference in how the state/county data is sourced and organized I think it is warranted. The need to filter on the existence of a county value isn't obvious to the general developer/data scientist looking at this data for the first time and these types of questions will likely continue to be raised if we keep the schema we currently have.

**Comment by jzohrab** [comment]
This is a good idea and one that we're considering for the new project (Li).  Thanks for the issue, cheers! jz
