### ISSUE TITLE
Add scraper for Orleans Parish, Louisiana (i.e. New Orleans)

### ISSUE THREAD

**Issue by mikelehen** [covidatlas/coronadatascraper#1000]
## Location name
Orleans Parish, LA, USA

## Source URL
http://nolagis.maps.arcgis.com/apps/opsdashboard/index.html#/7944c56c0b914072bbd9a8f4cceb0ee1
linked from (county website)
https://ready.nola.gov/incident/coronavirus/safe-reopening/ (under "Covid-19 dashboard")

## Notes/comments
Currently you only have cases / deaths, but the dashboard provides additional information including "total tests" which is what I specifically want.

**Comment by mikelehen** [comment]
For reference, it looks like the underlying dataset can be fetched as https://gis.nola.gov/arcgis/rest/services/apps/LDH_Data/MapServer/0/query?f=json&where=Date%3Etimestamp%20%272020-03-18%2003%3A59%3A59%27&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&orderByFields=Date%20asc&outSR=102100&resultOffset=0&resultRecordCount=1000

**Comment by sglyon** [comment]
I would like to contribute here, specifically to get information on hospital and icu capacity and current load.

From [the CDS docs](https://github.com/covidatlas/coronadatascraper/blame/master/docs/data_fields.md#L48), it seems that the variable `icu` tracks the cumulative number of covid patients that have been admitted to the icu. 

The variables available on the dashboard in the original link are:

```
['OBJECTID',
 'Date',
 'NO_Cases',
 'NO_Deaths',
 'NO_State_Tests',
 'NO_Commercial_Tests',
 'NO_Total_Tests',
 'NO_Tests_per_100k',
 'NO_Cases_per_100k',
 'NO_Deaths_per_100k',
 'NO_Positive_Rate',
 'NO_Deaths_per_Positive',
 'LA_Cases',
 'LA_Deaths',
 'LA_State_Tests',
 'LA_Commercial_Tests',
 'LA_Total_Tests',
 'LA_Tests_per_100k',
 'LA_Cases_per_100k',
 'LA_Deaths_per_100k',
 'LA_Positive_Rate',
 'LA_Deaths_per_Positive',
 'LA_Patients_Hospitalized',
 'LA_Patients_Ventilated',
 'LA_COVID_Hospitalizations',
 'LA_COVID_Hospitalizations_Delta',
 'R1_Ventilators_In_Use',
 'R1_ICU_Beds_In_Use',
 'R1_Beds_In_Use',
 'R1_Ventilators_Available',
 'R1_ICU_Beds_Available',
 'R1_Total_Ventilators',
 'R1_Total_ICU_Beds',
 'R1_Total_Beds',
 'R1_Beds_Available',
 'R1_Ventilators_pct_Available',
 'R1_ICU_Beds_pct_Available',
 'R1_Beds_pct_Available',
 'NO_Deaths_American_Indian_Alaskan_Native',
 'NO_Deaths_Asian',
 'NO_Deaths_Black',
 'NO_Deaths_Native_Hawaiian_Other_Pacific_Islander',
 'NO_Deaths_Other',
 'NO_Deaths_Unknown',
 'NO_Deaths_White',
 'NO_Death_Share_American_Indian_Alaskan_Native',
 'NO_Death_Share_Asian',
 'NO_Death_Share_Black',
 'NO_Death_Share_Native_Hawaiian_Other_Pacific_Islander',
 'NO_Death_Share_Other',
 'NO_Death_Share_Unknown',
 'NO_Death_Share_White',
 'NO_Rolling_Cases',
 'NO_Rolling_Deaths',
 'NO_Tests_Delta',
 'NO_Cases_Delta',
 'NO_Deaths_Delta',
 'NO_Cases_x5',
 'NO_Test_Growth_Rate',
 'NO_Case_Growth_Rate',
 'NO_Death_Growth_Rate',
 'NO_Population_pct_Tested',
 'LA_Rolling_Cases',
 'LA_Rolling_Deaths',
 'LA_Tests_Delta',
 'LA_Cases_Delta',
 'LA_Deaths_Delta',
 'LA_Cases_x5',
 'LA_Test_Growth_Rate',
 'LA_Case_Growth_Rate',
 'LA_Death_Growth_Rate',
 'LA_Population_pct_Tested',
 'NO_Population',
 'LA_Population',]
```

From this list I do not believe I can get cumulative icu cases (what the docs indicate), but I *can* get the daily icu capacity and usage variables I am after. 

Are there plans of supporting a "snapshot" of hospital status?

**Comment by lazd** [comment]
Yes, we have plans!

Return `icu_current` for current people in the ICU (is that `LA_Patients_Ventilated`?) in your scraper, and return `hospitalized_current` for current total (includes ventilated/ICU). Then, of course, `hospitalized` for total hospitalized (`LA_COVID_Hospitalizations`?), `discharged` for total discharged (not sure how to get this, is `LA_COVID_Hospitalizations_Delta` related?).

**Comment by sglyon** [comment]
Excellent thanks.

I believe that for New Orleans Parish we would have

- `icu_current` should be `R1_ICU_Beds_In_Use`
- `hospitalized_current` should be `R1_Beds_In_Use`

I'd need to verify that those `R1` numbers are for orleans and not LA.

**Comment by sglyon** [comment]
I'm nearly finished with a scraper for Orleans that grabs this data -- Stay tuned for a Pr within the next 24 hours!

**Comment by jzohrab** [comment]
I've added this to Li sources in https://github.com/covidatlas/li/pull/352.

Cheers and thanks!
