### ISSUE TITLE
France data is off

### ISSUE THREAD

**Issue by asarfati1985** [covidatlas/coronadatascraper#1001]
Data for France is showing very detailed (metro and county level) for deaths, tests, hospitalizations, and discharged, but no data for the confirmed cases. Why is this information missing?

**Comment by jzohrab** [comment]
Hello, thanks for the issue!

Per the code at
https://github.com/covidatlas/coronadatascraper/blob/master/src/shared/scrapers/FR/index.js,
we get urls from '
https://www.data.gouv.fr/fr/organizations/sante-publique-france/datasets-resources.csv
',

And then scrape other urls.  If you can suggest other data sources to
include, please do so.  Cheers and thanks again!
Jz

**Comment by jzohrab** [comment]
Hi @asarfati1985 - if you let us know where to get the data, we can include it; if not, I'll close this issue in a few days.  Thank you! jz

**Comment by jzohrab** [comment]
Closing, no response.  Au revoir, jz
