### ISSUE TITLE
Some administrative districts(Nenets and Chukotka) are missing in the Russia data, 5/16/2020

### ISSUE THREAD

**Issue by ngolosov** [covidatlas/coronadatascraper#1009]
## Some administrative districts are missing in the Russia data, 5/16/2020
Some administrative districts, such as _Nenets Autonomous Okrug (ISO code RU-NEN)_ and _Chukotka Autonomous Okrug(RU-CHU)_ are missing in the results(data,json file) but they're present in the data source(Yandex).
Apparently there is a bug with parsing data for the _Nenets Autonomous Okrug (ISO code RU-NEN)_ and _Chukotka Autonomous Okrug(RU-CHU)_
Counts in the data.json for the Nenets Autonomous Okrug seemingly as I can judge by the total number of cases are represented by the following entry in the data.json:
```
 {
    "country": "Russia",
    "aggregate": "state",
    "url": "https://yandex.ru/maps/api/covid?csrfToken=",
    "curators": [
      {
        "name": "Yandex",
        "url": "https://yandex.ru"
      }
    ],
    "sources": [
      {
        "description": "Data provided by Rospotrebnadzor (Federal Service for Surveillance on Consumer Rights Protection and Human Wellbeing)",
        "name": "Rospotrebnadzor",
        "url": "https://www.rospotrebnadzor.ru/"
      }
    ],
    "maintainers": [
      {
        "name": "Arseniy Ivanov",
        "twitter": "@freeatnet",
        "github": "freeatnet",
        "email": "arseniy+coronadatascraper@freeatnet.com"
      }
    ],
    "cases": 52,
    "recovered": 7,
    "deaths": 0,
    "active": 45,
    "rating": 0.45098039215686275,
    "coordinates": [
      0,
      61.5205
    ],
    "tz": [
      "Asia/Krasnoyarsk"
    ],
    "featureId": "iso1:RU",
    "population": 147500000,
    "populationDensity": 8.739206847225667,
    "countryId": "iso1:RU",
    "name": "Russia",
    "level": "country"
  },
```
featureId is obviously incorrect, as it belongs to Russia, and not to  the _Nenets Autonomous Okrug._

## Issue is evident in features.json visualization
As I can see at https://coronadatascraper.com/#features.json, data for the affected districts are labeled as "Russia" and not as "Name of the district" and the counts are the same for the _Nenets Autonomous Okrug._ and  _Chukotka Autonomous Okrug_

It would be great if @freeatnet could look at the issue.

**Comment by freeatnet** [comment]
@ngolosov Hey, thanks for raising this! It looks like the ISO mapping introduced in #787 has no entries for either Nenets Autonomous Okrug or Chukotka Autonomous Okrug.

@qgolsteyn would adding the following to `mapping.json` suffice?
```
{
    "Ненецкий автономный округ": "iso2:RU-NEN",
    "Чукотский автономный округ": "iso2:RU-CHU"
}
```
