### ISSUE TITLE
Missing location and population data for GBR counties

### ISSUE THREAD

**Issue by lazd** [covidatlas/coronadatascraper#101]
Tons of GBR counties can't find their respective GeoJSON:

  ❌ Could not find location Channel Islands, GBR
  ❌ Could not find location Bournemouth, Christchurch and Poole, GBR
  ❌ Could not find location Bristol, City of, GBR
  ❌ Could not find location Cornwall and Isles of Scilly, GBR
  ❌ Could not find location Hackney and City of London, GBR
  ❌ Could not find location Herefordshire, County of, GBR
  ❌ Could not find location Kingston upon Hull, City of, GBR
  ❌ Could not find location St. Helens, GBR
  ❌ Could not find location Wirral, GBR

And we're missing population data for tons too:

  ❌ Barking and Dagenham, GBR: ?
  ❌ Barnet, GBR: ?
  ❌ Barnsley, GBR: ?
  ❌ Bath and North East Somerset, GBR: ?
  ❌ Bedford, GBR: ?
  ❌ Bexley, GBR: ?
  ❌ Birmingham, GBR: ?
  ❌ Blackburn with Darwen, GBR: ?
  ❌ Blackpool, GBR: ?
  ❌ Bolton, GBR: ?
  ❌ Bournemouth, Christchurch and Poole, GBR: ?
  ❌ Bracknell Forest, GBR: ?
  ❌ Bradford, GBR: ?
  ❌ Brent, GBR: ?
  ❌ Brighton and Hove, GBR: ?
  ❌ Bristol, City of, GBR: ?
  ❌ Bromley, GBR: ?
  ❌ Bury, GBR: ?
  ❌ Calderdale, GBR: ?
  ❌ Camden, GBR: ?
  ❌ Central Bedfordshire, GBR: ?
  ❌ Cheshire East, GBR: ?
  ❌ Cheshire West and Chester, GBR: ?
  ❌ Cornwall and Isles of Scilly, GBR: ?
  ❌ County Durham, GBR: ?
  ❌ Coventry, GBR: ?
  ❌ Croydon, GBR: ?
  ❌ Darlington, GBR: ?
  ❌ Derby, GBR: ?
  ❌ Doncaster, GBR: ?
  ❌ Dudley, GBR: ?
  ❌ Ealing, GBR: ?
  ❌ Enfield, GBR: ?
  ❌ Gateshead, GBR: ?
  ❌ Greenwich, GBR: ?
  ❌ Hackney and City of London, GBR: ?
  ❌ Halton, GBR: ?
  ❌ Hammersmith and Fulham, GBR: ?
  ❌ Haringey, GBR: ?
  ❌ Harrow, GBR: ?
  ❌ Hartlepool, GBR: ?
  ❌ Havering, GBR: ?
  ❌ Herefordshire, County of, GBR: ?
  ❌ Hillingdon, GBR: ?
  ❌ Hounslow, GBR: ?
  ❌ Islington, GBR: ?
  ❌ Kensington and Chelsea, GBR: ?
  ❌ Kingston upon Hull, City of, GBR: ?
  ❌ Kingston upon Thames, GBR: ?
  ❌ Kirklees, GBR: ?
  ❌ Knowsley, GBR: ?
  ❌ Lambeth, GBR: ?
  ❌ Leeds, GBR: ?
  ❌ Leicester, GBR: ?
  ❌ Lewisham, GBR: ?
  ❌ Liverpool, GBR: ?
  ❌ Luton, GBR: ?
  ❌ Manchester, GBR: ?
  ❌ Medway, GBR: ?
  ❌ Merton, GBR: ?
  ❌ Middlesbrough, GBR: ?
  ❌ Milton Keynes, GBR: ?
  ❌ Newcastle upon Tyne, GBR: ?
  ❌ Newham, GBR: ?
  ❌ North East Lincolnshire, GBR: ?
  ❌ North Lincolnshire, GBR: ?
  ❌ North Somerset, GBR: ?
  ❌ North Tyneside, GBR: ?
  ❌ Nottingham, GBR: ?
  ❌ Oldham, GBR: ?
  ❌ Peterborough, GBR: ?
  ❌ Plymouth, GBR: ?
  ❌ Portsmouth, GBR: ?
  ❌ Reading, GBR: ?
  ❌ Redbridge, GBR: ?
  ❌ Redcar and Cleveland, GBR: ?
  ❌ Richmond upon Thames, GBR: ?
  ❌ Rochdale, GBR: ?
  ❌ Rotherham, GBR: ?
  ❌ Salford, GBR: ?
  ❌ Sandwell, GBR: ?
  ❌ Sefton, GBR: ?
  ❌ Sheffield, GBR: ?
  ❌ Slough, GBR: ?
  ❌ Solihull, GBR: ?
  ❌ South Gloucestershire, GBR: ?
  ❌ South Tyneside, GBR: ?
  ❌ Southampton, GBR: ?
  ❌ Southend-on-Sea, GBR: ?
  ❌ Southwark, GBR: ?
  ❌ St. Helens, GBR: ?
  ❌ Stockport, GBR: ?
  ❌ Stockton-on-Tees, GBR: ?
  ❌ Stoke-on-Trent, GBR: ?
  ❌ Sunderland, GBR: ?
  ❌ Sutton, GBR: ?
  ❌ Swindon, GBR: ?
  ❌ Tameside, GBR: ?
  ❌ Telford and Wrekin, GBR: ?
  ❌ Thurrock, GBR: ?
  ❌ Torbay, GBR: ?
  ❌ Tower Hamlets, GBR: ?
  ❌ Trafford, GBR: ?
  ❌ Wakefield, GBR: ?
  ❌ Walsall, GBR: ?
  ❌ Waltham Forest, GBR: ?
  ❌ Wandsworth, GBR: ?
  ❌ Warrington, GBR: ?
  ❌ West Berkshire, GBR: ?
  ❌ Westminster, GBR: ?
  ❌ Wigan, GBR: ?
  ❌ Windsor and Maidenhead, GBR: ?
  ❌ Wirral, GBR: ?
  ❌ Wokingham, GBR: ?
  ❌ Wolverhampton, GBR: ?
  ❌ York, GBR: ?

I tried figuring it out, but I'm unfamiliar with these counties and the data sources available for them, so I gave up. Can someone please look into this?

**Comment by veyEskelson** [comment]
https://github.com/martinjc/UK-GeoJSON

https://martinjc.github.io/UK-GeoJSON/

Your list seems to be of Local Authority districts.

**Comment by veyEskelson** [comment]
United Kingdom: https://gadm.org/download_country_v3.html  shapefile gadm36_GBR_2
[gadm36_GBR_2.zip](https://github.com/lazd/coronadatascraper/files/4344880/gadm36_GBR_2.zip)

**Comment by lazd** [comment]
@veyEskelson thanks, I was so confused (what's a county? what's a district?). Can you work with @enrichman to get the data in?

**Comment by veyEskelson** [comment]
@lazd Sure

**Comment by veyEskelson** [comment]
2018 population for local authorities in UK
source:https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates/articles/overviewoftheukpopulation/august2019

Looks to have all the locations on your list.
[UK2018_population.zip](https://github.com/lazd/coronadatascraper/files/4345193/UK2018_population.zip)

**Comment by jzohrab** [comment]
Hi @osvyg and @veyEskelson , is the data now present?  Thanks for the PR, @osvyg.  Cheers, jz

**Comment by hyperknot** [comment]
This is now fixed.
