### ISSUE TITLE
Add scraper for San Francisco

### ISSUE THREAD

**Issue by 1ec5** [covidatlas/coronadatascraper#1011]
## Location name
San Francisco County, CA, USA

## Source URL
https://data.sfgov.org/COVID-19/COVID-19-Cases-Summarized-by-Date-Transmission-and/tvq9-ec9w/
https://data.sfgov.org/COVID-19/COVID-19-Hospitalizations/nxjg-bhem

## Notes/comments
Like the Santa Clara County Public Health Department (#965), the San Francisco Department of Public Health is now reporting a full time series by date of sample collection rather than reporting date. This means many days’ counts can be retroactively updated on any given day. They’re reporting historical data for all the counts, not just confirmed cases, though they only seem to be providing hospitalization counts up to a certain number of weeks back.

There’s [already a scraper for San Francisco](https://github.com/covidatlas/coronadatascraper/blob/master/src/shared/scrapers/US/CA/san-francisco-county.js), but it scrapes the main dashboard in a way that’s more fragile and doesn’t reflect these retroactive updates.

Unlike Santa Clara County, this source is quite easy to work with. They provide a CSV for download or a REST API to get the table as JSON. As a point of reference, [this Bash script](https://gist.github.com/1ec5/88c9670dcd108d1493a957fb6ac8d819) updates [a table at Wikimedia Commons](https://commons.wikimedia.org/wiki/Data:COVID-19_cases_in_San_Francisco.tab) (used on [this Wikipedia article](https://en.wikipedia.org/wiki/COVID-19_pandemic_in_the_San_Francisco_Bay_Area#Statistics)) with the latest data using the API. I’m not suggesting to rely on Wikimedia Commons or Wikipedia, but perhaps some of the `jq` invocations could be ported to JavaScript.

**Comment by lazd** [comment]
Oh this is great. Do you think you can pick up this issue @1ec5?

**Comment by jzohrab** [comment]
Done in #1022 and #1044.
