### ISSUE TITLE
IMPORTANT - We are moving to Li -- https://github.com/covidatlas/li

### ISSUE THREAD

**Issue by jzohrab** [covidatlas/coronadatascraper#1037]
**This project is being replaced by [Li](https://github.com/covidatlas/li), the next-generation serverless crawler for COVID-19 data.**

The reasons for the switchover are documented in [Issue 782](https://github.com/covidatlas/coronadatascraper/issues/782).

We are not _actively_ accepting PRs for this repository, but are still using this repo to track issues.

> Scraper code written for this project is not compatible with Li, see that project for examples.  We have some helpers to assist in migrating code, see [this document](https://docs.google.com/document/d/1ITPU0hESswmiWw88Pl1eI26oIQtMJw1YUeD8mWEPIeE/edit#).

Thanks very much!

**Comment by rtwfroody** [comment]
Is this why timeseries.csv does not contain any data beyond 2020-06-01?
