### ISSUE TITLE
Data not Refreshed - last MAX(date) = 2020-05-27

### ISSUE THREAD

**Issue by tlampe0615** [covidatlas/coronadatascraper#1039]
Data hasn't refreshed

Last data was 2020-05-27

**Comment by jzohrab** [comment]
Hi @tlampe0615 , thanks for getting in touch.  There was a delay launching, but that has been fixed.  Checking https://coronadatascraper.com/#timeseries-byLocation.json, the last date there is 2020-05-29.  Cheers! jz

**Comment by lazd** [comment]
Thanks @tlampe0615, there was a bug the prevent automatic release and I was visiting my mother in the hospital and unable to fix it. It's fixed now and we have fresh data, sorry for the delay.
