### ISSUE TITLE
Possible Intermittent US State County level reporting issues - FYI

### ISSUE THREAD

**Issue by JimBudde** [covidatlas/coronadatascraper#105]
Just noticed this on page where Colorado Data was scraped.  Only state totals were provided.  County and demographic data removed at the moment.

"Due to the high volume of tests being processed by the state lab and a need to get the information out quickly, today’s case summary does not contain a demographic breakdown. Demographic data will be provided as soon as the lab is able to provide the statistical breakdown."

**Comment by lazd** [comment]
Yes, I saw that and it angered me. https://github.com/lazd/coronadatascraper/blob/master/scrapers.js#L610
