### ISSUE TITLE
2020.07.03 data missing several featureIds

### ISSUE THREAD

**Issue by rg3h** [covidatlas/coronadatascraper#1060]
1 'missing featureId' 'Australia'
4 'missing featureId' 'Brazil'
10 'missing featureId' 'India'
15 'missing featureId' 'New Zealand'
17 'missing featureId' 'Panama'
20 'missing featureId' 'Russia'
28 'missing featureId' 'Thailand'

other countries have the featureId and previous days had featureIds for these countries. I can pull from countryId or use a separate look up, but it seems odd that they are missing now and for just these countries.

**Comment by jzohrab** [comment]
hmmmm, @rg3h is this an issue in the Li reports?  https://covidatlas.com/data

Everything _should_ be present.

**Comment by rg3h** [comment]
These countries are present in the Li reports
