### ISSUE TITLE
didn't see data on 07/13 and 07/14

### ISSUE THREAD

**Issue by acertas** [covidatlas/coronadatascraper#1063]
I am using this api to query data: "https://coronadatascraper.com/timeseries.csv". But it seems doesn't have 07/13 and 07/14 data generally. I checked the #home website, it update until 07/14. 

Anyone know why this api doesn't update anymore or is there a new api for the data?

Thank you so much.

**Comment by jzohrab** [comment]
It should be updating every night.  It's possible that there was an issue with the automated launch last night.

fyi we are moving to a new project, Li, which will have slightly different reports.  I've tagged you on that issue in the project -- https://github.com/covidatlas/li/issues/284.

**Comment by acertas** [comment]
Thank you so much. So this api is still updating? do you guys notice the issue as I have or just me can't find the recent two days data

**Comment by jzohrab** [comment]
I just checked with the nightly launch script maintainer and he said that there was a problem with the launch the past few nights; hopefully it will now be fixed!  Let us know, and if it's fixed, please close this issue.  Cheers! jz

**Comment by acertas** [comment]
Thank you so much for confirm this. Good luck and appreciated with your group's effort

**Comment by eskirk** [comment]
@jzohrab seems that this issue is still present - I am only seeing data up to 7/12 at the `coronadatascraper.com/timeseries.csv` endpoint.

**Comment by jzohrab** [comment]
Hi @eskirk - we've been running into issues with the launches of coronadatascraper.com.  I've recently switched the reports over to the Li reports, and everything appears to be working correctly, with data included.

Can you take a look at the reports in https://covidatlas.com/data to verify?  Cheers! jz

**Comment by jzohrab** [comment]
Closing due to no response, I assume it is working.
