### ISSUE TITLE
Change CDS build to pull down reports from Li v1 folder

### ISSUE THREAD

**Issue by jzohrab** [covidatlas/coronadatascraper#1064]
Currently, CDS runs its own set of scrapers to get and scrape data.  We are moving over to Li and eventually will likely convert the existing CDS coronadatascraper.com site to serverless; however, until then, we should stop generating reports in CDS, and just pull them down from Li.

* Disable the "yarn start" and "yarn timeseries" commands
* Change the CDS build to pull down reports from Li 'v1/latest' prod report buck and add to dist, commit them as part of the build.
* Ensure the CDS site still builds???
* delete links for things we don't generate anymore

**Comment by jzohrab** [comment]
This has been merged to master, now waiting for it to be launched to prod.

**Comment by jzohrab** [comment]
Done and looks good.

**Comment by TomGoBravo** [comment]
@jzohrab Does this mean that https://coronadatascraper.com/timeseries.csv.zip is now a product of project Li? I'm trying to make sure CAN has switched to Li without breaking anything on our side. Is there a stable URL for fetching the project Li v1 timeseries data as CSV?

**Comment by jzohrab** [comment]
Hi @TomGoBravo - yes, those reports are now generated from Li.  That report is currently at https://liproduction-reportsbucket-bhk8fnhv1s76.s3-us-west-1.amazonaws.com/v1/latest/timeseries.csv

The link is at https://covidatlas.com/data along with the other reports.

The timeseries.csv should be _pretty much_ the same ... see the docs for that at https://github.com/covidatlas/li/blob/master/docs/reports-migrating-from-cds-to-li.md#timeseriescsv.  The fields are all there (except for growth factor ... an oversight!), and some other fields added.

**Comment by TomGoBravo** [comment]
Cool, thank you and congrats on getting this out.
