### ISSUE TITLE
Issue with Florida Data Numbers 

### ISSUE THREAD

**Issue by kantaloupe** [covidatlas/coronadatascraper#1066]
I was looking at the numbers for Florida and there is a huge spike on 7/16/2020 where the numbers almost double in the continue to be wrong from that date onwards. The total number of cases and deaths does not match what is currently on the Florida Health Webpage.  

I do know that on that same day the Florida Health page accidentally doubled the numbers but it was fixed that same day. For some reason, your code did not update their fix.  

![floridahealth](https://user-images.githubusercontent.com/68627502/88131921-1d9f1600-cbac-11ea-9e3d-05b34065581a.PNG)
![cdsflorida](https://user-images.githubusercontent.com/68627502/88131925-1e37ac80-cbac-11ea-87e4-ead38292cbb3.PNG)

**Comment by jzohrab** [comment]
Hi @kantaloupe , thanks for the issue.

I just checked our graphs on https://covidatlas.com/florida-us, and the numbers look OK to me.  Can you verify?  Cheers! jz

**Comment by jzohrab** [comment]
No response, closing.
