### ISSUE TITLE
File an issue and tag the person that wrote the scraper when it fails

### ISSUE THREAD

**Issue by lazd** [covidatlas/coronadatascraper#11]
I'm not sure this is possible, but it would be really slick.

**Comment by sorny92** [comment]
As a work around we can just add the @ to the github user in the Google sheets

**Comment by jzohrab** [comment]
This is possible, but I don't think that we'd want to automate this as there is too much volatility in source data.

I'm limiting the backlog now and so will close this issue -- if it comes up again, we'll deal with it then.  There are several other issues dealing with "quality monitoring", I'll put together a doc for future as a spec.
