### ISSUE TITLE
Texas deaths not captured

### ISSUE THREAD

**Issue by veyEskelson** [covidatlas/coronadatascraper#114]
https://www.dshs.state.tx.us/news/updates.shtm#coronavirus
Texas has its first death due to the virus. Added additional table for deaths and testing to webpage.
death in Matagorda county.

**Comment by lazd** [comment]
Hmm, they don't list deaths by county, but we can certainly add it to the state-level data.

**Comment by lazd** [comment]
Uhg, was just looking back into this issue and they've already had their second death. :'(

**Comment by StevenBryceLee** [comment]
County level records are available for cases, not deaths

**Comment by Shoeboxam** [comment]
Resolved by 2c686063302f6f3031f8e08b3ad79c0c79ba3b62

**Comment by jzohrab** [comment]
Confirmed, this is included in the output for Texas.
