### ISSUE TITLE
Provide index.json and index.csv with links for time series

### ISSUE THREAD

**Issue by lazd** [covidatlas/coronadatascraper#13]
Don’t make people guess what dates are available, provide an index on the site and in releases.

**Comment by jzohrab** [comment]
Added note to API design doc, https://docs.google.com/document/d/1Rdcy0D9C2jZvpgdH4-cOxybOkgiiWTlCUn_RsnAUOKQ/edit?pli=1#

**Comment by jzohrab** [comment]
Closing as I'm not sure what this is referring to, beyond the API notes mentioned above.  I don't feel this is relevant to Li.  Please open a Li issue if I'm wrong! jz
