### ISSUE TITLE
Implementing scraper for Spain (Official government data)

### ISSUE THREAD

**Issue by sorny92** [covidatlas/coronadatascraper#14]
Hello there!
I have the source data for spain and it's states but this data is in a pdf. I got the way to transform the data from pdf to html so then I can parse it properly.

A far I've seen the parser is in JS, should I create an intermediate project where I do this step and then parse my own data?

**Comment by lazd** [comment]
Let’s avoid the intermediate project, I’d rather have the parser fo straight to the source where possible.

Can you look into doing the parsing of the PDF in your scraper itself, and finding the data without converting it to HTML?

Take a look at:
https://github.com/mozilla/pdf.js

**Comment by sorny92** [comment]
oh! That makes sense!
I will give it a try

**Comment by sorny92** [comment]
Ok,
I'm starting with the scraper and I'm finding myself with problems setting the invironment.
I'm running ```Ubuntu 18.04```
node version: ```v12.16.1```
yarn version: ```1.22.4```

So far I've run:
```bash
yarn install
yarn start
```
I got an error related to some node arguments but I updated node to the version I said in the top and there wasn't error anymore.
When I run: ```yarn start``` now I get the next error:
```bash
yarn run v1.22.4
$ NODE_OPTIONS='--insecure-http-parser' node index.js
internal/modules/cjs/loader.js:1174
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/esteve/projects/coronadatascraper/index.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1174:13)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ERR_REQUIRE_ESM'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I have not that much experience in JS development, I'm more of  a Python guy myself :disappointed:

**Comment by sorny92** [comment]
I've been trying the last couple hours and I haven't been able to scrap the PDF. I'm having mainly two problems:
1. When I fetch the pdf and I try to visualize it in the cache folder it looks empty (although size is ~500kb, the correct one should have around ~300kb)
I tried the fetch method that is already implemented in the code and also:
```javascript
// parse the binary data downloaded from the fetch function
PDFJS.getDocument({data: body})

// Download directly the file and then parsing it.
PDFJS.getDocument(url)
```
In all of the cases the file is blank.

2. Another problem (which I'm not sure, I've just read about it trying to figure out how to parse properly the PDF) is the fact that you can parse the pdf but actually not really read the content because it just creates a canvas to be able to visualise it.


I will try tomorrow to create a task I can just run in my server to parse it in Python and then fetch the data from there, which is really not ideal. But I can't see any other option right now.It's damn annoying that they are uploading the data in a fucki*** pdf.

**Comment by mark-otaris** [comment]
While not an official government source, Esri España has [a dashboard](https://coronavirus.esri.es) with cases, deaths, and recovered for each autonomous community, and there’s [a CSV](https://opendata.arcgis.com/datasets/48fac2d7de0f43f9af938852e3748845_0.csv) of the data, which seems up-to-date for now.

**Comment by jzohrab** [comment]
Hello @sorny92 and @mark-otaris , we do have a scraper for ESP now, pulling data from https://github.com/datadista/datasets/tree/master/COVID%2019, specifically:

```
    {
      name: 'cases',
      url: 'https://raw.githubusercontent.com/datadista/datasets/master/COVID%2019/ccaa_covid19_casos.csv',
      description: 'Cases by date and community'
    },
    {
      name: 'recovered',
      url: 'https://raw.githubusercontent.com/datadista/datasets/master/COVID%2019/ccaa_covid19_altas.csv',
      description: 'Recoveries by date and community'
    },
    {
      name: 'deaths',
      url: 'https://raw.githubusercontent.com/datadista/datasets/master/COVID%2019/ccaa_covid19_fallecidos.csv',
      description: 'Deaths by date and community'
    }
```

Does this satisfy this issue?

Thank you! jz

**Comment by jzohrab** [comment]
Closing this issue as I believe it's resolved.  Thanks again! jz
