### ISSUE TITLE
Create github issue integration for cross-check report

### ISSUE THREAD

**Issue by judepayne** [covidatlas/coronadatascraper#146]
Please could we have an integration where the results of the cross-check report can be posted as a new issue to a configurable github repo?
The cross-check report is json. Please create from them an easy-to read text (.e.g. markdown) summary that can be posted as the body of the issue, for example:

Automated cross-check report: <date of time of the run>

Location | Type | Source 0 | Source 1 | .. Source n | Sources
---------|------|-----------|---------|----------|---------
Australian Captial Territory, Aus | cases | 3 | 2 | | 0: https://github.com/CSSEGISandData/COVID-19, 1: "https://www.health.gov.au/news/health-alerts/novel-coronavirus-2019-ncov-health-alert/coronavirus-covid-19-current-situation-and-case-numbers"
FRA | cases | 9043 | 9874 | | 0: "https://github.com/CSSEGISandData/COVID-19", 1: "https://raw.githubusercontent.com/opencovid19-fr/data/master/dist/chiffres-cles.csv"
FRA | deaths | 148 | 11 | | 0: "https://github.com/CSSEGISandData/COVID-19", 1: "https://raw.githubusercontent.com/opencovid19-fr/data/master/dist/chiffres-cles.csv"

The sources 0 ... n could be ordered descending according to the rating in the cross-check report where the highest number indicates the primary source.

Thanks!

**Comment by lazd** [comment]
This is a great idea. I don't know if issues are the right place. Effectively, we want a human to check the data manually and tell us which is right. We need to work with systems that humans who do that are familiar with. The folks at COVIDTracking have a full editorial process that something like this would slot beautifully into, and they've stated that they shy away from github issues for that because the journalists that are working on it aren't comfortable with issue tracking tools. So we have to find a balance.

**Comment by judepayne** [comment]
Right. Solving this task seems to be about getting a sustainable workflow which maximises automation and only raises the cant-be-resolved-automatically exceptions to people, or from what I've seen it's a case in drowning in request-to-fix X type requests.
We'll see if the Johns Hopkins repo maintainers are interested in getting help and in what form.

Perhaps for this issue, if you're interested and feel it would be useful, separate the summary report from the channel/s it's delivered into?

**Comment by jzohrab** [comment]
This is a good idea but is no longer relevant with the new project (Li).  Thank you for the issue, closing.  cheers! jz
