### ISSUE TITLE
Add actual webpage URLs to scraper object as a separate field when source is raw data

### ISSUE THREAD

**Issue by lazd** [covidatlas/coronadatascraper#152]
Some of our URLs are raw data sources, we should probably add human readable URLs to the scraper object so we can do things like direct users to their state or county website when they click.

**Comment by jzohrab** [comment]
@lazd , is this the `sources` element in some scrapers? eg for AU/VIC:

```
  sources: [
    {
      description: 'Victoria State Government Health and Human Services Department',
      name: 'Victoria State Government Health and Human Services',
      url: 'https://www.dhhs.vic.gov.au'
    }
  ],
```

Perhaps this can be closed.

**Comment by jzohrab** [comment]
Closing, this is related to https://github.com/covidatlas/coronadatascraper/issues/431 - "Add pretty names for sources".
