### ISSUE TITLE
Detail crosscheck report in page on the website

### ISSUE THREAD

**Issue by lazd** [covidatlas/coronadatascraper#156]
A crosscheck report exists in `report.json` `scrape->crossCheckReport`. It should exposed on the website.

**Comment by andys1376** [comment]
Is there any more work needed for this issue?

**Comment by jzohrab** [comment]
Closing, we're not updating this project, and the crosscheck report isn't created in the new project (Li).  Please reopen this issue in Li if you disagree.  Cheers! z
