### ISSUE TITLE
Change request for timeseries.csv header/attribute name of "recovered"

### ISSUE THREAD

**Issue by DavidGeeraerts** [covidatlas/coronadatascraper#164]
@lazd 
the [timeseries.csv](https://coronadatascraper.com/timeseries.csv) has a header/attribute of "recovered" with a data-type of date, which would make one think it's when the record was "scraped" i.e. recovered, but that is the language that the medical community is using for patient outcome = recovered. I'd like to suggest changing the header/attribute name to something else: i.e. _date-retrieved_.

**Comment by lazd** [comment]
@DavidGeeraerts whoa, sounds like a bug. I will look into it

**Comment by jzohrab** [comment]
Fixed looooooooooong ago.  Cheers, closing! z
