### ISSUE TITLE
Map filters and options

### ISSUE THREAD

**Issue by NateBaldwinDesign** [covidatlas/coronadatascraper#171]
Filters:
Nice to be able to filter by country. This gives more fidelity to data when max is segmented by the region specified.

Options:
May be nice to expose options for visualization. First, would be nice to signify data- cases, recoveries, deaths. Secondly it would be nice to select the comparator- by percent of population, by percent of cases, total numbers, etc.

**Comment by jzohrab** [comment]
Closing this for now.  At the moment I feel we're pivoting slightly to be a data provider, versus a UI provider.  It's a good suggestion, but not one I wish to clog the long backlog.  Thanks @NateBaldwinDesign ! jz
