### ISSUE TITLE
use ISO 8601 date format

### ISSUE THREAD

**Issue by hyperknot** [covidatlas/coronadatascraper#194]
I recommend using [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date format. 

For date it'd be: `2020-03-20`
For time it'd be: `2020-03-20T13:25:45`

This is the industry standard for human and machine readable dates. We are basically almost doing it, but are missing the leading 0-s. 

The advantage of iso dates is that all programming languages and all date libraries have built-in, tested functions for parsing and writing ISO 8601 strings.

I recommend not adding time offset and standardising everywhere in UTC times. 

For a JS library, especially once we start handling timezones, I recommend [luxon.js](https://moment.github.io/luxon/), from the developers of Moment.js.

**Comment by lazd** [comment]
Yes, absolutely. See #42 and #48

**Comment by camjc** [comment]
There’s some work in one of the current PRs to consume using js-joda, might be worth you having a CR mate :)
