### ISSUE TITLE
France missing recovered data

### ISSUE THREAD

**Issue by Wikunia** [covidatlas/coronadatascraper#225]
@samirrayani I saw that you have implemented the France scraper. Unfortunately the repository seems to miss the recovered cases. Maybe they can be included using the JHU data? @lazd

**Comment by samirrayani** [comment]
I don't have any specifics for that scraper. I was involved with refactoring `scrapers.js` into multiple files so that's why my name was attached to changes in the file: https://github.com/lazd/coronadatascraper/pull/162

**Comment by Wikunia** [comment]
Thanks I think it might be @osvyg then?

**Comment by jzohrab** [comment]
Hi @Wikunia , I see recovered cases on https://coronadatascraper.com/#data.csv right now, e.g.

State | Country | Cases  | Deaths | Recovered
-- | -- | -- | -- | --
Centre-Val de Loire | FRA |   | 84 | 179
Bourgogne-Franche-Comté | FRA |   | 271 | 746
Normandie | FRA |   | 81 | 224
Hauts-de-France | FRA |   | 370 | 857

I believe this issue can be closed, please confirm.  Thanks! jz

**Comment by jzohrab** [comment]
Closing this issue as I believe it's resolved.  Thanks again! jz
