### ISSUE TITLE
Scraper status slack message should report & compare total case counts 

### ISSUE THREAD

**Issue by chunder** [covidatlas/coronadatascraper#233]
So we seem to be counting more total cases for the USA than other sources. If I sum up all the cases in all the counties we are scraping, I get 21.7k. If I sum the state level counts, which we source from covidtracking.com I get 17.1k. The USA level number which we also source from covidtracking.com is 17.0k.
21,681 cases summed from all county level cases that we scrape
17,133 cases summed from state level cases we pull from covidtracking.com
17,038 cases at the USA level that we pull from covidtracking.com

It would be nice to see these stats update with every #scraper-status report.

**Comment by jzohrab** [comment]
Hi @chunder - we're now doing all of the reporting in the new codebase (Li), and I'm not sure how this applies to that.  In the timeseries-byLocation report, we show "warnings" and "sources" for each data point, were you looking for stats from that?  I did notice an over-reliance on covidtracking's numbers.
