### ISSUE TITLE
Can geography.addEmptyRegions already know the full list of counties (USA) ?

### ISSUE THREAD

**Issue by chunder** [covidatlas/coronadatascraper#235]
Right now there's a bunch of tedious and possibly error prone work to curate a list of all counties in a state. This list is passed to geography.addEmptyRegions so that it can assign 0 counts to all regions not otherwise reported by a state.

But the list of all counties in each state is available in `coronavirus-data-sources/population/population-usa-counties.csv`. Can we provide a convenience method to pull them out?

**Comment by lazd** [comment]
Absolutely possible. I already did something like that in another branch while testing a curated data source: https://github.com/lazd/coronadatascraper/blob/sarasource/scrapers/SARASOURCE.js#L51-L57

**Comment by jzohrab** [comment]
Closing as I don't believe we should be doing this, as mentioned in https://github.com/covidatlas/li/issues/50.  cheers! z
