### ISSUE TITLE
Proposal: Crawl timeseries separately

### ISSUE THREAD

**Issue by HerbCaudill** [covidatlas/coronadatascraper#250]
For sources without timeseries data, we're building a synthetic timeseries from periodic crawls, which is a brilliant hack. 

Scrapers for sources that _do_ have timeseries data, however, currently have to deal with a lot of complexity and weirdness that comes from trying to use all the scrapers in the same way, with the SCRAPE_DATE environment variable etc. Just glancing through the scrapers, between a third and half of the code in each one is devoted to dealing with this. 

I'd suggest changing the crawler so that if a datasource has a timeseries, it just runs it once and pulls the whole timeseries from that. That will make these scrapers much cleaner and easier to write. 

Each of the existing timeseries scrapers would need to be modified to return all dates instead of just one. At the moment there are only 6 (JHU, BRA, CHE, ESP, FRA, ITA), so it's feasible to make this change now. It will become harder as more timeseries sources are added. 

I'm happy to submit a PR if this seems like a good idea.

**Comment by jzohrab** [comment]
This is a great idea, which I've moved to Li in https://github.com/covidatlas/li/issues/254.  I'll close this as we won't implement it for this repo.  Thanks @HerbCaudill ! jz
