### ISSUE TITLE
We are building a RESTful-API based on your datascraper :-)

### ISSUE THREAD

**Issue by martiL** [covidatlas/coronadatascraper#253]
Thanks for this great project! 

In the course of the hackathon "https://wirvsvirushackathon.org/ " we are implementing a RESTful web service that uses the scrapper to provide the data. We have developed a landing page to make it easier for many interested people to implement a scraper or/and use our API

check it out: 
https://corona-api-landingpage.netlify.com/

**Comment by jzohrab** [comment]
Thank you very much!  We have just created a list of consumers in a [google spreadsheet](https://docs.google.com/spreadsheets/d/16pqZAI8pnHM_ahDyajkZuctQHPHJt_nbdudmple2gLg/edit#gid=0) , you're the very first entry.  I'll update the list as others let us know.

Cheers and best wishes from our team to yours.
