### ISSUE TITLE
New HTTP API based upon the data gathered here

### ISSUE THREAD

**Issue by ndom91** [covidatlas/coronadatascraper#256]
Hi All,

Just wanted to let you guys know, we created an API based upon the data gathered here. We clone the repo daily, run it, and store the results on a server.

From there users can query it like any other HTTP JSON API. We only have a few endpoints / filtering options, but we're always open for suggestions / PRs :)

We linked to you guys a few times from our landing page and gave a little intro on how users can add new scrapers to your repo as well. If its interesting to you, maybe you can link back ;)

Links:
- [API Repo](https://github.com/coronaapi/coronaapi)
- [Landing Page](https://corona-api-landingpage.netlify.com/)

This was a part of the German Government's #wirvsvirus hackathon this weekend.

@martiL @brauls

**Comment by jzohrab** [comment]
Hey @ndom91 , thanks very much, I had actually already added you as the first of a list of consumers of our work.  Regards and best of luck with your project, I hope you and your team and family are all doing well.  We're still working away, and likely will be doing some large restructuring of the code.  If the data gets unstable for you, please let us know via a GitHub issue.

Cheers! jz
