### ISSUE TITLE
Development Roadmap? 

### ISSUE THREAD

**Issue by Jord-Holt** [covidatlas/coronadatascraper#273]
Given the speed at which this project has ramped up over the past days/weeks. I think the need for a formalized development roadmap will soon become necessary. We will likely see many more people getting involved in this project and it will become imperative that we have guidelines/goal posts established to help us identify what tasks/issues our focus should be in so that we do not have development focus shifting away from our ultimate end goal(s).   Perhaps githubs Milestones feature would be the best thing to utilize here?

I’m not deep enough into this to know exactly what the upcoming goal posts are but I hope in the least that this could start that conversation and get it in our queue, or alternatively get this information shared if it already exists. Two goals that come to mind right off would be the establishment/finalization of our infrastructure and reaching 100% coverage on county data. Both of which are well underway and well understood. But what comes next?

**Comment by lazd** [comment]
See #236 for some insights!

**Comment by ryanblock** [comment]
Not nearly sufficient, but also: https://docs.google.com/document/d/1Kr6tybWx70pro6rApaYrDd1M58POcCWk5JzxEa-4S_8/edit

We'll be working to shore up internal comms around this asap! Many plates in the air atm.

**Comment by ryanblock** [comment]
A followup: https://github.com/lazd/coronadatascraper/issues/295

**Comment by qgolsteyn** [comment]
See #782
