### ISSUE TITLE
Crowd sourcing help needed for JHU region mapping

### ISSUE THREAD

**Issue by hyperknot** [covidatlas/coronadatascraper#275]
We'd need some crowdsurcing help to complete the following table, by looking up codes from the country-level list. I made a Google Spreadsheet we can edit together. Instructions should be visible on the right side.

**Comment by jeffchenoweth** [comment]
Do you just want all the county fips codes in the US?

**Comment by hyperknot** [comment]
We've been discussing this on the Slack channel. The conclusion is the following:

- id0, id1, id2, id3 where possible, these are from Natural Earth and guaranteed to be public domain and have Wikidata links which means up-to-date population information

For US, FIPS codes for counties with state code, so that we can use Census datasets, so it'd be `fips:CA-06085`

For the rest of the world, HASC, so `hasc:ES.MD`

**Comment by jeffchenoweth** [comment]
I'm wondering if you are only missing the ones listed or if you need all of them - there are way more US counties than listed in that sheet.

**Comment by hyperknot** [comment]
We only need to map from JHU strings to something consistent. For our own county scrapers we can use the reference list.

**Comment by jeffchenoweth** [comment]
OK, done for US Counties.
