### ISSUE TITLE
Illinois data and source out of date

### ISSUE THREAD

**Issue by alexmill** [covidatlas/coronadatascraper#290]
Illinois publishes their county level data here: http://www.dph.illinois.gov/covid19

The currently used source for the raw data is here, which hasn't been updated since 3/17: http://www.dph.illinois.gov/sites/default/files/COVID19/COVID19CountyResults.json

It appears they keep changing the name of the URL each day, without even saving all intermediate days. Today's JSON data is available here: http://www.dph.illinois.gov/sites/default/files/COVID19/COVID19CountyResults20200323.json

It looks like [USAFacts.org](https://usafacts.org/visualizations/coronavirus-covid-19-spread-map/) has been getting the daily county data, so we could at least back-fill the past few days from their CSV.

I'm not quite sure how to go about correcting past data or ensuring the URL for new scrapes remains updated, but I'm happy to help if I can.

**Comment by lazd** [comment]
Oh no! That's annoying, but we can work around it. @qgolsteyn wrote a scraper that has different URLs each day, it's a pain, but we can do it. As far as back-filling data, we have a strategy on that too, but it's still in the works.

@qgolsteyn can you work with @alexmill to get the scraper updated with a daily changing URL?

**Comment by qgolsteyn** [comment]
Last commit to master fixed IL, USA. Keeping this issue open to remember to backfill missing dates

**Comment by alexmill** [comment]
Thanks @qgolsteyn. I think they just have someone manually editing the file source each day, so I'll keep an eye on the Illinois data over the next couple days and update with any further issues. 

Commit here for reference: https://github.com/lazd/coronadatascraper/commit/b4a347d5d7aab2bee4eff8ffeb2af59288d94865

**Comment by alexmill** [comment]
It seems @chunder is also working on this here: https://github.com/lazd/coronadatascraper/commit/7ebba5a1b6973c50eba70bc33d5a9159d38d01b4

Just a thought so this doesn't have to be updated manually everyday: Can we scrape the HTML page [here](http://www.dph.illinois.gov/topics-services/diseases-and-conditions/diseases-a-z-list/coronavirus) and just extract the URL from the Plotly script:

`Plotly.d3.json('/sitefiles/COVIDTestResults.json', function (err, rows) {`

Again, from what I can tell, this line of code is being updated manually everyday, with inconsistent naming. Unless we get talk to someone directly in Illinois to encourage better practices, this approach seems like it would cause the least hassle.

**Comment by chunder** [comment]
This sounds smart.

**Comment by alexmill** [comment]
I've tried to address this issue but I'm not sure how to do so while also fixing the historical data. Rather than trying to make my own PR, I'll just describe my proposed solution in case someone else wants to build on it. It seems liked @chunder or @qgolsteyn have been working on this scraper recently.

The raw JSON URL is updated (manually from what I can tell) within the Plotly javascript every at this source page: http://www.dph.illinois.gov/topics-services/diseases-and-conditions/diseases-a-z-list/coronavirus

Here are the JSON URLs for the past few days:

3/22: http://www.dph.illinois.gov/sites/default/files/COVID19/COVID19CountyResults20200322.json
3/23: http://www.dph.illinois.gov/sites/default/files/COVID19/COVID19CountyResults20200323.json
3/24: http://www.dph.illinois.gov/sitefiles/COVIDTestResults.json
3/25: http://www.dph.illinois.gov/sites/default/files/COVID19/COVID19CountyResults202003250.json
3/26: http://www.dph.illinois.gov/sites/default/files/COVID19/COVID19CountyResults20200326.json

The inconsistencies between days suggest that we should make sure to update the JSON URL directly from the source page every day, unless we want to manually fix this every time it breaks.

My proposal: Every day (from now on), make sure we get a fetch of the [source page](http://www.dph.illinois.gov/topics-services/diseases-and-conditions/diseases-a-z-list/coronavirus). As long as we download that page, we can always programmatically extract the JSON URL, using the code below:

```
const sourcePage = 'http://www.dph.illinois.gov/topics-services/diseases-and-conditions/diseases-a-z-list/coronavirus';
const sourceScrape = await fetch.fetch(sourcePage, date);
const regex = /Plotly\.d3\.json\('(.+)',/gm;
const match = regex.exec(sourceScrape);
this.url = `http://www.dph.illinois.gov${match[1]}`;
```
I'm having trouble getting my code to work for both forward and backward compatibility, but I hope this can make it easier for someone with more knowledge to incorporate this fix.

**Comment by jzohrab** [comment]
IL appears to be fine.  http://www.dph.illinois.gov/sitefiles/COVIDTestResults.json is reporting on data, and the Li scraper us/il/index.js is parsing it correctly.  Closing this, cheers! z
