### ISSUE TITLE
Map color is incorrect

### ISSUE THREAD

**Issue by alangwilson** [covidatlas/coronadatascraper#306]
The map seems to be using a different color scale than the color legend.
<img width="341" alt="Screen Shot 2020-03-24 at 9 21 15 AM" src="https://user-images.githubusercontent.com/14807518/77444236-38ee4600-6db1-11ea-9519-ad3dc50bde53.png">

**Comment by lazd** [comment]
@NateBaldwinDesign does #153 fix this?

**Comment by NateBaldwinDesign** [comment]
Not sure exactly what’s being marked as a bug here. The yellow and red areas are most likely correct, as the scale is continuous. #153 updates ensure that they’re the same, yes.

But is this bug referring to the blue text from the map? @alangwilson

**Comment by NateBaldwinDesign** [comment]
If this is regarding the yellow, orange, and red colors on the map & legend, then this should be closed as it is merely a play on the perception of color. The colors on the map and legend (taken from the same geographic location) can be identified as accurate along the color scale:

![image](https://user-images.githubusercontent.com/13972198/77481457-50e1bc00-6de9-11ea-9995-41fdce05711c.png)

**Comment by jzohrab** [comment]
Closing, assuming ok.

**Comment by ciscorucinski** [comment]
I think what the reported issue dealt with was not the scale, as they match. However, the displayed color doesn't seem to match the percentage given the range.

Basically: 0.001742 / 0.006739 ~= .25 or 25% of the scale. Divide the bar into 4, and this region should show the color of the 1st divisopn at 25%, or a yellow-orange-ish color, not a dark red.
