### ISSUE TITLE
Need to do case-insensitive matching of county names

### ISSUE THREAD

**Issue by chunder** [covidatlas/coronadatascraper#314]
`DeKalb County, GA` is sometimes publishing their stats with a lowercase k as `Dekalb County`. This lowercased version is not matching and generating an error:

`  ❌ Could not find location Dekalb County, GA, USA`

We need to do case-insensitive matching.

**Comment by chunder** [comment]
I also wonder if we should surface "Could not find location" errors as a sign of a scraper regression? Scrapers should not be reporting stats for locations that we don't have in our geojson. Or if they are, it should be explicitly whitelisted somehow.

**Comment by chunder** [comment]
Also, after the case-insensitive match we should record the data under the canonical county name from our geojson. Not the county name we scraped from the source -- it could have odd case.

**Comment by lazd** [comment]
`geography.getCounty()` can be used to fix this. Yay!
