### ISSUE TITLE
Add a test to be sure scrapers don't return 0s if the source is unavailable

### ISSUE THREAD

**Issue by chunder** [covidatlas/coronadatascraper#315]
Another test I think we should do is run each scraper with a mocked fetch that returns 404 and then assert that the scraper doesn't return any results. We have scrapers that return zeros when they error. Returning 0 cases/deaths/etc is not the desired behavior if the source in inaccessible.

@samirrayani thinks this could go in here:

https://github.com/lazd/coronadatascraper/blob/master/src/events/crawler/scrapers.test.js

**Comment by jzohrab** [comment]
Hi @chunder, some questions:
* what are some of the bad scrapers returning 0's?
* what should a 404'd scraper return?
Thank you! jz

**Comment by chunder** [comment]
It's not that the scrapers are bad. It's that the source webpage changes and the scraper no longer works against the new layout/content/format. We had 2-3 last night that exhibited this problem. We scrambled and fixed them before the final data push.

It would be better if they failed by returning no data (ie: an empty array) rather than returning a pile of 0 case counts for all the counties in the state.

**Comment by jzohrab** [comment]
I misspoke.  I don't know what a bad case is, can you give me an example of a scraper that no longer works, if for example it 404's?  I see changes in master with `git log --oneline upstream/master -- src/events/crawler/scrapers` but I'm not sure which correspond to the fixes.

**Comment by jzohrab** [comment]
We have a simple html table validator now, PA uses it:

```
      const rules = {
        headings: {
          0: /county/i,
          1: /number of cases/i,
          2: /deaths/i
        },
        data: [
          { column: 0, row: 'ANY', rule: /Adams/ },
          { column: 1, row: 'ALL', rule: /^[0-9]+$/ },
          { column: 2, row: 'ALL', rule: /(^[0-9]+|)$/ }
        ]
      };
      const opts = { includeErrCount: 5, logToConsole: true };
      htmlTableValidation.throwIfErrors($countyTable, rules, opts);
```

I think that covers part of this question, the other part is that we should handle things differently if the source is completely unavailable.  At the moment, I'm not completely sure what happens if a source is offline.  I see various errors in the log, it should behave ... a bit better, I think: report source unavailability clearly, and carry on.

**Comment by jzohrab** [comment]
This is handled correctly in Li, closing as we won't fix it here.
