### ISSUE TITLE
Add "like JHU" CSV for deaths

### ISSUE THREAD

**Issue by davegotz** [covidatlas/coronadatascraper#322]
The "like JHU" csv option for confirmed cases is very helpful for people looking to fix their code after JHU's change in time series data model.  However, it only seems to have confirmed cases.

Can you add a version of the same file format but with death statistics as well?

**Comment by lazd** [comment]
Please just switch to `timeseries.csv`, it's a much more sane format.

**Comment by lazd** [comment]
@davegotz have you checked out `timeseries.csv`? Can you use that instead?

**Comment by jzohrab** [comment]
Closing this issue due to no response.  The Li reports contain this data as well.
