### ISSUE TITLE
US country level data

### ISSUE THREAD

**Issue by piccolbo** [covidatlas/coronadatascraper#327]
I noticed that there are only five data points for US cases, all after 3/19. I compared this with a roll-up of state cases. That roll up is complete going back to 22/1. But comparing the 5 US country level points with the rollups, the numbers are similar, but not quite (off by 12000 for yesterday for  instance). Suggestions? THanks

roll up:

```
	
2020-03-23 54398 
2020-03-22 30166 
2020-03-21 22922
2020-03-20 16651
2020-03-19 11364
2020-03-18 7953
2020-03-17 6050
2020-03-16 4456
2020-03-15 3527
2020-03-14 2734
2020-03-13 2127
2020-03-12 1590
2020-03-11 1214
2020-03-10 89
```

Country-level

```
city  county state country population   lat  long url                            date       type  value
  <lgl> <chr>  <chr> <chr>        <dbl> <dbl> <dbl> <chr>                          <date>     <chr> <dbl>
1 NA    NA     NA    USA      326625791  45.1 0.762 https://covidtracking.com/api… 2020-03-19 cases 11723
2 NA    NA     NA    USA      326625791  45.1 0.762 https://covidtracking.com/api… 2020-03-20 cases 17038
3 NA    NA     NA    USA      326625791  45.1 0.762 https://covidtracking.com/api… 2020-03-21 cases 23203
4 NA    NA     NA    USA      326625791  45.1 0.762 https://covidtracking.com/api… 2020-03-22 cases 30128
5 NA    NA     NA    USA      326625791  45.1 0.762 https://covidtracking.com/api… 2020-03-23 cases 42164

```

**Comment by zbraniecki** [comment]
Yep, noticed it as well.
I'm about to switch from https://github.com/pomber/covid19 which has data for the US dated back to Jan 22nd. It would be great to backlog that here to ease the switch.

**Comment by lazd** [comment]
Is this still an issue?

**Comment by cristipp** [comment]
US counts look reasonable to me.

**Comment by piccolbo** [comment]
No, solved. I had implemented  a workaround so I wasn't keeping an eye on it anymore. Thanks!
