### ISSUE TITLE
1point3acres data

### ISSUE THREAD

**Issue by shaperilio** [covidatlas/coronadatascraper#332]
I've spent a few days working with the JHU data and finally came across your project. Wow. Thank you. Thank you for citing sources. Thank you for scraping so meticulously.

Before yours, I had found this one: 

https://coronavirus.1point3acres.com/#map 

They also cite sources carefully, track (to some extent) when shelter in place orders were put into effect, and claim that they are doing some very careful validation - but their data set is closed.

As of this writing, it seems your data is lagging a bit behind theirs (or there is some other discrepancy). For example, the map at https://coronadatascraper.com/#features.json tells New York (state) has 20,875 cases and they claim 26,374.

Could this be an issue of scraping frequency?

I hope you're able to get access to their data and work together.

Looking forward to looking through your project further and, hopefully, contributing in some way.

**Comment by edwlook** [comment]
They have an application to request API access, could be worth trying - https://docs.google.com/forms/d/e/1FAIpQLScMGcazASoCxrcYJuBRxlOsAtpeTeyz1YWXJdZxPnFzbNvZRA/viewform

**Comment by shaperilio** [comment]
Just did a quick spot check on San Francisco - yours showed the same number of cases now that they had yesterday, so maybe it's just the timing of the scraping.

**Comment by jzohrab** [comment]
Hi @shaperilio, I haven't checked the data for this yet, but do feel this issue can be closed, given your last comment?  Regards! jz

**Comment by jzohrab** [comment]
Closing per slack convo with @shaperilio just now.
