### ISSUE TITLE
Chicago case counts are missing?

### ISSUE THREAD

**Issue by chunder** [covidatlas/coronadatascraper#339]
Looks like IL reports Chicago separately from Cook County which contains it. I don’t see our code handling this. And our we report 412 for Cook, where Cook+Chicago is more like 1200.

**Comment by alexmill** [comment]
Yeah from what I can tell the entry for "Cook" county actually represents Cook county cases minus Chicago cases. I'm working on fixing the URL here https://github.com/lazd/coronadatascraper/issues/290 and can see if I can handle this as well.

I think I'll aggregate Cook + Chicago to "Cook County, IL, USA" and then create a separate city entry for Chicago. Their data has been so inconsistent lately though. I'm afraid they're just gonna change it up again tomorrow 😖 .

**Comment by jzohrab** [comment]
Hi @chunder and @alexmill .  Some PRs mentioning this have been merged.  Is this resolved now?  Cheers! jz

**Comment by alexmill** [comment]
Does seem like this is being handled here: https://github.com/covidatlas/coronadatascraper/blob/master/src/shared/scrapers/US/IL/index.js#L59

**Comment by jzohrab** [comment]
Thanks @alexmill , I'll assume that this issue is resolved.  If not, please open a new one.  Thank you! jz
