### ISSUE TITLE
French states duplicated

### ISSUE THREAD

**Issue by zbraniecki** [covidatlas/coronadatascraper#365]
Many French states exist in two forms - with and without accents, covering different timespans.

Examples:
 - `Ile-de-France` and `Île-de-France`
 - `Grand-Est` and `Grand Est`
 - `Saint-Barthélemy` and `Saint Barthelemy` 

They should be unified.

**Comment by hyperknot** [comment]
This will be fixed when we move to ISO codes. 
https://github.com/hyperknot/country-levels/blob/master/docs/iso2_list/FR.md#level-4

**Comment by lazd** [comment]
@qgolsteyn is this still an issue?

**Comment by zbraniecki** [comment]
fixed
