### ISSUE TITLE
Change ARCGIS sites to start at public facing host page

### ISSUE THREAD

**Issue by joshuaellinger** [covidatlas/coronadatascraper#383]
It would be a lot more maintainable and easy to validate if we start with the public facing host page and pull the source from the iframe.

Right now, if the state moved to a new GIS page and let the old one up, you wouldn't notice for a while.  If they take it down, you have to go find the original UI page.

**Comment by jzohrab** [comment]
Closing as this falls under report monitoring and data validation which has an issue already.  It's a good point, thank you!
