### ISSUE TITLE
testing missing for 15 US states

### ISSUE THREAD

**Issue by zbraniecki** [covidatlas/coronadatascraper#386]
Compared to yesterday, today's JSON misses testing data for the following states:

```
Washington,
Lousiana,
Indiana,
Virginia,
Missisipi,
New York,
Texas,
Tennessee,
Ohio,
North Carolina,
Alabama,
Maryland,
Delaware,
Wyoming,
South Dakota,
```

**Comment by lazd** [comment]
Yes, we were pulling testing data from COVID Tracking, and we've replaced that with our direct-from-state data sources.

If you want the best and most accurate state-level data for `tested`, I would suggest hitting COVID Tracking's API: https://covidtracking.com/data/

HOWEVER, if, for any of the states you've listed above, you can find testing data on the sources we're currently scraping, file an issue and we'll add it into the dataset!

@zbraniecki if none of the sources for the states listed above are providing testing data, go ahead and close this issue. Thanks!

**Comment by zbraniecki** [comment]
What's the reason not to use COVID Tracking as a backup for direct-from-state? This would give you the same data for states that we have direct sources for, and the baseline for those we don't, no?

**Comment by lazd** [comment]
We still pull it down, but we do not "combine" data between sources, we just filter out duplicates.

**Comment by zbraniecki** [comment]
1) I miss how is it combining? If sourceA has data for Washington use it, if not use data from sourceB?

2) Why not combine (sourceA has data for Washigton till 3-11, sourceB from 3-12)?

**Comment by lazd** [comment]
We pull all the data for WA from their health department, then we include it in the dataset.

We pull the data for WA from COVIDTracking, then we include it in the dataset.

There is a de-dupe process that chooses one over the other. If COVIDTracking has testing, but WA health department doesn't, and if we give WA health department a higher priority, then we don't get testing data in the final dataset.

**Comment by zbraniecki** [comment]
Ah, that makes sense. I see! Of course, that means that you'd have to merge.

I filed issue #410 to discuss something a bit more flexible.

**Comment by zbraniecki** [comment]
Thank you for taking time to explain it to me!

**Comment by jzohrab** [comment]
Closing this issue as it appears to have been resolved.  In addition, Li reports now report "multivalent data", combining data from multiple sources.  See https://github.com/covidatlas/li/blob/master/docs/reports.md#combining-data-sources.  If this still feels like an issue, please open up a new issue in the Li project.  Cheers! jz
