### ISSUE TITLE
Remove DEU scraper data

### ISSUE THREAD

**Issue by jgehrcke** [covidatlas/coronadatascraper#387]
We replaced the DEU scraper with state-specific parsers. Yet, out-of-date DEU data remains to be in the system, e.g. in https://coronadatascraper.com/#timeseries-byLocation.json -- do we have a process for purging "old" scrapers?

**Comment by lazd** [comment]
@jgehrcke I would say set a higher priority on your state-specific scrapers, do the rollup to replace DEU with `transform.sumData()` and leave the old scraper intact.

If we remove the old scraper, we will lose data from the timeseries!

**Comment by jgehrcke** [comment]
@lazd Thanks.

> do the rollup to replace DEU with transform.sumData() and leave the old scraper intact.

I previously asked a question here on GitHub and in Slack about whether or not to remove the country-wide scraper when introducing state-level scrapers.

Sounds like you would have disagreed with his commit which was merged as part of #196 : https://github.com/lazd/coronadatascraper/commit/36d4197c0530dad59e9a4ad0fcc8b1d1bce39322

To make it really explicit: you suggest to keep the country-level scraper, and to make the numbers be _consistent_ with the state-level scraper, yes?

> If we remove the old scraper, we will lose data from the timeseries!

Well, yeah, that was exactly the intent behind this issue: I thought we rather want to get rid of the country-wide scraper and its data in the cache, when this scraper isn't active anymore.

**Comment by lazd** [comment]
Yeah I may have missed that commit, but here's the deal -- if a scraper got data once upon a time, and we remove that scraper, UNLESS we have added a new scraper that covers that same place with timeseries data, when we regenerate the timeseries, whatever data the old scraper gathered will be missing from the timeseries.

Is the data from the scraper you're proposing to remove totally covered with timeseries data from the new scrapers? If so, we can remove it.

**Comment by jgehrcke** [comment]
> Is the data from the scraper you're proposing to remove totally covered with timeseries data from the new scrapers? If so, we can remove it.

A definite Yes.

Background: the 16 state scrapers in sum conceptually replace the country-wide scraper. We have a bottom -> up system in Germany, there are no cases to be expected associated with the country, but not associated with any state.

One good reason to include the country-wide scraper could potentially be for users looking for the _sum_ in this project to easily see it. However, I think that should be (maybe already is?) solved on a logical level, all state-level scrapers already annotate the same country: `DEU`. :-)

**Comment by lazd** [comment]
@jgehrcke just wanted to check back on this issue and see if we can close it now! Thanks!

**Comment by hyperknot** [comment]
Also #690

**Comment by jzohrab** [comment]
Hi @jgehrcke , thanks for double-checking.  If I don't hear from you in 5 days, I'll assume this issue has been resolved and will close it.  Thanks again! jz

**Comment by jzohrab** [comment]
Closing, thanks all. jz

**Comment by jgehrcke** [comment]
> Is the data from the scraper you're proposing to remove totally covered with timeseries data from the new scrapers? If so, we can remove it.

I think we converged to a decision here: that we want to remove the DEU scraper data. Let's reopen unless we have new arguments.
