### ISSUE TITLE
Hospitalizations data (a'ka serious cases)

### ISSUE THREAD

**Issue by zbraniecki** [covidatlas/coronadatascraper#390]
Is it possible to start accumulating hospitalization data?

It seems that hospitalizations (a'ka `serious cases`) is an important bit of information that would be good to track alongside other numbers.

**Comment by zbraniecki** [comment]
Here's penn state data https://github.com/CodeForPhilly/chime including:
```
CHIME enables capacity planning by providing estimates of total daily (i.e. new) and running totals of (i.e. census) inpatient hospitalizations, ICU admissions, and patients requiring ventilation.
```

We could even aim for:
* hospitalizations
* ICU admissions
* ventliation

**Comment by zbraniecki** [comment]
This source shows critical - https://www.worldometers.info/coronavirus/

**Comment by zbraniecki** [comment]
Data for New York on illness/respiratory - https://weinbergerlab.shinyapps.io/NYC_syndromic/

**Comment by zbraniecki** [comment]
Ooh, `COVIDTracking` now shows hospitalized data for states - https://covidtracking.com/data/state/new-york/#history

**Comment by tautme** [comment]
Good point on tracking severity of case. I noticed Arkansas started reporting hospitalized, on ventilator, nursing home, gender, and age. Should all this data be collected?

**Comment by qgolsteyn** [comment]
We started gathering hospitalization data! See https://github.com/covidatlas/coronadatascraper/blob/master/docs/data_fields.md
