### ISSUE TITLE
Los Angeles county on 03/12 incorrect

### ISSUE THREAD

**Issue by kendonB** [covidatlas/coronadatascraper#398]
```r
# A tibble: 8 x 6
  adm0_name adm1_name  adm2_name          adm3_name date       cum_confirmed_cases
  <chr>     <chr>      <chr>              <chr>     <date>                   <dbl>
1 USA       California Los Angeles County NA        2020-03-08                  14
2 USA       California Los Angeles County NA        2020-03-09                  14
3 USA       California Los Angeles County NA        2020-03-10                  20
4 USA       California Los Angeles County NA        2020-03-11                  27
5 USA       California Los Angeles County NA        2020-03-12                   0
6 USA       California Los Angeles County NA        2020-03-13                  40
7 USA       California Los Angeles County NA        2020-03-14                  53
8 USA       California Los Angeles County NA        2020-03-15                  69
```

**Comment by kendonB** [comment]
Situations like this should really be in there as missing right?

**Comment by lazd** [comment]
@kendonB lots of stuff is missing on 3-12 -- that was the day after JHU stopped providing county level data, and the day before I this project started to exist. We'll back-fill the data some day.

**Comment by lazd** [comment]
Wondering if this is related to #374 ...

**Comment by jzohrab** [comment]
@lazd, this scraper calls parse.number: `cases: parse.number($('.counter').first().text()` and parse.number says `  if (string === '') return 0;`.

This method is used extensively in the code: `find . -name '*.js' -print0 | xargs -0 grep -i 'parse.number' | wc -l` => 438.  Perhaps we should change the method to let callers specify the default return value for empty strings (either `null` or 0).

**Comment by jzohrab** [comment]
Re-opened as https://github.com/covidatlas/coronadatascraper/issues/807, "parse.number('') should return null, not 0".  Closing this.
