### ISSUE TITLE
Collect reasonable set of algorithms to perform on the data

### ISSUE THREAD

**Issue by zbraniecki** [covidatlas/coronadatascraper#403]
Once this dataset grows, it may be useful to start accumulating JS algorithms to apply on the data.

It'll likely be a separate repo, but linked to this one so that this data can be directly operated on using this data model.

My idea is that assuming we can eventually come to a sensible coverage of core raw numbers per day (`cases`, `deaths`, `hospitalizations`, `ventliations`, `recovered`)
We could coordinate working on best calculations like exponential moving average, % of infected population, or predictions derived from the data like probable actual number of infected people, `point of no return` for the medical system etc.

My argument for cooperating on this is that a lot of us are not data scientists, and in particular epidemiologists, and as we roll different ways to view the same data we really want to convey some meaning behind it and we are at risk of spreading misleading information if we're not careful.

As an example of that, the current dataset allows us to show `cases per million`, but data scientists from my company pointed out to me that this is a potentially misleading data:

> (...) when measuring number of cases on the y-axis, this is only dependent on time and the 
> interactions of people (so population density, or social distancing, definitely affect the curve). The 
> total size of the population of the country doesn't matter, unless it's a tiny country like Lichtenstein 
> maybe, where you could reach a limit to the number of people affected really quickly and the curve
> would become a flat line. You could estimate the population of any country to be infinite...it's kind of 
> like a thermodynamics problem. (...)

Collecting a single repo where such algorithms are collected and explained and experts are being asked to evaluate quality of the algorithms and meaningfulness of the outcome, may be a good next level on top of this data.

Not ready to go for it, we're still early in building a reliable collection of raw data sources, but filing it now to help people talk about this potential next step.

**Comment by zbraniecki** [comment]
As one algorithms I'd like to play with is the exponential curve vs. population satiation. The exponential predictions require flattening out at some point as the virus reaches saturation in the population and starts flattening out as it gets to the upper boundary of the infected population.

All the measures in the "flatten the curve" approach aim to push the point at which the growth rate slows down earlier so that the curve doesn't just stop on saturation of the population. Having ability to calculate which regions deviate from that and start slowing down earlier than saturation point would be awesome.

**Comment by zbraniecki** [comment]
Or calculating the R=

**Comment by jzohrab** [comment]
I like this idea a lot, but at the moment we're simply working on getting scrapers going. :-)  In v2 reports I intend to release all the raw data per location.  If we can do interesting and useful calculations, that would be great, but I feel that's beyond this project's scope at the moment.  Closing, thank you! jz
