### ISSUE TITLE
How to supply a live JSON datafeed

### ISSUE THREAD

**Issue by gitcnd** [covidatlas/coronadatascraper#407]
My data is immediately usable for any live charting application (news tickers, real-time charts, pandemic leaderboards, etc)

Do a "view source" to see how to load my JSON file.

https://cryptinc.com/covid19/covid19_predictor.html

Unlike other feeds, I also include the outbreak paramaters and the functions for producing real-time (up to the second) forecasts (upto a week ahead, and back to any day in the past)

e.g. see this clock demo: https://cryptinc.com/covid19/clock.htm

**Comment by gitcnd** [comment]
https://github.com/gitcnd/coronavirus-data-sources/tree/master/curated

**Comment by lazd** [comment]
I'm not sure what I'm looking at here, does this use our data?

**Comment by jzohrab** [comment]
Hello @gitcnd, I'm not sure what this issue is about.  As lazd asked above, does this use our data?  Thanks and regards.

**Comment by jzohrab** [comment]
Closing this issue, the team isn't clear what the issue is.  Regards and best of luck! jz
