### ISSUE TITLE
Enable combining data from multiple sources (i.e. cases from one, tested from another)

### ISSUE THREAD

**Issue by zbraniecki** [covidatlas/coronadatascraper#410]
As pointed out in #386 we currently use a single source with a fallback on another one if needed.

But different sources may provide different data for the same region or even different quality of data over time.

It'd be great to be able to have something like:

```json
{
  "region": "WA, USA",
  "sources": {
    "sourceA": {},
    "sourceB": {},
    "datasets": {
      "cases": [{"from": null, "to": null, "order": ["sourceA", "sourceB"]}],
      "testing": [{"from": null, "to": null, "order": ["sourceB"]}],
      "recovered": [
        {
          "from": null,
          "to": "2020-3-11",
          "order": ["sourceA"]
        },
        {
          "from": "2020-3-12",
          "to": null,
          "order": ["sourceB"]
        }
      ]
    } 
  }
}
```

**Comment by lazd** [comment]
We already can use different sources for different time ranges, generally when we add a new source, it only starts at the date we added it (unless it's a timeseries).

**Comment by zbraniecki** [comment]
@lazd any update on this one?

**Comment by lazd** [comment]
@zbraniecki unfortunately no, this isn't something we've looked at yet. We should take a look at doing this in the new architecture here https://github.com/covidatlas/li

**Comment by jzohrab** [comment]
This is implemented in Li.  I didn't see this issue and so didn't implement it per the above spec, but the reporting is clear (at least to me!), and we can easily determine the provenance of data.  See, eg, https://github.com/covidatlas/li/blob/master/docs/reports.md#combining-data-sources.  I'm closing this issue, but if you see any obvious improvements we can make to the Li reports let me know, or submit a PR.  Cheers! jz
