### ISSUE TITLE
Active count may end up negative, depending on how locations handle data (ref issues 412-414)

### ISSUE THREAD

**Issue by jzohrab** [covidatlas/coronadatascraper#416]
`geography.js` has the following:

```
export const getActiveFromLocation = function(location) {
   ... [snip] ...
    return location.cases - location.deaths - location.recovered;
    ... [snip] ...
};
```

Some locations appear to only include live people in "cases", e.g.:

![image](https://user-images.githubusercontent.com/1637133/77719599-4c650100-6fab-11ea-9a67-b919b7219a2b.png)

CHN has cases: 168; deaths: 6; recovered: 168.  `getActiveFromLocation` returns 168 - 6 - 168 = -6.

This bug causes issues
#412 
#413 
#414

**Comment by jzohrab** [comment]
Some of these (with undefined in the columns) would have already been fixed by commit 84e8a277 from @qgolsteyn , but the CHN line would still be erroneous.

We could do the obvious:

```
var active = return location.cases - location.deaths - location.recovered;
if (active < 0) {
  active = 0;
}
return active;
```

but it feels too simplistic.

If "cases" includes deaths, the formula is good.
1000 cases, of these 500 died, 10 recovered.  active = 1000 - 500 - 10 = 490

If "cases" does not include deaths, it doesn't work.
1000 cases, 10 recovered (and there are also 500 deaths): active = 990
(i.e., There are 1000 current cases.  There used to be 1500, but 500 died already.)

**Comment by lazd** [comment]
I think we need to drop `active`. @camjc  @qgolsteyn @chunder ?

**Comment by chunder** [comment]
I think if `active < 0` then return `null` not `0`.

**Comment by jeffchenoweth** [comment]
I'd hate to drop active cases.  It's going to become much more important to decision making in the future as cases begin to drop.  I think it should be an error flag in scraper-status if it returns negative active to check the scraper for how it's being calculated.

**Comment by chunder** [comment]
Is anyone suggesting that we should stop tracking and reporting active cases completely? My suggestion is that we report it when we have the data to do so. When we don't have the data needed, we omit it.

**Comment by lazd** [comment]
Yes @chunder , I'm not sure we should calculate `active` at all. It seems too prone to errors. If the source provides it pre-calculated, then we can use it.

That said, every time we have an error where `active` is less than zero, then that means there is something funky with the data source -- either we're pulling the number of cases wrong, or cases is not cumulative, or something like that...

**Comment by jzohrab** [comment]
Even if active is > 0, is could still be misleading, unfortunately.  e.g., both location X and Y started with 1500 sick people, and both have had 500 deaths, and have 10 recovered.  They should look the same, but X only reports current living cases (cases = 1000), Y includes deaths (cases = 1500).

Per the formula, active = (current) cases - deaths - recovered:

|X|Y|
|--|--|
|= 1000 - 500 - 10|= 1500 - 500 - 10|
|= 450|= 990|

To use, both 450 and 990 look like reasonable numbers, but only the 990 is correct.

CHN wasn't included deaths in their case numbers, the same as location X.  The only reason that CHN showed up as negative was because their recovered = case count.

**Comment by jzohrab** [comment]
We're no longer using "active" anywhere that I can see.  Closing this.
