### ISSUE TITLE
docs: methodology

### ISSUE THREAD

**Issue by Akuukis** [covidatlas/coronadatascraper#420]
Great stuff! I'm considering to reuse your data via some API for my dashboard [Pandemic Estimator](https://pandemic-estimator.net/) but I wish it had a better documentation on methodology. I'm using JHU directly and I know what chaos it is, the most blatant example being that they provide "cumulative data" that's not cumulative quite often in practice. And the whole change of file formats, etc.

Can you please describe methodology how you deal with it? How do you deal with inconsistencies between data sources? What has been omitted, what has been "adjusted" and how? Thank you!

**Comment by lazd** [comment]
Oh yeah, so you can check our `report.json` to see which data was been omitted.

ABSOLUTELY NOTHING has been adjusted. We're not in the business of forecasting or fudging. We pass along what our sources report, and we cite our sources. Corrections and adjustments are outside the scope of our project.

**Comment by Akuukis** [comment]
I think that answer would be best served by being somewhere visible on website, e.g. https://coronadatascraper.com/#sources

On the other side I've seen firsthand many problems with JHU source but not in your data, therefore this reply doesn't really answer my curiosity of what happened to those problems.

**Comment by jzohrab** [comment]
Hi @Akuukis, I'm getting into some documentation soon.  Can you give an example where JHU has a data issue, but this project doesn't?  Regards, jz

**Comment by Akuukis** [comment]
@jzohrab Hi! It has been a while, but here's what I remember:

Example No.1 is France. It was "France, <empty>" at the start, then it bacame "France, France" with other "France, <otherStuff>" along it. Then Mar 23 is missing data, and afterwards it became "France, <empty>" again but "France, <otherStuff>" still was there. (or other way around, I may have forgotten). This raises the following questions:
1. What exactly is rolled up at country level, with emphasis on how we can be sure that something's not counted twice or excluded?
2. How gaps are back-filled?

Example No.2 I don't remember exactly, but there was few locations where cumulative amount was decreasing at some points.

I wrote some tests for JHU data in fact. See them [at this commit](https://github.com/Akuukis/pandemic-estimator/tree/9801ee023489793fa628a7c6e198e632ac6cd90a) before I migrated to Corona Data Scraper. Once cloned, do `make install` and `make update` to see a lot errors and warnings. Let me know if you have questions on that

**Comment by jzohrab** [comment]
Thanks for responding @Akuukis.

1. We're working with several data sources.  Sometimes countries and states both report, and they're inconsistent.  We de-dupe our sources, and use source "ratings" to break ties.  The code for this is `src/events/processor/dedupe-locations/`.  Unfortunately, due to our dependence on source data, it's very hard to _guarantee_ that we're not excluding anything, but recently we have moved to standardized country/state data which will perhaps help with that.

2. When we scrape data for a given location, we cache the files for each date (recently changed to caching for each date-time, to allow for multiple scrapes).  Currently we do have gaps in these files, as sources change their reporting or move the sources.  The best we can do at this point would be to use the latest possible file to fill any gap, i.e. if we have a file for Monday and for Wednesday, but not Tuesday, we'd use Monday's data to fill in Tuesday. 

fyi - I tried building that commit, but it failed (I'm on a Mac):

```
.... [SNIP] ...
../src/weakref.cc:168:75: error: too few arguments to function call, single argument 'context' was not specified
  Local<Object> proxy = Nan::New<ObjectTemplate>(proxyClass)->NewInstance();
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
... [other errors]

make[1]: *** [Release/obj.target/weakref/src/weakref.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node@12/12.16.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/Cellar/node@12/12.16.1/bin/node" "/usr/local/Cellar/node@12/12.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jeff/Documents/Projects/pandemic-estimator/node_modules/weak
```

If you do see data issues, we'd appreciate it if you opened a new Data Issue and reference the spot!

Cheers, jz

**Comment by Akuukis** [comment]
Hi,

I think we misunderstood each other. I dont see any data issues with your data, or at least haven't searched for them carefully enough, but I saw a lot of issues with JHU. What's I mean by this issue "docs: methodology" is a plain-english big-picture explanation of what what's going on inside `dedupe-locations` and elsewhere.

Regarding the errors, let's just skip the JS dependencies because you don't need them. In such case please run (in Bash)
```
pip3 install -r requirements.txt --user
./scripts/fetch_raw_data.py
./scripts/export.py
```

**Comment by jzohrab** [comment]
Ah, got it.  Yes, we have a data scientist who is working on various data documentation.  I don't have a timeline on that.

re your code: I ran into errors.  Can you make sure that this project runs on a clean install, to a new directory, without any preconditions/assumptions about state?

```
# error one:
MacBook-Air:pandemic-estimator jeff$ ./scripts/fetch_raw_data.py
Traceback (most recent call last):
  File "./scripts/fetch_raw_data.py", line 52, in <module>
    urllib.request.urlretrieve(url_template.format(current_date.month, current_date.day), filepath)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 257, in urlretrieve
    tfp = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'tmp/2020-01-23.csv'

# hack
MacBook-Air:pandemic-estimator jeff$ mkdir tmp
MacBook-Air:pandemic-estimator jeff$ touch tmp/2020-01-23.csv

# works up to a point
MacBook-Air:pandemic-estimator jeff$ ./scripts/fetch_raw_data.py
Cached tmp/2020-01-24.csv
Cached tmp/2020-01-25.csv
...
Traceback (most recent call last):
  File "./scripts/fetch_raw_data.py", line 76, in <module>
    records.append(parser(row, current_date))
  File "./scripts/fetch_raw_data.py", line 34, in parseVersion1
    return (row[0], row[1], date, normalize_zero(row[3]), normalize_zero(row[4]), normalize_zero(row[5]))
  File "./scripts/fetch_raw_data.py", line 19, in normalize_zero
    return int(something)
ValueError: invalid literal for int() with base 10: 'US'
```

Or optionally, please just give me the list of what you're looking at.  Thanks! jz

**Comment by Akuukis** [comment]
Sorry, I guess my report would too outdated to be relavant. Here's a recent problem, that cumulative is not cumulative: https://github.com/CSSEGISandData/COVID-19/issues/1250#issuecomment-613856442

**Comment by jzohrab** [comment]
Closing this issue as the reports generated from Li use a different method for report data: the data is reported by "priority".  In future, we'll include rollups, and also simply export all existing data.  If further questions arise, we'll deal with it in the new project.  cheers! jz
