### ISSUE TITLE
Wrong coordinates for USA

### ISSUE THREAD

**Issue by martiL** [covidatlas/coronadatascraper#423]
![image](https://user-images.githubusercontent.com/5569498/77764265-aeba1200-703c-11ea-95bb-ee8301b59565.png)

The data set of " https://covidtracking.com/api/states" has wrong coordinates. 

reproduce:
go to: https://corona-api-dashboard.netlify.com/
select "all" for source

**Comment by lazd** [comment]
LOL nice. Thanks for the report, we'll have to track down why that's happening...

**Comment by lazd** [comment]
Also, your tracker looks AWESOME, but you need to look at the `aggregate` property and ignore things that are aggregated; i.e. `CA, USA` will have `aggregate: county`, so you shouldn't draw it because you're going to draw its counties individually. Same for `USA`, really.

**Comment by martiL** [comment]
> Also, your tracker looks AWESOME, but you need to look at the `aggregate` property and ignore things that are aggregated; i.e. `CA, USA` will have `aggregate: county`, so you shouldn't draw it because you're going to draw its counties individually. Same for `USA`, really.

Ah, thx for the hint :)
@ndom91

**Comment by hyperknot** [comment]
I might not understand this properly, but this might have nothing to do with us. We are covidatlas and covidtracking is an unrelated project on GitHub.

**Comment by jzohrab** [comment]
Hello @martiL, it looks like this issue has been resolved.  Can you let me know?

Also, as hyperknot asked, you mentioned "The data set of " https://covidtracking.com/api/states" has wrong coordinates." - but I believe you meant us, right?  Not covid **tracking**.

We have a list of consumers, can I add your site to that list?

Cheers, great site!  jz

**Comment by martiL** [comment]
@jzohrab You can add my site to your list :-) :
https://www.corona-api.org/
https://app.corona-api.org/

Jep, I meant your data set. But the original data source is "https://covidtracking.com/api/states"

**Comment by jzohrab** [comment]
I believe this issue is now resolved.  @martiL , LMK if things look good on your side.

**Comment by martiL** [comment]
@jzohrab LGTM :-)

**Comment by jzohrab** [comment]
Cheers, thank you!  Closing.
