### ISSUE TITLE
Scraping agents, resources and free tool to help in this project

### ISSUE THREAD

**Issue by vickyrathee** [covidatlas/coronadatascraper#424]
Hey there!

Vikash from [Agenty](https://www.agenty.com/) here.
We'd love to offer a FREE Agenty account to help in setting up scraper quickly using our point-and-click extension with instant preview and more.

https://chrome.google.com/webstore/detail/agenty-advanced-web-scrap/gpolcofcjjiooogejfbaamdgmgfehgff

We already have some agents (in our public dataset) and experts web scraping team to build more.  https://www.agenty.com/docs/how-to/how-to-scrape-covid-19-data-from-websites

![image](https://user-images.githubusercontent.com/6106479/77768586-ae377080-7068-11ea-8e29-b632a4da9cd1.png)

No promotion, just want to help!

**Comment by jzohrab** [comment]
Hello @vickyrathee , thank you for contacting the team!  We've been swamped, and haven't been sure how to use this offer.

Our scrapers are built with javascript, scraping from public sources.  As sources change, we have to deal with the thrash ... it's tough!  How does your team/tool deal with this problem?  If a source updates, how do your scrapers deal with it?

I'm not sure how our tools could collaborate, or how/if we could use your data.  Ours is open source, I don't think yours is, and I'm not sure of your data sources.  We're using gov't sources only.

What are your thoughts?  Cheers, Jeff

**Comment by jzohrab** [comment]
Closing due to no response.  We need to understand data sources, transparency, etc.  Thank you though @vickyrathee, cheers! jz
