### ISSUE TITLE
Pretty names for sources (`url` field)

### ISSUE THREAD

**Issue by Akuukis** [covidatlas/coronadatascraper#431]
## Problem
It's great to have `url` field to see which data comes from which places!

It would be even better to have a "pretty name" for those urls. For example, for "https://github.com/CSSEGISandData/COVID-19" says "Johns Hopkins University" or so.

## Proposal
A non-breaking suggestion would be to provide a map where urls maps to pretty names.

A breaking suggestion would be to change `url` field to `source` field with interface `{title: string, url: string}`. 

## Rationale

I want to present the source to users but they care more about the owner of source than the link to the source.

**Comment by lazd** [comment]
We already have a `sources` field (as well as `curators` for curated date sources), but many scrapers don't have this field populated!

@Akuukis, can you send a PR adding pretty names to every scraper? We will be forever indebted to you.

**Comment by Akuukis** [comment]
@lazd I can look into that but my earliest ETA would be end of Monday. If anyone can do it sooner then please do!

**Comment by lazd** [comment]
Sounds great!

**Comment by jzohrab** [comment]
Hi @Akuukis , this is a nice idea.  Did you make any progress on this?  If not, what would help you make progress on it?  Cheers, regards! jz

**Comment by Akuukis** [comment]
@jzohrab Sorry, no, I didn't. In the end I figured it is not that big a deal for my dashboard, so I skipped this. Sorry for not coming back sooner!

**Comment by jzohrab** [comment]
Np, thanks for replying @Akuukis.  I'll keep this issue open as it's still valid.

What's your dashboard?  I keep a list of consumers for interests' sake.

**Comment by Akuukis** [comment]
@jzohrab That's [Pandemic Estimator](https://pandemic-estimator.net)

**Comment by jzohrab** [comment]
Thanks very much, that's an interesting presentation!  Are you still using us for a source?  I see on the graph footer a link to other sources, eg https://health-infobase.canada.ca/src/data/covidLive/covid19.csv for Canada.

**Comment by Akuukis** [comment]
@jzohrab Thanks! Yes, it's mentioned on "Methodology" page

**Comment by jzohrab** [comment]
Closing, we're addressing this in Li.  cheers! z
