### ISSUE TITLE
Sum of Aggregate active/Recovered cases drop between 24/3/20 and 25/3/20

### ISSUE THREAD

**Issue by FortDigital** [covidatlas/coronadatascraper#438]
![image](https://user-images.githubusercontent.com/62287745/77805750-9bc63280-707a-11ea-8820-643464339648.png)

As per screenshot, the number of active cases dramatically drops between the above dates from 190K to 105K. Recovered Metric also drops significantly across these dates:

![image](https://user-images.githubusercontent.com/62287745/77805896-09725e80-707b-11ea-9686-0315400c5dd9.png)

I understand this might be because of the JHU Data set change to remove Recovered data from their dataset. They have since reinstated this datafeed:

https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series

Im hoping to move our monitor (http://fdcnt001.uksouth.cloudapp.azure.com:8080/d/H7a-pFmRz/covid-19?orgId=1&refresh=1h) from using the JHU dataset to this feed in the near future as the additional datasets give us more options to normalise for Population, and the data is just generally cleaner! This and #405 are the last blockers stopping me from making this change :) For Clarity im using the Timeseries-tidy csv file.

**Comment by lazd** [comment]
Can you suggest a fix?

**Comment by FortDigital** [comment]
Probably beyond my capability TBH. My best guess would be that this lines up with when JHU 'Retired' Recovered datasets, they have since reinstated them with a new name here so it could just be a case of re establishing the previous scraper?:

https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series

**Comment by FortDigital** [comment]
This seems to be fixed since re instating the JHU Scraper
