### ISSUE TITLE
scrapers.all.test.js doesn't handle cases where a scraper has multiple scrapers defined

### ISSUE THREAD

**Issue by jzohrab** [covidatlas/coronadatascraper#450]
`scraper.all.test.js` has the following:

```
      it('returns latest data', async () => {
        const expectedPath = join(testDir, 'expected.json');
        let result = await scraperObj.scraper();
```

For some scrapers, such as USA/AL, `scraperObj.scraper` is an object, not a function: `{ '0': [AsyncFunction: 0], '2020-3-26': [AsyncFunction: 2020-3-26] }`

Currently, the tests are passing in master due to a hack added to `scraper.all.test.js`:

```
      if (scraperObj.state === 'AL' && scraperObj.country === 'USA') {
        // Honestly these linter rules are absurd
        // eslint-disable-next-line
        scraperObj.scraper = scraperObj.scraper[0];
      }
```

This testing idea should support multiple input file formats, just like it supports multiple expected file outputs.

**Comment by HerbCaudill** [comment]
I'll take this.

**Comment by qgolsteyn** [comment]
@HerbCaudill I partially addressed this issue yesterday, feel free to take a different direction on this. Essentially, I used the logic from `runScraper` to handle scraper objects as it was already implemented. I also removed the test to check for the expected value of the for the latest data, as this would be error-prone. It is more deterministic to date-stamp all expected values, and run the scraper at a particular date.

**Comment by qgolsteyn** [comment]
I didn't see the hack when I updated those tests, I'll remove it now.

**Comment by jzohrab** [comment]
I'm working on this, have submitted PR #632, and will follow up with another PR for code.

**Comment by jzohrab** [comment]
Code PR: #636.  With these two PRs, this issue is closed.

**Comment by jzohrab** [comment]
Update: not exactly.  That branch fails when scraper code is updated ... b/c sometimes things hit cache, sometimes they call live sites (which can fail), etc.  The work in PR #636 is useful, but it doesn't solve the problem.  I've sketched out a more complete idea in issue #711, so I'll close this issue in favor of that one.
