### ISSUE TITLE
Could the output data be made available on github as well?

### ISSUE THREAD

**Issue by judepayne** [covidatlas/coronadatascraper#456]
Hi, would it be possible to make the output data (the raw csv's) available on this or another github repo as well as the https://coronadatascraper.com/ site? I feel it would help with the accessibility of this great resource.

**Comment by lazd** [comment]
It's possible, but not something we've considered as we don't want people sending pull requests against raw data.

**Comment by judepayne** [comment]
I get that - fair enough

**Comment by jzohrab** [comment]
Closing in favor of #597.  Thanks!
