### ISSUE TITLE
CHE aggregated data is wrong

### ISSUE THREAD

**Issue by paul-em** [covidatlas/coronadatascraper#460]
Total Cases in Switzerland were going down over the last couple days. Seems like the aggregation is wrong, because the individual cantons look legit.

Visualized here: https://paul-em.github.io/covid-19-curves/?shown=Switzerland&column=cases

**Comment by piccolbo** [comment]
Worldometer latest value is 13377, +500 from yesterday

**Comment by lazd** [comment]
Hmm, maybe they're reporting daily, not cumulative? @paul-em @piccolbo can you investigate at the source https://github.com/daenuprobst/covid19-cases-switzerland/

**Comment by piccolbo** [comment]
If you look bottom row here https://github.com/daenuprobst/covid19-cases-switzerland/blob/master/covid19_cases_switzerland.csv after sorting by date, there's a row of null values for most cantons, but the federation value keeps going up. So two question @lazd do we trust the federal number or roll up the cantons in our scraper? For @paul-em : clearly my observation doesn't fit with yours that cantons look legit. At least not for 3/27 in that table. Can we compare notes, what were you looking at exactly when you said the "cantons look legit"? I think we should file an issue with the friendly Swiss and ask about the nulls, or maybe they are just late and fill the last row as they become available. But that would explain only the last day, not what @paul-em  reported and I see (several days too low in corona atlas data).

**Comment by piccolbo** [comment]
Their dashboard looks fine.
    https://dashcoch.herokuapp.com/
 I found other issues that could be related 
covid19-cases-switzerland#61 covid19-cases-switzerland#58

**Comment by qgolsteyn** [comment]
Closed as the count now seems correct (crosschecked with Worldometer)
