### ISSUE TITLE
Use YYYY-MM-DD everywhere

### ISSUE THREAD

**Issue by lazd** [covidatlas/coronadatascraper#48]
Currently, sometimes we have YYYY-M-D. Switch to YYYY-MM-DD for ease of sort and consistency.

**Comment by Wikunia** [comment]
Maybe you can give a place where this can be done? Do you have a post-processing step?

**Comment by lazd** [comment]
@Wikunia I believe @qgolsteyn is working on it. Thank you!

**Comment by ryanblock** [comment]
I can look at this (I assume with @HerbCaudill).

**Comment by ryanblock** [comment]
This is a fuzzily defined issue but we're on our way! See: https://github.com/covidatlas/coronadatascraper/commit/58ce17e3bd986bed82833fa1685a485684aa1d89
