### ISSUE TITLE
RUS Scraper breaks caching

### ISSUE THREAD

**Issue by lazd** [covidatlas/coronadatascraper#483]
The way the RUS scraper is implemented, fetching the CRSF token and throwing it on the URL, breaks caching. The URL changes every day and there is no way to know the old CRSF token.

This will need to be handled specially.

**Comment by lazd** [comment]
@freeatnet

**Comment by freeatnet** [comment]
@lazd what's the expected behavior here?

**Comment by lazd** [comment]
It should be possible to retrieve cache for RUS when running a timeseries:

```
yarn timeseries -d 2020-3-26 -e 2020-3-28 -l "RUS"
```

You see, when we run a timeseries, we re-scrape the cached page -- we don't use previously generated data, because it could contain bugs that we fixed in the scraper. We version our scrapers by date, so the old version sticks around to re-scrape old pages. This makes our dataset retroactively healing if we fix bugs.

So for RUS, the filename of the cache is the MD5 sum of the URL, and the URL includes a CRSF token that changes every time you fetch it. When we try to fetch cache, it's a different CRSF token, and we will never get a cache hit because the filename is wrong.

The fetch method will need to be updated to have an argument for `cacheAsURL` and include the URL without the CRSF token. Then, the methods for caching will need to respect that and retrieve the cache properly.

Finally, we will have to rename all of the historical cache files so they can be found.

**Comment by freeatnet** [comment]
@lazd Should the cache key (URL) change every day or is that handled somewhere else when re-scraping fetched pages?

**Comment by chunder** [comment]
We need to provide a way to cache the first `needle.get` call including the headers. Then re-running the scraper will pull the same csrf token from the cache.

**Comment by ryanblock** [comment]
I'll take a look at it; I'm mid-flight rewriting all our caching anyway, I have some ideas.

**Comment by jzohrab** [comment]
We can add a quick hack to get past this, with the current caching.

Current code in RU/index.js:

```
      const csrfRequestResponse = await needle('get', this.url, {}, { parse_response: true });
      const csrfCookies = csrfRequestResponse.cookies;
      const { csrfToken } = csrfRequestResponse.body;
      const { data } = await fetch.json(`${this.url}${csrfToken}`, undefined, { cookies: csrfCookies });
```

So, it's actually calling needle get itself, bypassing caching, and the random-ish token is appended to the URL.

We can change this to have it call a new method in fetch, which would result in it being deterministic:

```
      const csrfRequestResponse = await fetch.jsonAndCookies('get', this.url, {}, { parse_response: true });
      const csrfCookies = csrfRequestResponse.cookies;
      const { csrfToken } = csrfRequestResponse.body;
      const { data } = await fetch.json(`${this.url}${csrfToken}`, undefined, { cookies: csrfCookies });
```

With this change, the `fetch.jsonAndCookies` response (containing the csrfToken) would be cached with that fixed URL and thus be deterministic, and then url + csrfToken would be used as the base url which is hashed, to look up the final cached file.

We could also change `fetch.json` to have an extra param or option `returnCookies = false`, and if that extra param is true we return a hash: `{ body: ..., cookies ...}`, but I'm generally not in favor of changing returned data structure depending on arguments.  Still worth considering.

**Comment by jzohrab** [comment]
I'm going to add a PR for this, RUS having deterministic cache will help with integration tests.

**Comment by jzohrab** [comment]
Submitted PR, should be good to go.
