### ISSUE TITLE
unstable featureId

### ISSUE THREAD

**Issue by Akuukis** [covidatlas/coronadatascraper#485]
## Problem

A day ago, `featureId=338` was Italy, now it is some county in Russia. It's meaning is not defined.

Can we make IDs that don't change?

## Proposal

I don't know. Good enough for me to use random numbers as long they don't change.

## Ratione

I'm trying to pre-select some locations by ID but now I need to search/find the whole array by country/county/city and aggregation to find it.

**Comment by lazd** [comment]
Yes, they totally change. #243 was set to fix this with the help of @hyperknot's killer dataset, and it will be refactored and resent soon.

**Comment by qgolsteyn** [comment]
@lazd if this is fixed, feel free to close :)
