### ISSUE TITLE
Recoveries data problem for certain countries

### ISSUE THREAD

**Issue by kdn88** [covidatlas/coronadatascraper#488]
Looks like recovery numbers for CHN, KOR, JPN, DEU, SGP, TWN, GBR, IRN, maybe others not updating since 3/23.

**Comment by lazd** [comment]
Yes, that data came from JHU, and it seems like it's missing now. Not sure if they scrubbed it or what, but if they don't provide it, we won't have it.

**Comment by ketch** [comment]
They dropped it because they said they didn't have sufficiently reliable sources in most places.

**Comment by lazd** [comment]
Sounds like we don't either, then :( Closing this for now.
