### ISSUE TITLE
How to store bigger assets

### ISSUE THREAD

**Issue by hyperknot** [covidatlas/coronadatascraper#489]
What should we do with the bigger geographic packages, where should we store them? 

My country-levels full planet extracts have a 72 MB, 92 MB and a 169 MB version, uncompressed. Compressed, these are 11, 17 and 35 MBs respecitvely.

As more and more county level data arrives, I'm sure it'll be dozens of similarly sized packages at the end.

What should we do about them?

The easiest and most reliable way to handle these would be `yarn add github_url`. That checks out the whole repo into node_modules. In my case the 3 versions together.

The other way would be to download a release zip file from GitHub and extract it into a folder in runtime. For example I was working on downloading the medium version of country-levels and extracting it to /vendor/country-levels. It'd be gitignored then.

What path should we go? I think this very much depends on the lambda limitations, what do you say @ryanblock.

I think writing a function which checks and downloads a given url into a folder is quite easy. My idea was to store the version or url inside the folder, then we can check it trivially. For example:
```
if (readJSON('vendor/country-levels/__cache__.json') === url) return
```
or something similar.

Downloading and unzipping is also quite trivial. The point of this one would be that nothing would be included in the package, it'd be downloaded at runtime.

But again, I don't know the lambda specific parts of it, if we'd download everything on each function call for all scrapers might not be the best.

What are the limitations, how much can we include via package.json?

**Comment by camjc** [comment]
https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html
Bunch of limits for lambdas. The one I normally hit is the 50mb limit for the bundle of code to run on the lambda.

**Comment by hyperknot** [comment]
So I guess we are almost hitting that with the vendor folder already (28 MB)? I guess the direction then is to download zip files.

And is it possible to make them cache so that not every single run needs to download from GitHub?

**Comment by ryanblock** [comment]
Couple things:
- 50MB compressed, 250MB uncompressed
- We get a decent amount of disk if we need to temporarily persist anything (512MB)
- We will have 3GB of RAM if we want to read anything out of S3 into memory and operate on it there, which I'd strongly suggest

How soon do we need this functionality?

**Comment by hyperknot** [comment]
Right now I'd need to store those GeoJSON files somewhere. I definitely not want to store them in Git, as they are big and numerous. Including in package.json is also not a good idea, as it'd load the whole dataset. 

Basically that zipToFolder seems to be the best idea for me, at least it takes the smallest amount of space and doesn't pollute Git or package.json / node_modules.

**Comment by hyperknot** [comment]
> We get a decent amount of disk if we need to temporarily persist anything (512MB)

That sounds like the perfect solution in my opinion. Can we just unzip to `src/shared/vendor` now and change it to that temp folder later on?

**Comment by hyperknot** [comment]
Solved with yarn + tar.gz
