### ISSUE TITLE
Document output data format

### ISSUE THREAD

**Issue by lazd** [covidatlas/coronadatascraper#49]
We need a nice rundown of each field, what it is, what format its in, etc.

**Comment by DavidGeeraerts** [comment]
Yes that's me [jumping up and down]!

**Comment by DavidGeeraerts** [comment]
I'm looking into whether to make this an [ISO 19115:2013](https://en.wikipedia.org/wiki/Geospatial_metadatal) metadata record or use [metadata-json](https://project-open-data.cio.gov/v1.1/schema/). 
This is after all, Vector Spatial Data --> ISO 19115:2013

**Comment by lazd** [comment]
@hyperknot, thoughts on this?

**Comment by DavidGeeraerts** [comment]
I'm heavily swayed by data.gov Open Data Standards:
[Project Open Data Metadata Schema ](v1.1https://project-open-data.cio.gov/v1.1/schema/)

I'm somewhat spinning my wheels trying to find a good metadata-json editor. I'd rather not have to edit in raw. I'm looking...

**Comment by DavidGeeraerts** [comment]
This is exactly what I was looking for and need!
[mdEditor](https://go.mdeditor.org/#/dashboard)
Let's just say it's in the works after being stalled for the day. :-(

**Comment by DavidGeeraerts** [comment]
@lazd I've validated the workflow with [mdEditor](https://www.mdeditor.org/l):

1. Import the mdeditor metadata file
2. merge
3. edit
4. export
Think this workflow will work as a collaborative metadata project.

My question: should I upload the metadata.json file to the coronadatascraper repository?
I would think so, just want to check with you, since that's not exactly where the data is.
Should another repository be created just for the data?
(organization: CoronaVirusDataTeam)

**Comment by lazd** [comment]
@DavidGeeraerts how often will this metadata file change, what does it look like, and how should we provide it?

**Comment by DavidGeeraerts** [comment]
Getting an official metadata record for data.gov is going to take (me) a while. Went back to creating the metadata.md file so you can post on [your] website. I've started a Github organization called ["CoronaVirusDataTeam"](https://github.com/CoronaVirusDataTeam) --that was before the whole Coronavirus Response Data Team)-- and have a repo for docs. In there is the draft for [metadata.md](https://github.com/CoronaVirusDataTeam/docs/blob/master/metadata.md). This is a lot of work and I can only do it in chunks as time permits.

Can you provide me with (or update the [document](https://github.com/CoronaVirusDataTeam/docs)):

featureId:
   description: <needed>

aggregate:
   description: <needed>

I think I can do the rest of the CSV entries in the format I've laid out. Not sure about the JSON files, haven't looked closely at them.

**Comment by lazd** [comment]
* `featureId` - The ID of the feature this location references (index in `features.json`'s FeatureCOllection)
* `aggregate` - Whether this data source provides aggregate information (i.e. this county-level data was scraped from a state-level source)

**Comment by hyperknot** [comment]
I recommend keeping this very simple for now. 

I think the ideal timeseries would look like this:
{
  "id2:ITX": {
    "dates": {
      "2020-03-17": {
        "cases": 2,
        "deaths": 0,
        "recovered": 0
      },
      "2020-03-18": {
        "cases": 2,
        "deaths": 0,
        "recovered": 0
      }
    },
    "source_url": "https://github.com/CSSEGISandData/COVID-19",
    "population": 68414135
  }
}

Where each date string is a [ISO 8601 date](https://en.wikipedia.org/wiki/ISO_8601) and each id is a [Country Level ID](https://github.com/hyperknot/country-level-id).

Addressing counties, etc with an id is not a simple task, but I'll think about it. Maybe we can do something like id4:"US-CA-ABCDE" or something. I don't think there is a consistent system for county short codes.
