### ISSUE TITLE
Add links to cache on crosscheck reports

### ISSUE THREAD

**Issue by lazd** [covidatlas/coronadatascraper#492]
Right now, cross-check reports link to the latest data. We should instead link to the relevant cache.

**Comment by chunder** [comment]
I think we should link both to the "human" `this.source.url` landing page for the authoritative source as well as the "machine read" `this.url`. The `this.url` should link into the cache.

**Comment by lazd** [comment]
Yeah good call, right now we link to the human URL on the sources page, then data separate. We'll need UI to disclose additional links for this view, however.

**Comment by chunder** [comment]
Why not add a block of info right below the LOCATION header of each cross check entry.

```
MA, USA
---------
COVID Atlas Source: Massachusetts DPH (links to human page)
COVID Atlas Data URL: https://www.mass.gov/doc/covid-19-cases-in-massachusetts-as-of-march-29-2020/download
COVID Atlas Data cache: http://github.com/..../cache/xxxx.pdf

	cases	deaths	tested	recovered
The COVID Tracking Project	4257	44	35049	-
Massachusetts DPH	4260	4	-	-
The New York Times	3240	35	-	-
```

**Comment by jzohrab** [comment]
Closing, we're not updating this project.  Li reports warnings per data point if necessary (https://github.com/covidatlas/li/blob/master/docs/reports.md), and this is not relevant in the new project.  Closing! jz
