### ISSUE TITLE
Need help figuring out GeoJSON objects for Italian regions

### ISSUE THREAD

**Issue by lazd** [covidatlas/coronadatascraper#51]
I'm having trouble figuring out what GeoJSON features the regions listed here should be associated with: 
https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/dpc-covid19-ita-regioni.csv

GeoJSON regions: https://github.com/lazd/coronavirus-data-sources/blob/master/geojson/world-states-provinces.json

**Comment by lazd** [comment]
@enrichman can you help? I think it might be that the names in the data source refer to regions of provinces, and the GeoJSON has the provinces (too granular).

**Comment by enrichman** [comment]
@lazd that's correct, the file with provinces is this one:
https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-province/dpc-covid19-ita-province.csv

**Comment by enrichman** [comment]
One thing to notice is that there are two regions that are interpreted as two distinct one, but they're officially one.
*Bolzano* and *Trento* are actually two provinces of the *Trentino Alto-Adige* region (id 4).

**Comment by lazd** [comment]
Oh! Let's go by provinces then! Can you send a PR to update [the ITA scraper](https://github.com/lazd/coronadatascraper/blob/master/scrapers.js#L331-L364) to use the province data? I struggle with the language and geography.

**Comment by enrichman** [comment]
@lazd no problem. But I've seen that the data of the provinces show only the total cases, not the recovered nor deaths. 🙁 

Should we go only with the regions then?

**Comment by lazd** [comment]
@enrichman if we go with regions, we need GeoJSON for the regions (or we need to make our own feature collection that includes the provinces we have). Can you do that?

**Comment by enrichman** [comment]
@lazd I don't know much about GeoJSON but I can study a bit.
Could something like this work? https://github.com/stefanocudini/leaflet-geojson-selector/blob/master/examples/italy-regions.json

Btw I'm having some trouble on starting the project:
```
-> % yarn start
yarn run v1.22.4
$ NODE_OPTIONS='--insecure-http-parser' node cli.js
/Users/enrico/.nvm/versions/node/v11.14.0/bin/node: --insecure-http-parser is not allowed in NODE_OPTIONS
error Command failed with exit code 9.
```

**Comment by lazd** [comment]
@enrichman update to Node 13 and that error will go away

**Comment by lazd** [comment]
@enrichman that would work perfectly!

**Comment by LiveMethod** [comment]
Heads up the specific version is 13.4.0 – I had 13.2 and was still receiving this error, updating to 13.4 resolved it.

https://nodejs.org/api/cli.html#cli_insecure_http_parser

**Comment by lazd** [comment]
Thanks @LiveMethod, we need to add this in `engines`

**Comment by jzohrab** [comment]
@lazd I believe that the new system from @hyperknot resolves this.  Should this issue be closed?

**Comment by hyperknot** [comment]
I went through this manually yesterday and tagged each country to the right iso2 string, it's displaying nicely now. The data was wrongly mapped before, we mixed a 1m province with a 100k one so the color on the map was super black in one place.
