### ISSUE TITLE
Geo Metadata is wrong Brandenburg, Germany

### ISSUE THREAD

**Issue by roboter202** [covidatlas/coronadatascraper#514]
In location.json on object 628 (DE-BB) Brandenburg
coordinates, population and feature id wrongfully match those of object 629 (DE-BE) Berlin.

These are 2 different states though.

```
"country": "DEU",
    "state": "DE-BB",
    "coordinates": [
      13.421511874923084,
      52.513642483363896
    ],
    "population": 3740000,
    "rating": 0.43137254901960786,
    "tz": [
      "Europe/Berlin"
    ],
    "featureId": 335,
    "name": "DE-BB, DEU"
  },
```

should be 

```
"country": "DEU",
    "state": "DE-BB",
    "coordinates": [
      12.5316444,
      52.4125287
    ],
    "population": 2504000,
    "rating": 0.43137254901960786,
    "tz": [
      "Europe/Berlin"
    ],
    "featureId": ,
    "name": "DE-BB, DEU"
  },
```

**Comment by lazd** [comment]
@jgehrcke thoughts?

**Comment by jgehrcke** [comment]
looking

**Comment by jgehrcke** [comment]
Yes, so this was another copy/paste error during refactoring. Thanks for the report.

https://github.com/covidatlas/coronadatascraper/pull/516

For the record: population count from Wikipedia, coordinates from https://www.gps-latitude-longitude.com/gps-coordinates-of-brandenburg

> "featureId": 335,

We don't set this explicitly in the scraper file. @lazd thoughts?
