### ISSUE TITLE
Wrong Coordinates for Country ESP, PRT, FRA

### ISSUE THREAD

**Issue by roboter202** [covidatlas/coronadatascraper#528]
Same as #423 also for 

Spain, France and Portugal

![screenshot](https://user-images.githubusercontent.com/5413687/77956586-687de080-72d2-11ea-8f98-bad64db5ee17.png)

**Comment by ManuelAlvarezC** [comment]
Hi guys, Manuel from coronawhy here.
@JuanCalvoFerrandiz have made a visualization with all the coordinates on your data to help finding issues:
https://juancalvo.carto.com/builder/3ad41c17-bc07-4889-b047-5903300806c4/embed

**Comment by hyperknot** [comment]
@ManuelAlvarezC @JuanCalvoFerrandiz we are soon migrating to totally different coordinates, calculated in country-levels. https://github.com/hyperknot/country-levels

Please review if this issue is still present in a few days.

**Comment by qgolsteyn** [comment]
We have moved to this new system. Is the issue still present?

**Comment by hyperknot** [comment]
The coordinates are not yet taken from country-levels, that'll be in the next PR.

**Comment by jzohrab** [comment]
This doesn't appear to be a problem in the new site, https://covidatlas.com/portugal.  Thanks to @hyperknot for that, I assume.  Cheers all! z
