### ISSUE TITLE
Store timeseries sources in shared cache, but don't use it

### ISSUE THREAD

**Issue by lazd** [covidatlas/coronadatascraper#544]
Right now, for timeseries data, we store cache locally, but not in shared cache. If the timeseries we are consuming is not in github, we run the risk of it being changed or removed, and our timeseries will be missing their data completely.

Right now, we pass `false` for date to avoid storing it or fetching it from cache. We should find another way to indicate "hey, store this in cache, but don't use it."

Via @hyperknot

**Comment by jzohrab** [comment]
Closing.  In Li, we do store timeseries in the same folders as regular cache.
