### ISSUE TITLE
LA Parish in timeseries

### ISSUE THREAD

**Issue by caticoa3** [covidatlas/coronadatascraper#549]
Noticed a discrepancy in naming parishes in LA in the [timeseries.csv](https://coronadatascraper.com/#timeseries.csv)
"Parish" or "County" missing from these in the time-series. Although these are also found with the the "County" ending.  

orleans, la
jefferson, la
lafourche, la
st. bernard, la
st. charles, la
st. tammany, la
terrebonne, la
bossier, la
st. john the baptist, la
caddo, la
ascension, la
east baton rouge, la
washington, la

**Comment by hyperknot** [comment]
FIPS codes will these, as it used official census names.

**Comment by hyperknot** [comment]
So instead of "st. charles, la" we'll write "fips:22089" and it'll get everything from census, including the right name, which is "St. Charles Parish".
