### ISSUE TITLE
LA, USA: loc / pop failure

### ISSUE THREAD

**Issue by praging** [covidatlas/coronadatascraper#552]
location and population gets begin failing 2020-3-18 in backwards chronological order. seems as though "Parish" is not being added to the raw name. unsure as to how these older dates are being handled in the scraper.

**Comment by lazd** [comment]
Fixed by #551

**Comment by praging** [comment]
still open, even after https://github.com/covidatlas/coronadatascraper/pull/527

**Comment by praging** [comment]
latter commit fixes the issue
