### ISSUE TITLE
Add metadata file to cache directory for each cached file.

### ISSUE THREAD

**Issue by jzohrab** [covidatlas/coronadatascraper#556]
Currently each cache directory contains many files, but we don't know what the files are:

```
$ ls -1 coronadatascraper-cache/2020-3-28 | wc -l
155

$ ls -1 coronadatascraper-cache/2020-3-28 | head -n 3
018472faea35c3c9fa713caa8b9e21be.csv
01b0a96cf8f3121f1696e57ccdf11e4f.html
02a85b7c27387c85398b4e4bceee27fa.html
...
```

The filenames are hashes of the source URL.

It would be useful to have a human-readable index of these files, along with the date they were actually fetched from the source.

**Suggested implementation (drawing from various slack comments)**

Each file will have a corresponding `metada-{filename}.json` file, with the following data:

```
{
  cachefile: {filename-with-extension},
  url: {source url},
  cachedatetime: date time cached
}
```

This file will be created in the method `caching.saveFileToCache(url, type, date, fetchedBody)`.

It may be nice to have the calling scraper written in the metadata file as well, but that should be a separate PR/issue as it would require more changes to the code (i.e. each scraper would have to pass itself during the call to get content).

It may be useful to get all of the metadata files as an iterable data structure, so also provide a method in in `cache` that gets all of the metadata files:

```
caching.listAll()

returns array of information

[
  {
    cachefile: {filename-with-extension},
    url: {source url},
    cachedatetime: date time cached,

    // These are 'nice-to-have', because the callers
    // could derive this information from the above.
    fullpath: {cache-date-folder}/{cachefile}
  },
  ...
]
```

**Comment by lazd** [comment]
Note that @ryanblock has suggested separate folders for each source so we can begin caching multiple times per day.

**Comment by jzohrab** [comment]
Separate folders for each source -- we could do that.  We could also append the datetime to the hashed filename, it would work out to the same thing without much difference in the code.  However, that opens up some other questions, as currently the calls to get first check the cache, and then do a fetch if it's missing ... but would every scrape then create a new cached file?

I'll go ahead with this as-is and we can revisit on the multiple-caches-per-day in a separate issue/PR.

**Comment by lazd** [comment]
@jzohrab yes, that's a possibility. We should probably have a flag, `-c`/`--cache` that will use the latest cache (if it's from today), otherwise create a new cache file.

@ryanblock please weigh in

**Comment by jzohrab** [comment]
Can we put that discussion in a new issue?  I didn't see one, can create if needed.  That helps separate this issue from that, which I feel is something new.

**Comment by jzohrab** [comment]
I'm working on this now, fyi.  (Can't assign myself).

**Comment by ryanblock** [comment]
Hey there, sorry I didn't port my slack comments on this over here earlier, but this opens us to lots of state bugs and isn't presently necessary given the new caching format. Closing for now!
