### ISSUE TITLE
Washington State results are too low: missing "unassigned" county

### ISSUE THREAD

**Issue by emclain** [covidatlas/coronadatascraper#557]
I noticed that you recently changed the source of data for Washington State (USA/WA).  The new data source (arcgis.com) seems to report consistently lower counts than the official WA Department of Health website (https://www.doh.wa.gov/Emergencies/Coronavirus).

I think the difference may be that some of the Washington cases are not assigned to a county and so they are missing from your query.  It appears the arcgis query is specifically for county-level data (the URL contains "CountyCases").

For example, the Department of Health lists the case counts for 3/28 as 4,896, and also states "387 of 4,896 confirmed cases do not have an assigned county".  (You can see the difference for each day by clicking the "Unassigned" checkbox.)
![Screen Shot 2020-03-31 at 9 04 39 AM](https://user-images.githubusercontent.com/2669564/78048604-cd672400-732e-11ea-888b-ddd0734da060.png)

Coronadatascraper says the count for 3/28 was 4,310, which is 586 less than the Department of Health. It's not clear if the "unassigned" county is part of this difference, but it's worth taking a look.

Thanks for providing this service!

**Comment by lazd** [comment]
@aed3 can you look at this?

**Comment by emclain** [comment]
Looking more closely at the JSON you're getting from arcgis, I see this in the result for each county: 
... "CV_State_Cases":4896,"CV_State_Unassigned":387,"CV_State_Deaths":195 ...

I think if you're simply adding up all the results from all the counties, then you'll get the incorrect answer.  But it appears you can just pull the state cases directly from the CV_State_Cases field.

**Comment by aed3** [comment]
Yep, will fix that right now

**Comment by emclain** [comment]
Yup, I confirmed that the sum of all the counties currently is 4,509, which is exactly 387 different from the DOH total.

I'm not sure what accounts for the rest of the difference between coronadatascraper and DOH.

**Comment by aed3** [comment]
@lazd #558

**Comment by emclain** [comment]
Looks good, thanks!
