### ISSUE TITLE
Scrape and cross-check JHU county-level data

### ISSUE THREAD

**Issue by lazd** [covidatlas/coronadatascraper#559]
Just got added: https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv

**Comment by hyperknot** [comment]
Wow, this is amazing, we can basically map their values to `fips:${FIPS}` and be done with it!

**Comment by lazd** [comment]
@hyperknot see the branch I started putting together to scrape it, you can work off of that to merge with FIPS codes.

**Comment by hyperknot** [comment]
OK, let's merge FIPS codes first and then base the branch on the new master.
