### ISSUE TITLE
TN, USA State & County Data is all Zeros or Null

### ISSUE THREAD

**Issue by weslawson** [covidatlas/coronadatascraper#562]
TN USA Data is All Zeros or Null for 3/30/2020.

**Comment by lazd** [comment]
What file

**Comment by williamlidata** [comment]
> What file

Timeseries csv

**Comment by weslawson** [comment]
My apologies on not providing enough information.  It is affecting at least Timeseries.csv and data.csv

**Comment by weslawson** [comment]
I have rechecked the files and the missing data is now included in the data sets.

**Comment by lazd** [comment]
Thank you for following up, I'm glad it's fixed now!
