### ISSUE TITLE
FYI - Illinois IDPH COVID-19 Cook County Count

### ISSUE THREAD

**Issue by gschmeckpeper** [covidatlas/coronadatascraper#568]
FYI - the Illinois IDPH COVID-19 map and count on their website counts Chicago cases & deaths separate from the rest of Cook County cases & deaths.  Not sure if that is reflected in your figures on your map.  When do you update in the evening or the morning after?  Thanks!

**Comment by lazd** [comment]
Please re-open this issue if it's still looking wrong in the 2020-4-5 data. Thanks!
