### ISSUE TITLE
How should KOR quarantine location be handled

### ISSUE THREAD

**Issue by jacobmcgowan** [covidatlas/coronadatascraper#572]
In reference to PR #571, KOR lists quarantine as a separate location from the provinces and special cities so there is no location or population data to populate for that record. Should the population be set to the number of cases in quarantine or left undefined/0?

**Comment by jzohrab** [comment]
Hi @jacobmcgowan , thanks for the PR, which has been merged.  Do you think this issue is still a valid question, or should we close it?  Cheers and regards, jz

**Comment by jacobmcgowan** [comment]
Hello @jzohrab, I think it is still a valid question. In the PR I kept the population of quarantine to 0/not set. If that is how it should be handled then this question can be closed and there will be no change.

**Comment by jzohrab** [comment]
Thanks @jacobmcgowan: yes, if we don't have the data, then we should record it as `null` (not `0`).  If your code sets it to `null`, we're good.

**Comment by jacobmcgowan** [comment]
Thank you. I'll close this issue then.
