### ISSUE TITLE
Only glob actual locations

### ISSUE THREAD

**Issue by hyperknot** [covidatlas/coronadatascraper#581]
We need to fix the location globbing, right now it includes everything, like 

- src/shared/scrapers/AUS/_shared/get-data-with-tested-negative-applied.js
- src/shared/scrapers/AUS/_shared/get-key.js

How should we do it? 
1. Skip everything without a valid location.country? (I've fixed JHU to report country: "JHU" in my other PR, so that'd be ok)
2. Testing if `_shared` is part of the path in -1 or -2 level?

**Comment by qgolsteyn** [comment]
Filter using this regex `/scrapers(?![^/])(?!.*\/_).*\.js$/gi`, it will ignore filenames and directories that start with `_`

**Comment by qgolsteyn** [comment]
The change should be brought to this file: https://github.com/covidatlas/coronadatascraper/blob/master/src/events/crawler/get-sources/load-sources.js

**Comment by hyperknot** [comment]
This is fixed by @qgolsteyn in 4b632a52
