### ISSUE TITLE
Add Ukraine

### ISSUE THREAD

**Issue by hyperknot** [covidatlas/coronadatascraper#583]
They have official JSON API:
https://api-covid19.rnbo.gov.ua/data?to=2020-04-01

**Comment by shaperilio** [comment]
Added this to the [spreadsheet](https://docs.google.com/spreadsheets/d/1bx_9GMWkvwU4mdeyXWFdZMwxSt8J6mpaIa1IqKLAoiU/edit#gid=0) which @chunder can reference if we decide to write a "cache-only" scraper.

@hyperknot can you provide a root source page for this (e.g. the official equivalent to this that a human would go look at).

**Comment by shaperilio** [comment]
@ciscorucinski @lazd close this?

**Comment by shaperilio** [comment]
Actually, this source has data for places around the world, too. Should we scrape is as such separately?

**Comment by hyperknot** [comment]
Ukrain has been added yesterday, implemented using that API. The non-Ukraine regions in their world are just from JHU or something, so we better not use it.
