### ISSUE TITLE
Population for Emilia-Romagna missing as of 2020-04-01

### ISSUE THREAD

**Issue by shaperilio** [covidatlas/coronadatascraper#584]
It seems population disappeared for Emilia-Romagna. I refresh from https://coronadatascraper.com/timeseries-byLocation.json each day and today it’s not there, whereas yesterday it was

As @enrichman points out, it seems the province is in the wrong place:
![image](https://user-images.githubusercontent.com/26465923/78182733-9b7fbb80-741b-11ea-9864-385f3d214e4b.png)

**Comment by hyperknot** [comment]
@shaperilio @enrichman can you check if the provinces are correct on this list?
https://github.com/hyperknot/country-levels/blob/master/docs/iso2_list/IT.md

It's supposed to use up-to-date population data as well as OpenStreetMaps data.

**Comment by shaperilio** [comment]
This is fixed now.
