### ISSUE TITLE
Request: Please add European Union as entity

### ISSUE THREAD

**Issue by rcoenen** [covidatlas/coronadatascraper#593]
Please add the European Union as entity by aggregating the data for the following 27 Member States:
Austria, Belgium, Bulgaria, Croatia, Cyprus, Czechia, Denmark, Estonia, Finland, France, Germany, Greece, Hungary, Ireland, Italy, Latvia, Lithuania, Luxembourg, Malta, Netherlands, Poland, Portugal, Romania, Slovakia, Slovenia, Spain, Sweden.

The purpose of this is to provide context to the sometimes hard to interpret numbers. For example, it is often more meaningful to compare The Netherlands (population: 18 million) with New York State (population: 19 million) than The Netherlands with the entire USA. As it stands, there is no easy way to compare the USA with the European Union as a whole.

**Comment by qgolsteyn** [comment]
Closed as we are keeping the scope of this project to countries at the moment. It should not be too difficult when consuming our data to aggregate EU countries together.

**Comment by rcoenen** [comment]
You seem to be homing in on ultra specific local regions and localities and
not just countries. Why not provide some much needed global context by
default and add supra-natio all entities at the other end of the spectrum
in?

It's pretty pointless to see whatever San Marino or Malta is doing relative
to say China? To understand these mind boggling numbers we need context.
Adding the EU provides just that I believe.
