### ISSUE TITLE
data output: features.json future

### ISSUE THREAD

**Issue by hyperknot** [covidatlas/coronadatascraper#594]
So right now our features.json is on the limit of GitHub file size if we have unoptimised Brazil included.

This will definitely start to grow even more, as soon as we'll start including international states/provinces, and if some contributions like Brazil add counties.

Few solutions, in terms of complexity:
- minify JSON, right now it's a huge, space indented file. The super low hanging fruit, we can make the 75 MB file into 25 MB, just by minifying the JSON (where minifying means removing spaces). We should definitely do this!
- simplifying the geometries. This is more complicated but I'm doing this in the country-levels geometries, so if we move Brazil into there then they'd be automatically simplified
- split the file to 3-4 different one. For example one for fips, one for iso1, one for iso2 one for the rest.
- serve everything from AWS, with transparent gzipping.

**Comment by chunder** [comment]
I would suggest splitting it. That will keep it readable and easy to work with.

**Comment by hyperknot** [comment]
I don't think anyone is reading a file with 3.9 **million** lines as of today.

**Comment by chunder** [comment]
Of course not. But they may be grepping it.

**Comment by chunder** [comment]
And people have been editing the names in that file. Which would be quite painful if it is minified.

**Comment by chunder** [comment]
Or is this just the OUTPUT of the pipeline? In that case minify away!

**Comment by ryanblock** [comment]
Let’s minimize bug vectors and build processes, so I’d suggest holding off on minifying for the moment. Splitting is a good call tho.

We should only sideload and ‘require’ these files dynamically and only when necessary; they can load out of S3 to our functions. Thoughts on how? Just key on country?

**Comment by hyperknot** [comment]
Yes, I'm talking about the output.

**Comment by hyperknot** [comment]
@ryanblock this is the output, pretty much not "require"-d anywhere, only the website reads it.

Adding a JSON.minify() or something at saving features.json is quite a trivial change, much simpler than splitting it in 4.

**Comment by ryanblock** [comment]
... on second thought, these files aren’t changing much right? If not and we only have to minify very infrequently, that’s an easy win.

**Comment by hyperknot** [comment]
No, they change in every run. But minification is literally not including the spaces, we are talking about a line line change in the source code.

The bigger issue is with 
```
File timeseries-tidy.csv is 113.44 MB; this exceeds GitHub's file size limit of 100.00 MB 
```

This needs to be moved to AWS already, there is no option there.

**Comment by ryanblock** [comment]
Got it. In that case we may already be thinking about this wrong way. No client should be downloading a >1MB JSON obj...

**Comment by hyperknot** [comment]
Ok, for maps, we have to make a difference between what do we serve for other websites, for that a 100 MB JSON is perfect.

Now what to put on our own map, it needs to be cleaned, optimised and converted to TopoJSON and them compressed with Gzip. Even that way, they'd be about a few MB, but that's the case with maps, it works like this.

**Comment by hyperknot** [comment]
This makes size from 75 MB to 25 MB:
https://github.com/covidatlas/coronadatascraper/pull/595

**Comment by lazd** [comment]
@hyperknot This is super good stuff. I will defer to you on what the right solution is. I merged the PR that removes the prettyprint from the JSON already, that's a great start. We might want to offer a US-only map with the county-level data, a world map with state-level and country-level data, and perhaps switch between them with zoom level.

**Comment by hyperknot** [comment]
JSON is now output with space: 0, and we implemented all the US counties using fips codes. Today's feature.json is now 14.8 MB only, 3.7 MB is the gzipped response.

This makes me confident we don't need to take drastic measures. In the future I recommend splitting it up to fips / iso1 / iso2 / br_muni files, but basically it'll be managable like that.

For the website, only internally, we can convert it to TopoJSON which is deduplicating shared borders, but again, this is not needed now, 3.7 MB for a full world is definitely a good size.

**Comment by HerbCaudill** [comment]
I'd include a topojson version in the public output as well. The advantage over geojson isn't just file size; you also don't have to deal with adjoining shapes simplifying differently and creating gaps and overlaps.

**Comment by hyperknot** [comment]
Oh, that's not because GeoJSON, it's because they are from different datasets. TopoJSON can only help if the borders were the same in the first place. Still, we can totally output to TopoJSON in dist.

Where is this taken from?

**Comment by jzohrab** [comment]
In Li we're no longer committing reports to GitHub, we're just posting them to S3.  We're no longer doing this, so I'll close it ... if anyone here disagrees, please open a new issue in Li.  Cheers! z
