### ISSUE TITLE
Deploy compiled data files to public location

### ISSUE THREAD

**Issue by jzohrab** [covidatlas/coronadatascraper#597]
A few people have suggested places where the data reports could be stored for later use.  This is a master issue compiling each of those locations.

**Possibilities**

* Manual deployment to GitHub releases (issue #3)
* Manual deployment to npm (issue #4)
* storing the data in GitHub (possible, but not something we've considered as we don't want people sending pull requests against raw data.) (issue #456)
* public S3 bucket

**Comment by judepayne** [comment]
Hi, a public S3 bucket would also be great - easy to get at the data for non-technical users.

**Comment by jzohrab** [comment]
In Li, we're storing the generated reports in a public S3 bucket.  We need to make them available via a CDN / human friendly  URL, but that's where they are and will be.  Closing, as we're not updating this project.  Cheers! z
