### ISSUE TITLE
Missing county data in snapshot  for VT and NH on 04/02

### ISSUE THREAD

**Issue by caticoa3** [covidatlas/coronadatascraper#602]
https://coronadatascraper.com/#data.csv
Expected values for counties in VT and NH

https://coronadatascraper.com/#data.cs
<img width="903" alt="image" src="https://user-images.githubusercontent.com/5348361/78303410-72315f00-74f1-11ea-84b4-6ce614729ef6.png">

I see the data in the map:
<img width="286" alt="image" src="https://user-images.githubusercontent.com/5348361/78303506-a016a380-74f1-11ea-8c60-5e797da97d8e.png">

Is the JSON file more reliable for data?

**Comment by hyperknot** [comment]
Can you recheck this tomorrow? It might have been already fixed with the fips: migration with @lazd.

**Comment by caticoa3** [comment]
checking now but it appears there is a bigger issue, I don't see any data in time series or snapshot for the US:
which is coincidentally issue 666, https://github.com/covidatlas/coronadatascraper/issues/666

**Comment by lazd** [comment]
@caticoa3 please check again, I think we got it this time! Close this issue if so please!

**Comment by caticoa3** [comment]
@lazd sure thing, the data are there now. Although I was a bit thrown off at first because I searched with state abbreviation and now the full state is listed. Closing this. Thanks.
