### ISSUE TITLE
scraper.json schema is not erroring for scrapers

### ISSUE THREAD

**Issue by ryanblock** [covidatlas/coronadatascraper#604]
scraper.json schema should error, probably even throw, for scrapers.

* How will this make life better?

It should help ensure some degree of quality/security within the scraper realm.

* How big is this change (small/med/large/really large)?

Minor

* How complicated is it? [Complexity]

Minor

**Comment by jzohrab** [comment]
@ryanblock , I had started this code before during the other work for integration tests, so I finished it and opened PR #644.

One question, which I'm not sure how to address: scrapers can have different versions, keyed by date.  This check, the main part of which I stole from another file, only checks the `default` object.  That was the check in the existing code.

We could conceivably change this to get all of the versions for any one scraper, and then verify the schema is correct for each version.  Does that sound like the right thing to do?  My main concern with that is that the schema may evolve as well over time, and perhaps it's not realistic to expect all historical scrapers to keep up.
