### ISSUE TITLE
Add package.json to country-levels

### ISSUE THREAD

**Issue by ryanblock** [covidatlas/coronadatascraper#605]
@hyperknot:

```npm i https://github.com/hyperknot/country-levels/releases/download/v1.1.1/export_q7.tgz
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: https://github.com/hyperknot/country-levels/releases/download/v1.1.1/export_q7.tgz.
npm ERR! package.json npm can't find a package.json file in your current directory.
```
For the time being we'll be using npm inside the functions; in order for me to add this package to the functions npm needs a package.json file.

Thanks!

**Comment by hyperknot** [comment]
OK, I add one for the zips. Isn't it risky to use yarn.lock and npm?

**Comment by hyperknot** [comment]
New release: https://github.com/hyperknot/country-levels/releases/download/v1.1.2/export_q7.tgz

**Comment by ryanblock** [comment]
Fixed, thanks!

(npm and yarn are being used in diff parts of the codebase; I'll continue to advocate for the boring, built-in, officially vendored option that doesn't leave us locked on a past version, shortcomings and all, but that's a sep conversation!)
