### ISSUE TITLE
Deaths cases Australia

### ISSUE THREAD

**Issue by subzero79** [covidatlas/coronadatascraper#612]
* https://ww2.health.wa.gov.au/Articles/A_E/Coronavirus/COVID19-statistics
* **File: ** [the data file with the discrepancy]
* **Issue: ** Australia scrapers are not reporting deaths. Most of the health by state websites are not reporting the deaths cases. 

can check here 

https://www.health.qld.gov.au/news-events/doh-media-releases/releases/queensland-novel-coronavirus-covid-19-update19

also here 

https://www.dhhs.vic.gov.au/coronavirus-update-victoria-3-april-2020

But the state of Western Australia is reporting a table for whole wide Australia including the deaths cases. 

https://ww2.health.wa.gov.au/Articles/A_E/Coronavirus/COVID19-statistics

![image](https://user-images.githubusercontent.com/7058119/78316546-4a023880-75a3-11ea-9fca-6fae7e3db36c.png)

**Additional context**

Maybe is it possible to use this table to feed in the deaths stats for the remaining states

**Comment by subzero79** [comment]
Been trying to run the scrapers individually see i can add to the missing deaths cases to the states scrapers by using the WA table

I've tried this

yarn start --location "QLD, AUS"

or this
yarn start --location "Queensland, AUS"

**Comment by subzero79** [comment]
Have to use 

```
yarn start --location 'iso2:AU-WA, AUS'
```

**Comment by subzero79** [comment]
@camjc Any possibility of feeding the WA table of deaths into each state?

**Comment by camjc** [comment]
Sure it’s possible. Not sure if it’s considered a primary source at that point though.
Doesn’t seem like we have merging logic for missing fields, just picking one primary for each region.

**Comment by subzero79** [comment]
I don't get why they are not publishing the deaths records on qld neither on the top health site

**Comment by camjc** [comment]
Could be a good feature request to use fallbacks for fields not included in the best source?

**Comment by lazd** [comment]
@camjc can we close this one?

**Comment by camjc** [comment]
Yeah I scraped this the other day. Close away :)

**Comment by camjc** [comment]
Btw WA seems to be always behind at least a day vs the feds.
