### ISSUE TITLE
Data discrepancies - Date, Country and States

### ISSUE THREAD

**Issue by ersaurabhex** [covidatlas/coronadatascraper#615]
Below data is incorrect for given date, country and state.

state | country | population | lat | long | url | aggregate | tz | date | type | value
DC | USA | 705749 | 38.89945 | -77.0145 | https://coronavirus.dc.gov/page/coronavirus-data | state | America/New_York | ######## | cases | 252

Instead of 252, It should be 31
-----------------------------

Few more 
country|state|date|cases_of_given_date|cases_of_given_date-1
CHE|CHE|2020-03-27 00:00:00|1,751|9,369
USA|KS|2020-03-27 00:00:00|32|171
CHE|CHE|2020-03-26 00:00:00|9,369|11,081
GUY|GUY|2020-03-24 00:00:00|5|7
IND|Rajasthan|2020-03-24 00:00:00|30|31
USA|HI|2020-03-24 00:00:00|70|72
XKX|XKX|2020-03-24 00:00:00|0|2
FRA|French Guiana|2020-03-23 00:00:00|0|18
FRA|Reunion|2020-03-23 00:00:00|0|47
TLS|TLS|2020-03-23 00:00:00|0|1
CAN|Manitoba|2020-03-21 00:00:00|11|17
AUS|Tasmania|2020-03-20 00:00:00|8|10
CHE|LU|2020-03-18 00:00:00|48|50
CHN|Guizhou|2020-03-18 00:00:00|146|147
MNE|MNE|2020-03-18 00:00:00|1|2
USA|NV|2020-03-18 00:00:00|55|56
AUS|Northern Territory|2020-03-17 00:00:00|0|1
USA|DC|2020-03-17 00:00:00|31|252
AZE|AZE|2020-03-16 00:00:00|15|23
JPN|JPN|2020-03-16 00:00:00|825|839
LBN|LBN|2020-03-16 00:00:00|99|110
USA|PA|2020-03-16 00:00:00|0|63
USA|TX|2020-03-16 00:00:00|55|56
CHE|CHE|2020-03-15 00:00:00|1,184|1,607
DEU|DE-SL|2020-03-15 00:00:00|32|40
USA|UT|2020-03-15 00:00:00|7|19
ESP|Baleares|2020-03-14 00:00:00|28|30
USA|TN|2020-03-14 00:00:00|22|26
BHR|BHR|2020-03-13 00:00:00|189|195
USA|IN|2020-03-13 00:00:00|12|13
USA|NY|2020-03-13 00:00:00|325|328
ESP|Galicia|2020-03-12 00:00:00|35|39
GBR|GBR|2020-03-12 00:00:00|456|459
GUF|GUF|2020-03-12 00:00:00|0|5
REU|REU|2020-03-12 00:00:00|0|1
USA|USA|2020-03-12 00:00:00|1,596|2,316
CHE|LU|2020-03-09 00:00:00|5|6
FRA|Saint Barthelemy|2020-03-09 00:00:00|1|3
ITA|Piemonte|2020-03-09 00:00:00|350|360
ESP|Canarias|2020-03-08 00:00:00|17|18
FRA|Bourgogne-Franche-ComtÃ©|2020-03-08 00:00:00|112|129
AUS|Northern Territory|2020-03-06 00:00:00|0|1
ESP|AndalucÃ­a|2020-03-05 00:00:00|12|13
FRA|Guadeloupe|2020-03-04 00:00:00|0|3
FRA|Bourgogne-Franche-ComtÃ©|2020-03-02 00:00:00|8|10
ITA|Liguria|2020-03-02 00:00:00|22|25
ITA|Sicilia|2020-03-02 00:00:00|7|9
ESP|AragÃ³n|2020-03-01 00:00:00|0|1
ITA|Liguria|2020-03-01 00:00:00|25|42
ITA|Piemonte|2020-02-27 00:00:00|2|3
JPN|JPN|2020-02-07 00:00:00|25|45
AUS|Queensland|2020-02-02 00:00:00|2|3
AUS|Queensland|2020-01-31 00:00:00|2|3
JPN|JPN|2020-01-23 00:00:00|1|2

Regards,
Saurabh

**Comment by lazd** [comment]
Unfortunately, we can't correct data that comes directly from sources. Please submit a PR or file a more focused issue if you find a bug with a scraper.
