### ISSUE TITLE
Map: Higher-Order bleed-through

### ISSUE THREAD

**Issue by praging** [covidatlas/coronadatascraper#616]
There are certain places (two shown below) where the higher-order entity bleeds through the empty spaces of the lower order. In the case of Nevada, it is state data bleeding through the county gaps; in the case of Russia, it is country data bleeding through federal subject gaps.

![Screen Shot 2020-04-03 at 00 03 02](https://user-images.githubusercontent.com/26956401/78333711-30c7a080-753f-11ea-8cfa-288f5c963270.png)

![Screen Shot 2020-04-03 at 00 02 48](https://user-images.githubusercontent.com/26956401/78333716-34f3be00-753f-11ea-81af-f29616992cfd.png)

**Comment by hyperknot** [comment]
Splitting the files to iso1 / iso2 / fips features.geojson is the solution to solve this. We'd be able to turn on and off individual layers on the map.

**Comment by hyperknot** [comment]
Actually https://github.com/covidatlas/coronadatascraper/pull/432 is a cleaner solution. For example in the US, we probably want state level data by default, not country one, so it's better not to use files for that.

Still, it'll be quite important to not load br_muni for example by default.

**Comment by lazd** [comment]
This is absolutely intended. Unless we have COMPLETE data for a given region, we render the higher order and the lower order data. This is determined by the `aggregate` property. For Russia, it's possible that property is set incorrectly, for Nevada, it's functioning as designed.

**Comment by praging** [comment]
Could you clarify what you mean by complete data? Does this include (unassigned) counties?

**Comment by praging** [comment]
I guess my point is that I'm not sure that this is working as expected (considering that Utah was incomplete but not showing aggregate) and that I'm not sure that I agree with the expectation -- that we should display higher-order on a lower-order map. The problem is it juxtaposes data we don't have a location for onto portions of the state that have not confirmed cases, essentially showing cases where there aren't any confirmed. I would recommend removing this feature during the #432 merge, so that the county toggle shows only confirmed counties / regions and the state map shows the aggregate.

**Comment by lazd** [comment]
This is definitely worth exploring more and elaborating on. Will keep this in mind as we re-work the map.

**Comment by jzohrab** [comment]
Closing, I believe this issue is stale / doesn't apply to Li / covidatlas.com.
