### ISSUE TITLE
name format issue for Shasta County, CA on 04/02

### ISSUE THREAD

**Issue by tautme** [covidatlas/coronadatascraper#617]
File:  data.csv
Issue:
* state listed as "CA" 
* country listed as "USA"
* stateId and countryId iso missing

![image](https://user-images.githubusercontent.com/15580867/78334651-c10ee100-7551-11ea-878a-9c666cace68f.png)

**Comment by hyperknot** [comment]
Good catch! This was the test county for fips conversion and it was using fips: code.

**Comment by hyperknot** [comment]
@lazd it's fixed in PR.
