### ISSUE TITLE
Scraper for [LOCATION_HERE]

### ISSUE THREAD

**Issue by leon-wong1949** [covidatlas/coronadatascraper#623]
**The source**

Please ensure the source meets our [source guidelines](../../tree/master/docs/sources.md#criteria-for-sources).  Thank you!

* **Full location name: ** [Name here, e.g., "County x,WuHan , CN")]
* **Source URL: ** [URL]

**Comment by lazd** [comment]
Looks like you didn't use the issue template correctly.
