### ISSUE TITLE
SHORT_ISSUE_NAME for LOCATION on MM/DD

### ISSUE THREAD

**Issue by kabeerAhmed09** [covidatlas/coronadatascraper#625]
* **Source: ** [source or url, if applicable]
* **File: ** [the data file with the discrepancy]
* **Issue: ** [bad data or values currently in the file, and what was expected]

```
[If you can, please include a snippet of the file here, or a screenshot, so that the devs can search and find it quickly in the file.]
```

**Additional context**

[Add any other context here.]

**Comment by lazd** [comment]
Looks like you didn't use the issue template correctly.
