### ISSUE TITLE
Maine data way off

### ISSUE THREAD

**Issue by kb1ujs** [covidatlas/coronadatascraper#631]
Data for Maine is way off on number of deaths.  Looks like maybe hospitalizations are being counted instead as deaths.

**Comment by kb1ujs** [comment]
I looked at the data closer and that's exactly what's happening.  The death data is not in the file and the column marked deaths is actually hospitalizations.

**Comment by kb1ujs** [comment]
Table format on Maine CDC website changed on April 2, breaking the scraper.  Will try to submit a pull request to fix.

**Comment by lazd** [comment]
Thanks @kb1ujs, please do send along a PR!

**Comment by jzohrab** [comment]
Hi @kb1ujs , thanks for the PR.  This was recently merged, so if this problem is resolved in the next release or so please close this issue.  Thanks again! jz

**Comment by praging** [comment]
three dates have not yet been fixed: 03-30, 03-31, and 04-01

**Comment by kb1ujs** [comment]
Looks like the format change occurred a few days earlier than I thought.  I'll fix it and submit a new pull request.

**Comment by lazd** [comment]
Closed by #718
