### ISSUE TITLE
US States and Counties missing on 04/03

### ISSUE THREAD

**Issue by akkana** [covidatlas/coronadatascraper#634]
* **Source: ** [source or url, if applicable]
https://coronadatascraper.com/timeseries-byLocation.json
* **File: ** [the data file with the discrepancy]
timeseries-byLocation.json
* **Issue: ** [bad data or values currently in the file, and what was expected]
USA states and counties have disappeared since yesterday.

Yesterday, timeseries-byLocation.json was 30,535,773 bytes and included locations such as "NM, USA" and "Bernalillo County, NM, USA". Today, it's 8,239,261 bytes, and doesn't include any locations that include "USA", either states or counties. Did the scrapers misfire last night? Or should I be fetching a different data file?

By the way, the coronadatascraper project is absolutely fantastic -- thanks!

**Comment by jzohrab** [comment]
We've recently changed some of the code that deals with locations -- this change will help enormously in ensuring we're consistent everywhere.  We have some fixes in and will be redeploying tonight.

Thanks very much for notifying us, I'll follow up later.  Cheers! z

**Comment by lazd** [comment]
@akkana two things:

1. We backed out #476, hence the file size decrease
2. Last night, we pushed an update that includes FIPS and ISO codes for everything as `countyId`/`stateId`/`countryId`. The corresponding `county`, `state`, `country` fields became human readable names. This is not messaged correctly and we didn't have a great way to inform people of the change.

**Comment by akkana** [comment]
Oh! Sure enough, you're right, the counties are there, just with new names. And a smaller file size sounds excellent. Thank you! I'm going to close this.
