### ISSUE TITLE
datetime.now.utc() should have a Z at the end

### ISSUE THREAD

**Issue by lazd** [covidatlas/coronadatascraper#637]
**Description**
/title

**To Reproduce**
1. Run `datetime.now.utc()`
2. Observe Z-lessness

**Expected behavior**

`datetime.now.utc()` be has the Z

**Screenshots**
![image](https://user-images.githubusercontent.com/201344/78409812-8348a180-75bf-11ea-9830-c7f261901a7c.png)

**Additional context**
It's true

**Comment by hyperknot** [comment]
Right, I've just checked Wikipedia and it says:
```
If no UTC relation information is given with a time representation, the time is assumed to be in local time. 
```

So we either need to add Z or `+00:00` to specify UTC.

**Comment by jzohrab** [comment]
Added a fix to close one issue.
