### ISSUE TITLE
population data not counted correcly when coming from scraper

### ISSUE THREAD

**Issue by hyperknot** [covidatlas/coronadatascraper#639]
Repro: `yarn start -c DEU` says and reports: 

```
Found population data for 0 out of 16 locations
```

It's because the location is coming from the scraper, and we have a continue early on in find-locations.

**Comment by hyperknot** [comment]
@lazd

**Comment by lazd** [comment]
I believe we fixed this, I'll go ahead and close it. If it pops up again, please re-open!
