### ISSUE TITLE
city, county, state, country need to be human readable, ISO should only be in cityId, countyId, stateId, countryId

### ISSUE THREAD

**Issue by lazd** [covidatlas/coronadatascraper#647]
## Description

Right now, we mix in ISO-3166 Alpha 3 into the `country` field, but it should be the full, human-readable country name instead.

This was a problem with 2020-4-2 data -- people were looking for USA, but it's United States now.

We need to be consistent.

**Comment by weslawson** [comment]
I'm seeing this in the timeseries.csv file, I initially though there was missing data.

**Comment by lazd** [comment]
Fixed by #683 in 2020-4-5 data.
