### ISSUE TITLE
Migrate to JHU ISO and FIPS mapping CSV

### ISSUE THREAD

**Issue by hyperknot** [covidatlas/coronadatascraper#648]
JHU uploaded a CSV file for ISO and FIPS mapping. This is huge! It means we can remove all the "smart" code from JHU scraper and get the perfect iso and fips codes for their strings! 

https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv

No more point-in-polygon finding, finally!

@lazd

**Comment by lazd** [comment]
We can close this as we've reffing this file for JHU data now.
