### ISSUE TITLE
2020-04-04 DE-RP population field is not an integer

### ISSUE THREAD

**Issue by mightybyte** [covidatlas/coronadatascraper#657]
## Location, date, and short issue description

Population field is not an integer

## File

https://coronadatascraper.com/timeseries.csv

## Issue details

Has the value 4070000.0000000005 in the population field

## Snippet/screenshot
```
"DE-RP, DEU",state,,,DE-RP,DEU,4070000.0000000005,49.90656550694859,7.295141232392936,https://raw.githubusercontent.com/jgehrcke/covid-19-germany-gae/master/data.csv,,Europe/Berlin,25,,,,,,2020-03-11
```

**Comment by hyperknot** [comment]
will be fixed by iso codes

**Comment by lazd** [comment]
@hyperknot still seems to be an issue, seeing `4070000.0000000005` in the latest data.

**Comment by lazd** [comment]
Fixed, will be corrected in tomorrow's data.
