### ISSUE TITLE
Run scraper and report changed data on pull request

### ISSUE THREAD

**Issue by lazd** [covidatlas/coronadatascraper#66]

**Comment by lazd** [comment]
@qgolsteyn sounds like we're close to being able to do this with the CI setup we have for daily pushes. Thoughts?

**Comment by qgolsteyn** [comment]
Yes, very close. Diffing might be a bit harder. Looking at ways to trigger for only the scrapper that was changed/added.

**Comment by jzohrab** [comment]
Opened as a separate issue in li, https://github.com/covidatlas/li/issues/196.  Closing this as a duplicate.  Cheers! z
