### ISSUE TITLE
JHU-USA deaths > cases

### ISSUE THREAD

**Issue by hyperknot** [covidatlas/coronadatascraper#665]
Does anyone know anything about JHU-USA deaths > cases for the unassigned counties? Can someone ask them about it?

AK cases: 0 deaths: 1
AZ cases: 0 deaths: 6
CA cases: 0 deaths: 1
FL cases: 0 deaths: 2
MD cases: 0 deaths: 1
MN cases: 0 deaths: 4
NY cases: 0 deaths: 159
VA cases: 0 deaths: 5

**Comment by lazd** [comment]
Yes, I believe they've tracked deaths, but don't know where the deaths occurred. It's ok that there are more deaths than cases in unassigned regions.
