### ISSUE TITLE
data.csv and timeseries.csv missing entries with 0 cases

### ISSUE THREAD

**Issue by lazd** [covidatlas/coronadatascraper#666]
## Description

These entires should definitely appear in `data.csv`, not so sure about `timeseries.csv`

## Steps to reproduce
1. `yarn start`
2. Compare `data.csv` with `data.json`
3. See places with `cases: 0` missing from CSV

## Expected behavior

`cases: 0` places appear in CSV

**Comment by andys1376** [comment]
Has this been fixed? It looks like today both the CSV and json have 3931 entries, and I can see some entries in the CSV with 0 cases.

**Comment by jzohrab** [comment]
Fixed.
