### ISSUE TITLE
Population data missing in Wikidata

### ISSUE THREAD

**Issue by hyperknot** [covidatlas/coronadatascraper#668]
We are now using Wikidata to get the population based on ISO codes. There are 5 provinces in China which are missing population data. 

You can see the current list as well as the Wikidata links where on the following page:
https://github.com/hyperknot/country-levels/blob/master/docs/iso2_list/CN.md

Can someone enter those missing populations into Wikidata? Good first issue.

**Comment by praging** [comment]
Put in a permissions request for four out of the five. The last of the five (Yunnan) actually has population data on its page, so that seems like a different issue.

**Comment by praging** [comment]
Populations now present in all but Guizhou.

**Comment by hyperknot** [comment]
@praging thanks! How did you "Put in a permissions request"?

Can you help in Aragon, Spain?
https://www.wikidata.org/wiki/Q4040

We should copy the population from Wikipedia but it's locked. How can I request editing of locked pages?

**Comment by praging** [comment]
https://www.wikidata.org/wiki/Wikidata:Requests_for_permissions/Other_rights

They're obnoxious about it though. They denied perms with vitriol and did some of the edits themselves.

I'll put in the two remaining as edit requests in a bit, but it may just be easier/faster to find someone who is already autoconfirmed on Wikidata.

**Comment by praging** [comment]
They have an edit request category [here](https://www.wikidata.org/wiki/Category:Wikidata_protected_edit_requests).

**Comment by hyperknot** [comment]
Thanks for the explanation and for the effort! 

> it may just be easier/faster to find someone who is already autoconfirmed on Wikidata.

I have no idea how could I find such person. In the meanwhile, I've added a fixes/populations.json to country-levels, so we can at least add fixes while waiting for Wikidata.

https://github.com/hyperknot/country-levels/blob/master/fixes/population.json

**Comment by praging** [comment]
Looks like you got it sorted! You have my sincere congratulations. ;D

**Comment by hyperknot** [comment]
Yes, this is now fixed!
