### ISSUE TITLE
US State - Data Inaccuracies 

### ISSUE THREAD

**Issue by PeterBloomingdale** [covidatlas/coronadatascraper#673]
First of all, thank you for putting this nice data repository together. Especially since John Hopkins repository stopped reporting state level data in a nice .csv table.

There are select cases where US state data is in accurate within the last few days. This is in part due to the county level data not being reported accurately. For example, in some counties in Alaska, incidence is accumulating over time, but is reported as N/A in the absence of data. Might be worthwhile to report the to-date maximum reported value for each county in the absence of data, instead of N/A

Also, for New Jersey. The cumulative incidence increases and then decreases. For example:

4/2/2020 = 20724 cases
4/3/2020 = 25090 cases
4/4/2020 = 20724 cases
4/5/2020 = 20724 cases

**Comment by williamlidata** [comment]
South Dakota and Kansas are also showing this same increase and drop in the timeseries csv.

**Comment by lazd** [comment]
Please take a look at the latest data from this evening and note any inconsistencies you find for NJ, AK, SD, and KS. Make sure the same sources are being used for each day the anomaly occurs, and if so, please file a separate issue for each state with your analysis. We can then debug the scrapers and refer to the cache to see if the issue is due to the datasource or an error in the scraper. Thanks!

**Comment by praging** [comment]
AK at #697

**Comment by praging** [comment]
KS at #698

**Comment by praging** [comment]
SD at #699

**Comment by praging** [comment]
NJ at #700

**Comment by praging** [comment]
closed

**Comment by praging** [comment]
@lazd @camjc @ryanblock 

Looks like every territory (besides Hawaii and Wisconsin) began failing 04-03 and rebounded 04-06 (besides AK, which is still broken).

[timeseries-jhu-us_states.xlsx](https://github.com/covidatlas/coronadatascraper/files/4441790/timeseries-jhu-us_states.xlsx)

**Comment by lazd** [comment]
@praging thanks for the insight, we'll get to the bottom of this and heal the timeseries.

**Comment by praging** [comment]
closed

**Comment by praging** [comment]
this is mostly closed now. the only state-wide issue I see as of today is null timezone fields from 03-28 to 04-07 (inclusive).

**Comment by tautme** [comment]
Noticed there are some differences between `timeseries-tidy.csv` and `timeseries.csv`

<img width="594" alt="image" src="https://user-images.githubusercontent.com/15580867/79089921-9836da80-7d0d-11ea-80ad-cca99bada292.png">

<img width="594" alt="image" src="https://user-images.githubusercontent.com/15580867/79089911-90773600-7d0d-11ea-84f8-a4af958f3d90.png">

**Comment by jzohrab** [comment]
We no longer create timeseries-tidy.  :-)

NJ looks ok to me on https://covidatlas.com/new-jersey-us, with numbers only increasing.

I'm going to assume that this issue is closed.  If you see any issues with the Li reports (https://covidatlas.com/data) please let us know.  Cheers, jz
