### ISSUE TITLE
USA country name changed to iso1:US, similar for states

### ISSUE THREAD

**Issue by caticoa3** [covidatlas/coronadatascraper#675]
In timeseries data and snapshot, the country name for USA is has changed to iso1:US and states also have a changed from state abbreviation to iso1:US-WA vs WA, for example. Could this be changed back to USA and just state abbreviation, for consistency?

<img width="263" alt="image" src="https://user-images.githubusercontent.com/5348361/78508830-bb2a2300-773e-11ea-9209-711b877a9b5a.png">

**Comment by caticoa3** [comment]
https://github.com/covidatlas/coronadatascraper/issues/647

**Comment by lazd** [comment]
This will be fixed tonight; `state`, `country`, etc will be human readable, and `countryId`/`stateId` will be packed ID fields
