### ISSUE TITLE
Virginia, United States - County Data either Not Updating or Old Data for 4/5/2020

### ISSUE THREAD

**Issue by weslawson** [covidatlas/coronadatascraper#681]
## Location, date, and short issue description
Virginia, United States - County Data reporting old or incorrect for 4/5/2020

## Source
http://www.vdh.virginia.gov/content/uploads/sites/182/2020/03/VDH-COVID-19-PublicUseDataset-Cases.csv

## File
timeseries.csv
data.csv

## Issue details
Wise County, VA reported as 0 cases in CDS
Wise County, VA reported as 1 case by Virginia Department of Health (Authoritative Source)

## Snippet/screenshot
```
<!-- If you can, please include a snippet of the file here, or a screenshot, to help us find it.-->
```
![image](https://user-images.githubusercontent.com/62673655/78515001-1a5d5700-7782-11ea-97b6-4b5a1e9e35a2.png)

![image](https://user-images.githubusercontent.com/62673655/78515006-2f39ea80-7782-11ea-9cb8-405fcac0fc7d.png)

**Comment by weslawson** [comment]
As an additional note: the source data source is being updated at 9:00 am et daily.

**Comment by lazd** [comment]
4/5 not released yet

**Comment by lazd** [comment]
We update every dat at 9PM. The latest update just went out right now. Please re-open this issue if the data is still stale. Thanks!
