### ISSUE TITLE
Missin GeoJSON for Ladakh and Telengana India

### ISSUE THREAD

**Issue by lazd** [covidatlas/coronadatascraper#686]
## Location, date, and short issue description

Missing GeoJSON for:

  ❌ Could not find location Ladakh, iso1:IN
  ❌ Could not find location Telengana, iso1:IN

**Comment by pankaj-giri** [comment]
@lazd, @hyperknot 
Need some out to the file I need to update to include these states in the GeoJSON. I have tried adding the state level Geo codes following the Italy scraper but haven't had any luck.

**Comment by hyperknot** [comment]
@pankaj-giri I started doing this as well. I'll need to work with @lazd on this, as the cross referencing didn't let any state through.

**Comment by pankaj-giri** [comment]
Sounds good. Thanks!

**Comment by pankaj-giri** [comment]
@hyperknot - isnt this bug closed?

**Comment by hyperknot** [comment]
Yes, thanks for noting it!
