### ISSUE TITLE
ID columns missing from timeseries.csv

### ISSUE THREAD

**Issue by hyperknot** [covidatlas/coronadatascraper#692]
1. We need to add the ID columns to timeseries.csv 
2. We should also move them next to the human readable name columns (more left), as many users don't find them in the rightmost place and feel confused.

**Comment by cristipp** [comment]
Same for timeseries-tidy.csv. 

Not entirely where the 'reference' dataset is. Looking at https://coronadatascraper.com/#timeseries.json, it appears to only have counts, but not metadata. Possibly we need to join it with https://coronadatascraper.com/#locations.json. A challenge is that locations.json has 3972 entries, but timeseries.json has a variable number of entries, depending on the date, for example 3430 for 2020-01-20, but 3884 for 2020-04-01. Not entirely sure how to join these 2 tables

**Comment by hyperknot** [comment]
Timeseries only has rows for days / locations which are non-zero. This might not be a good decision, there is an issue about it.

**Comment by cristipp** [comment]
Thanks. I just joined on location #, and it worked just fine.

**Comment by jzohrab** [comment]
This has been implemented in Li.  All reports contain `locationID`.  See https://github.com/covidatlas/li/blob/master/docs/reports.md.

I'm closing this, but if there is a problem, please open an issue in Li.  Cheers! jz
