### ISSUE TITLE
USA timeseries, negative cases growth for 2020-03-12, almost zero cases growth for last date

### ISSUE THREAD

**Issue by cristipp** [covidatlas/coronadatascraper#695]
## Location, date, and short issue description
USA timeseries, negative cases growth for 2020-03-12
USA timeseries, almost zero cases growth for last date, currently 2020-04-05

## File
https://coronadatascraper.com/timeseries-tidy.csv.zip

### USA timeseries, negative cases growth for 2020-03-12.
USA, 2020-03-11, cases: 2316 
USA, 2020-03-12 cases: 1596

Cases are cumulative, it is impossible to have negative growth. May leave the impression there are others errors in the lurking in the data.

See http://covid19.quersive.com/chart?e=CA&e=DE&e=FR&e=GB&e=IT&e=JP&e=KR&e=US&f=R&w=0&x=D

Just noticed the same for Japan, 2020-02-05 / 2020-02-06 See http://covid19.quersive.com/chart?e=CA&e=DE&e=FR&e=GB&e=IT&e=JP&e=KR&e=US&f=R&ff=JP&w=0&x=D

### USA timeseries, almost zero cases growth for last date, currently 2020-04-05
USA, 2020-04-04, value: 307280
USA, 2020-04-05, cases: 307288

Surely the case growth is much larger than 8 per day, I suspect somehow the summation is only considering partial sums. May leave the incorrect impression the growth has stalled.

## Snippet/screenshot

PS. Notice the 'United States' timezone is 'Africa/Algiers' for some reason :)

USA timeseries data snapshot:
[
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-01-22', type: 'cases', value: '1'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-01-23', type: 'cases', value: '1'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-01-24', type: 'cases', value: '2'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-01-25', type: 'cases', value: '2'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-01-26', type: 'cases', value: '5'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-01-27', type: 'cases', value: '5'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-01-28', type: 'cases', value: '5'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-01-29', type: 'cases', value: '5'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-01-30', type: 'cases', value: '5'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-01-31', type: 'cases', value: '7'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-02-01', type: 'cases', value: '8'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-02-02', type: 'cases', value: '8'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-02-03', type: 'cases', value: '11'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-02-04', type: 'cases', value: '11'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-02-05', type: 'cases', value: '11'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-02-06', type: 'cases', value: '11'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-02-07', type: 'cases', value: '11'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-02-08', type: 'cases', value: '11'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-02-09', type: 'cases', value: '11'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-02-10', type: 'cases', value: '11'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-02-11', type: 'cases', value: '12'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-02-12', type: 'cases', value: '12'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-02-13', type: 'cases', value: '13'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-02-14', type: 'cases', value: '13'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-02-15', type: 'cases', value: '13'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-02-16', type: 'cases', value: '13'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-02-17', type: 'cases', value: '13'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-02-18', type: 'cases', value: '13'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-02-19', type: 'cases', value: '13'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-02-20', type: 'cases', value: '13'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-02-21', type: 'cases', value: '15'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-02-22', type: 'cases', value: '15'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-02-23', type: 'cases', value: '15'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-02-24', type: 'cases', value: '15'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-02-25', type: 'cases', value: '15'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-02-26', type: 'cases', value: '15'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-02-27', type: 'cases', value: '16'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-02-28', type: 'cases', value: '16'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-02-29', type: 'cases', value: '24'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-03-01', type: 'cases', value: '30'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-03-02', type: 'cases', value: '53'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-03-03', type: 'cases', value: '73'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-03-04', type: 'cases', value: '104'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-03-05', type: 'cases', value: '172'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-03-06', type: 'cases', value: '217'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-03-07', type: 'cases', value: '336'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-03-08', type: 'cases', value: '452'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-03-09', type: 'cases', value: '517'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-03-10', type: 'cases', value: '1598'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-03-11', type: 'cases', value: '2316'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-03-12', type: 'cases', value: '1596'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-03-13', type: 'cases', value: '2112'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-03-14', type: 'cases', value: '2660'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-03-15', type: 'cases', value: '3432'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-03-16', type: 'cases', value: '4565'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-03-17', type: 'cases', value: '6353'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-03-18', type: 'cases', value: '7715'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-03-19', type: 'cases', value: '11723'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-03-20', type: 'cases', value: '17038'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-03-21', type: 'cases', value: '23203'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-03-22', type: 'cases', value: '30128'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-03-23', type: 'cases', value: '42164'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-03-24', type: 'cases', value: '53192'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-03-25', type: 'cases', value: '64180'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-03-26', type: 'cases', value: '82234'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-03-27', type: 'cases', value: '99447'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-03-28', type: 'cases', value: '118234'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-03-29', type: 'cases', value: '139061'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-03-30', type: 'cases', value: '162399'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-03-31', type: 'cases', value: '184770'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-04-01', type: 'cases', value: '213372'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-04-02', type: 'cases', value: '243453'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-04-03', type: 'cases', value: '275586'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-04-04', type: 'cases', value: '307280'},
        {name: 'United States', level: 'country', city: '', county: '', state: '', country: 'United States', population: '325145963', lat: '28.4065', long: '0.30750000000000455', aggregate: 'state', tz: 'Africa/Algiers', date: '2020-04-05', type: 'cases', value: '307288'},
        ... 335977 more
    ]

**Comment by jzohrab** [comment]
Hi @cristipp - thanks for the issue.  I'm clearing out the backlog.

I downloaded the `timeseries-tidy-small.csv` from https://covidatlas.com/data, and checked the counts.  Below are the results, everything looks good for those dates you mentioned:

```
$ grep 'iso1:us,' timeseries-tidy-small.csv | grep cases | grep 2020-03-1
iso1:us,2020-03-10,cases,2346
iso1:us,2020-03-11,cases,2873
iso1:us,2020-03-12,cases,3555
iso1:us,2020-03-13,cases,4580
iso1:us,2020-03-14,cases,5495
iso1:us,2020-03-15,cases,6746
iso1:us,2020-03-16,cases,8315
iso1:us,2020-03-17,cases,11928
iso1:us,2020-03-18,cases,15099
iso1:us,2020-03-19,cases,19770

$ grep 'iso1:us,' timeseries-tidy-small.csv | grep cases | grep 2020-04-0
iso1:us,2020-04-01,cases,225559
iso1:us,2020-04-02,cases,253551
iso1:us,2020-04-03,cases,285496
iso1:us,2020-04-04,cases,318748
iso1:us,2020-04-05,cases,344298
iso1:us,2020-04-06,cases,373235
iso1:us,2020-04-07,cases,403972
iso1:us,2020-04-08,cases,434506
iso1:us,2020-04-09,cases,468925

```

Closing this issue, but LMK if something else looks off.  Cheers! z
