### ISSUE TITLE
Use center_lat/center_lon from country-level jsons

### ISSUE THREAD

**Issue by hyperknot** [covidatlas/coronadatascraper#696]
Country-level json files have now center_lat and center_lon coordinates pre-calculated. (They also have timezones pre-calculated now).

We should migrate to use these ones over dynamically calculating using turf, as the current data has some problems for some reason:
https://github.com/covidatlas/coronadatascraper/issues/478

Also, it'd be much faster to use precomputed values instead of calculating the centroid. Same is true for timezones, which is even slower and also depends on a big dependency of geotz.

**Comment by jzohrab** [comment]
We're using this in Li, so I'll close this issue here.  Cheers! jz
