### ISSUE TITLE
KS, US: Data Inconsistency

### ISSUE THREAD

**Issue by praging** [covidatlas/coronadatascraper#698]
03-21 data repeated on 03-22; 03-27 data significantly lower than 03-26; 03-30 data repeated on 03-31; 04-03 data significantly lower than 04-02; 04-03 data repeated on 04-04 and 04-05.

same [source](https://public.tableau.com/views/COVID-19Data_15851817634470/CountyCounts.pdf?:showVizHome=no) being used throughout.

[timeseries-jhu-ks.xlsx](https://github.com/covidatlas/coronadatascraper/files/4441647/timeseries-jhu-ks.xlsx)

**Comment by praging** [comment]
remaining: 03-27 case data incorrect; 03-23 to 03-27 (inclusive) deaths nulled; 03-23 to 03-31 (inclusive) tested nulled.

**Comment by tautme** [comment]
Comparing current 04-09 `timeseries.csv` `level == state` and `state == Kansas`
To `timeseries-jhu-ks.xlsx` above.

* Same
** 03-21 repeated 03-22
** 03-27 significant downtrend
** 03-30 repeated 03-31
* Different
* 04-03 greater than 04-02
* 03-03 not repeated on 03-04 and 03-05

<img width="658" alt="image" src="https://user-images.githubusercontent.com/15580867/79023417-e8fbd700-7b45-11ea-90de-8e10f0aaaa09.png">

**Comment by tautme** [comment]
Here is current 04-09 `timeseries-tidy.csv` `level == state` and `state == Kansas` and `date > 2020-03-11`

<img width="658" alt="image" src="https://user-images.githubusercontent.com/15580867/79023722-9e2e8f00-7b46-11ea-9ba0-c396d674659f.png">

**Comment by jzohrab** [comment]
KS numbers look ok on https://covidatlas.com/kansas-us, closing.
