### ISSUE TITLE
SD, US: Data Inconsistency

### ISSUE THREAD

**Issue by praging** [covidatlas/coronadatascraper#699]
04-01 data significantly lower than 03-31; 04-03 data significantly lower than 04-02; 04-03 data repeated on 04-04 and 04-05; 04-06 data does not match source (**scraping recoveries**).

same [source](https://doh.sd.gov/news/Coronavirus.aspx#SD) being used throughout.

[timeseries-jhu-sd.xlsx](https://github.com/covidatlas/coronadatascraper/files/4441680/timeseries-jhu-sd.xlsx)

**Comment by praging** [comment]
update
remaining: 04-01 data significantly lower than 03-31, **scraping recoveries**.

**Comment by tautme** [comment]
2020 April 11
timeseries-jhu.csv
level == "state"
<img width="594" alt="image" src="https://user-images.githubusercontent.com/15580867/79089014-1c875e80-7d0a-11ea-93ac-8dc71ff46ed6.png">

**Comment by hyperknot** [comment]
Just to confirm, this error is found in source JHU data? When we deduplicate we should use COVIDTracking for state data, so this won't matter for us in the future.

**Comment by tautme** [comment]
No, this is our data from `https://doh.sd.gov/news/Coronavirus.aspx#SD`
The `timeseries-jhu.csv` is CDS's data in JHU format.

**Comment by hyperknot** [comment]
Can you check if the sources we are using for state level data are good?

**Comment by tautme** [comment]
[https://doh.sd.gov/news/Coronavirus.aspx](https://doh.sd.gov/news/Coronavirus.aspx) gives `868` cases for 11:30 a.m.; April 13, 2020.
CDS is showing  `197` for April 12, 2020

**Comment by jzohrab** [comment]
SD numbers look good for https://covidatlas.com/south-dakota-us.  Closing, thank you!
