### ISSUE TITLE
NJ, US: Data Inconsistency

### ISSUE THREAD

**Issue by praging** [covidatlas/coronadatascraper#700]
03-19 data repeated on 03-20, 03-21, 03-22, 03-23, and 03-24; 04-03 data significantly lower than 04-02 data; 04-03 data repeated on 04-04 and 04-05.

same [source](https://opendata.arcgis.com/datasets/24f4fcf164ad4b4280f08c8939dd5dc7_0.csv) being used throughout.

[timeseries-jhu-nj.xlsx](https://github.com/covidatlas/coronadatascraper/files/4441694/timeseries-jhu-nj.xlsx)

**Comment by praging** [comment]
drop now fixed. 
remaining: 03-19 data repeated on 03-20, 03-21, 03-22, 03-23, and 03-24; 04-02 data repeated on 04-03, 04-04, and 04-05.

**Comment by tautme** [comment]
2020 April 11 
timeseries-jhu.csv 
<img width="594" alt="image" src="https://user-images.githubusercontent.com/15580867/79088893-b1d62300-7d09-11ea-8586-d19d47b844a9.png">

**Comment by jzohrab** [comment]
Still present for NJ:

![image](https://user-images.githubusercontent.com/1637133/83342179-10576080-a2ba-11ea-953e-2ec2f30f269b.png)

Taking a look.

**Comment by jzohrab** [comment]
For 2020-03-19 ... -25, the NJ scraper scraped the following

```
    '2020-03-19': async function() {
      this.url = 'https://opendata.arcgis.com/datasets/84737ef7f760486293b6afa536f028e0_0.csv';
```

This URL is still up, and it's still returning that old data.  On the 25th, it was changed to

```
    '2020-03-25': async function() {
      this.url = await fetch.getArcGISCSVURL(this, 7, 'ec4bffd48f7e495182226eee7962b422', 'DailyCaseCounts');
```

and got better data.

I don't know that we can fill in this missing data, unless NJ decides to make hist. data publicly available.  I'll contact them to see if they can open something up for us.

**Comment by jzohrab** [comment]
Sent email to Covid.Dashboard@doh.nj.gov.  The worst they can do is not respond. :-)

**Comment by jzohrab** [comment]
Appears to be fixed now, in https://covidatlas.com/new-jersey-us.  Numbers are increasing with no plateaus.
