### ISSUE TITLE
timeseries-tidy.csv has stopped updating since 05/04/2020

### ISSUE THREAD

**Issue by FortDigital** [covidatlas/coronadatascraper#701]
## Location, date, and short issue description
timeseries-tidy.csv has not been updating since the 5th April, and the data for the 5th is incomplete

## Source
https://coronadatascraper.com/

## File
https://coronadatascraper.com/timeseries-tidy.csv

## Issue details
Data for the last 7 days shown below, Ive re-run the import and manually checked the file and found there is no data since the 5th and the data for the 5th is partially complete, The other CSV files and Json's seem to be ok.

## Snippet/screenshot
![image](https://user-images.githubusercontent.com/62287745/78646216-9eadf800-78b0-11ea-9a68-3acced70a888.png)

**Comment by lazd** [comment]
Yes, it's now a zip file. We need to delete the old `timeseries-tidy.csv`.

https://coronadatascraper.com/timeseries-tidy.csv.zip

**Comment by FortDigital** [comment]
Thanks, Ive updated my collection script to allow for the zip file

**Comment by SylCard** [comment]
thanks i've just seen this and saved me opening another issue lool!
