### ISSUE TITLE
Add timeseries scraper for Washington, D.C.

### ISSUE THREAD

**Issue by lazd** [covidatlas/coronadatascraper#703]
## Location name

Washington, D.C., USA

## Source URL

https://microstrategy.dc.gov/MicroStrategyLibrary/app/E52A533B11EA01A28FE80080EFC53DA4/30FE682111EA6FB5A6620080EF357B1F/K53--K46??ui.navigation.share=false&ui.navigation.gotoLibrary=false&ui.navigation.options=false&ui.navigation.filter=false&ui.navigation.reset=false&ui.navigation.bookmark=false&app.embedded=true&auth.freeLogin=false&ui.navigation=true&ui.navigation.title=true&ui.navigation.toc=true&ui.message=false

## Notes/comments

Requires a token

**Comment by aed3** [comment]
I can look into it

**Comment by jzohrab** [comment]
Fixed in #724, afaict.  Cheers!
