### ISSUE TITLE
Update getting started docs about new switches.

### ISSUE THREAD

**Issue by hyperknot** [covidatlas/coronadatascraper#705]
## Description
https://github.com/covidatlas/coronadatascraper/blob/master/docs/getting_started.md
needs to be updated for new switches

**Comment by jzohrab** [comment]
Hi @hyperknot, is this the same as #706?  Which new switches need to be covered?

**Comment by hyperknot** [comment]
Yes, exactly the same.

**Comment by jzohrab** [comment]
I'm opening a PR anyway. :-)  https://github.com/covidatlas/coronadatascraper/pull/723
