### ISSUE TITLE
Yarn Flags (Documentation Fix and Feature Request)

### ISSUE THREAD

**Issue by praging** [covidatlas/coronadatascraper#706]
yarn flags have been changed over the past week or so -- need to be explained more fully in the [documentation](https://github.com/covidatlas/coronadatascraper/blob/master/docs/getting_started.md).

add: the `-c` flag for country-specific scraper runs
remove: the `-l` flag for location-specific scraper runs (the Ventura County example no longer works)

the latter should be implemented in a similar way and documented -- current way to run a region-specific scrape is "quite ugly" (@hyperknot)

the `-l` flag should also probably be renamed now that it is not used for location

**Comment by hyperknot** [comment]
I mean `yarn start -l "Ventura County, iso2:US-CA, iso1:USA"` is not exactly nice and also it doesn't even work now.

**Comment by jzohrab** [comment]
Ventura county has the following:

```
const scraper = {
  county: 'Ventura County',
  state: 'CA',
  country: 'iso1:US',
```

Should you be using the iso2 there, or should it be `Ventura County, CA, iso1:US` ?

**Comment by hyperknot** [comment]
`yarn start -l "Ventura County, CA, iso1:USA"` doesn't work either. I think the confusing part is that -l is also trying to match on filename, and that combination of filename matching and location names is not really working.

**Comment by jzohrab** [comment]
I think we should match on filename only, it's easier to grok when quickly running one scraper, or a group.  It could be a regex, and the match would be checking against the path relative to the scrapers root, all parts joined by '/'.  So, '.*ventura.*' would find anything with 'ventura' in the path, '^US' anything starting with US, '.*index.*' would run pretty much everything.
Thoughts?

**Comment by hyperknot** [comment]
I totally agree we should match on filename/subdir. So we should be able to do US/CA or `US/CA/ventura` or something similar.

**Comment by lazd** [comment]
Yeah these flags are unpredictable and confusing, I know because I made them that way as a means to an end :)

Let's make them not suck! Matching on filename/subdir is GREAT.

**Comment by jzohrab** [comment]
Assigning to self: I'm going to do this now, it should be a small fix and will help everyone, including me.

**Comment by jzohrab** [comment]
PR opened. #720

**Comment by lazd** [comment]
`yarn options` now clues you into all the deets. Cheers!
