### ISSUE TITLE
Incorrect 4/6 infection count for San Francisco County, CA

### ISSUE THREAD

**Issue by ldtcooper** [covidatlas/coronadatascraper#719]
## Incorrect 4/6 infection count for San Francisco County, CA
According to snapshots of the San Francisco Department of Public Health website, the number of infections on 4/6 was 583, not 568 as reported on your website. The SFDPH updates their numbers at 9:00 AM PST, and if you look at a snapshot from before then (8:10 AM, see pre-update snapshot link below), you'll see that there were 568 deaths reported before the update, and 583 after the update (see post-update snapshot link below). 

## Source
Pre-update snapshot: https://web.archive.org/web/20200406081006/https://www.sfdph.org/dph/alerts/coronavirus.asp
Post-update snapshot: https://web.archive.org/web/20200406165215/https://www.sfdph.org/dph/alerts/coronavirus.asp

## Snippet/screenshot
<img width="1094" alt="Screen Shot 2020-04-08 at 8 46 11 AM" src="https://user-images.githubusercontent.com/24310179/78804773-6cb29980-7975-11ea-97a4-7e4a60d125ff.png">

**Comment by lazd** [comment]
There's definitely an error here, but we should be able to heal it properly. Our source data is procured from @HarrietRowan's curated spreadsheet here: https://docs.google.com/spreadsheets/d/1CwZA4RPNf_hUrwzNLyGGNHRlh1cwl8vDHwIoae51Hac/edit#gid=0 , which shows 583 for 4/7 and 568 for 4/6, so it looks like our 4/7 fetch got 4/6 data. I remember her saying she was late to update on 4/7, so it's possible it got missed.

**Comment by lazd** [comment]
Fixed! Thank you so much for the report.

```
    "San Francisco County, California, United States":
    {
        "dates":
        {
            "2020-04-05":
            {
                "cases": 568,
                "deaths": 8
            },
            "2020-04-06":
            {
                "cases": 583,
                "deaths": 9
            },
            "2020-04-07":
            {
                "cases": 622,
                "deaths": 9,
                "tested": 5645
            }
        },
        "state": "California",
        "country": "United States",
        "aggregate": "county",
        "curators": [
        {
            "name": "The Mercury News",
            "email": "hattierowan@gmail.com",
            "twitter": "@hattierowan",
            "github": "HarrietRowan"
        }],
        "url": "https://docs.google.com/spreadsheets/d/1CwZA4RPNf_hUrwzNLyGGNHRlh1cwl8vDHwIoae51Hac/gviz/tq?tqx=out:csv&sheet=master",
        "county": "San Francisco County",
        "rating": 0.5686274509803921,
        "coordinates": [-122.42182114845951, 37.7701349930529],
        "tz": ["America/Los_Angeles"],
        "featureId": "fips:06075",
        "population": 881549,
        "populationDensity": 7035.640089356456,
        "countryId": "iso1:US",
        "stateId": "iso2:US-CA",
        "countyId": "fips:06075",
        "name": "San Francisco County, California, United States",
        "level": "county"
    },
```
