### ISSUE TITLE
Timeseries Date Field changing formats

### ISSUE THREAD

**Issue by weslawson** [covidatlas/coronadatascraper#725]
## Location, date, and short issue description
The date field keeps changing formats.  It has been either yyyy-MM-dd or MM/dd/yyyy. A format needs to be chosen and used consistently.  April 8 the format is MM/dd/yyyy and April 7 the format was yyyy-MM-dd.

## File
timeseries.csv

## Issue details
Date keeps changing formats every few days between yyyy-MM-dd and MM/dd/yyyy.

**Comment by jzohrab** [comment]
This has been fixed in Li, we use yyyy-mm-dd exclusively.  Thanks for the issue, closing! z
