### ISSUE TITLE
GB improvements

### ISSUE THREAD

**Issue by hyperknot** [covidatlas/coronadatascraper#726]
I'm working on GB improvements, just wanted to document it here.

1. It's absolutely a monster, they have 211 regions from different levels.
2. Their source file uses something called GSS codes, which I was able to map to ISO codes using this Wikidata query: https://w.wiki/MQ3
3. It seems that their data contains a mix of state and county level numbers. Can someone with deep understanding of UK admin boundaries have a look?

GSS => E06
![image](https://user-images.githubusercontent.com/494223/78855191-8b6f6980-7a23-11ea-9c1b-37808e3f922d.png)

E08
![image](https://user-images.githubusercontent.com/494223/78855233-a5a94780-7a23-11ea-9b34-3fdec95ab46d.png)

E09
![image](https://user-images.githubusercontent.com/494223/78855290-c83b6080-7a23-11ea-8e6c-3007ae1a6b18.png)

E10
![image](https://user-images.githubusercontent.com/494223/78855334-e2753e80-7a23-11ea-9b9c-800a324f6112.png)

**Comment by hyperknot** [comment]
Basically this is the full England:

![image](https://user-images.githubusercontent.com/494223/78855452-3e3fc780-7a24-11ea-8351-a3cd66bea294.png)

**Comment by hyperknot** [comment]
Actually I checked and it's quite good, those polygons are perfectly matching and not overlapping. So basically we just need to add population data to 

  ❌ iso2:GB-OLD, England, iso1:GB: ?
  ❌ iso2:GB-RCH, England, iso1:GB: ?
  ❌ iso2:GB-SKP, England, iso1:GB: ?
  ❌ iso2:GB-TAM, England, iso1:GB: ?
  ❌ iso2:GB-KWL, England, iso1:GB: ?
  ❌ iso2:GB-SFT, England, iso1:GB: ?
  ❌ iso2:GB-WRL, England, iso1:GB: ?
  ❌ iso2:GB-BNS, England, iso1:GB: ?
  ❌ iso2:GB-WLL, England, iso1:GB: ?
  ❌ iso2:GB-BRD, England, iso1:GB: ?
  ❌ iso2:GB-CLD, England, iso1:GB: ?
  ❌ iso2:GB-KIR, England, iso1:GB: ?

**Comment by lazd** [comment]
Holy shit, you're so close! This is a huge improvement!

**Comment by hyperknot** [comment]
I think I've managed to make GB / England work 100%

![image](https://user-images.githubusercontent.com/494223/78906240-61e42b80-7a7f-11ea-9f57-104821941296.png)

**Comment by hyperknot** [comment]
England is now fixed, working on Scotland now (totally different system).

**Comment by lazd** [comment]
YES. Can't wait to merge and deploy this code.

**Comment by hyperknot** [comment]
GB/ENG is merged. GB/SCT I'm still working on.

**Comment by qgolsteyn** [comment]
Heads up: #816 changes the source for ENG, as the previous one gave us a 403 error

**Comment by jzohrab** [comment]
#816 was merged, and another timeseries fix for GB went in tonight (from @qgolsteyn as well).  Perhaps this issue can be closed, will follow up w/ @lazd and @hyperknot tomorrow-ish.  cheers!
