### ISSUE TITLE
Forecast

### ISSUE THREAD

**Issue by microprediction** [covidatlas/coronadatascraper#728]
## Description
Hi I'm assigning myself the task of calibrating [pandemic](https://github.com/microprediction/pandemic) to coronascraper data. Hope to get to it sooner or later. Fabulous scraping project btw, well done. Not sure if you want "synthetic" data or not here. Otherwise I'll put the predictions at [Microprediction.Org](www.micropredictions.org). 

## Why do you need this feature or component?
Inference, forecasting

## Additional context
Here's a [post](https://www.linkedin.com/pulse/dear-new-zealand-heres-how-simulate-covid-19-all-your-cotton-phd/) about the open source pandemic model.

**Comment by jzohrab** [comment]
Wow that's very interesting.  We're currently working on collecting and presenting data from official sources, so at the moment synthetic data is outside of our scope.  But please keep us informed of your work.

Your second link "Micropredictions.org" isn't valid, and http://www.micropredictions.org/ doesn't exist yet.  Did you have a different link?

Cheers! jz

**Comment by microprediction** [comment]
Yes I figured your site would be a source and that's all. I will circle back when I have a decent surrogate model for pandemics. 

You've done a nice job. Finally someone putting out clean JSON data instead of flashy graphics.

In passing the link is 
   [www.microprediction.org](www.microprediction.org)   

I have a few time series like:

https://www.microprediction.org/bar?name=hospital_bike_activity.json and https://www.microprediction.org/bar?name=covid_news_nyc.json 

there which I use to train prediction algorithms.

**Comment by jzohrab** [comment]
Hi @microprediction , thanks again for the note.  We're changing how we collect data shortly.  If you shoot me your email address (jzohrab at gmail dot com), I can keep you update in a BCC-only non-spammy update (which I haven't done yet, but may start soon-ish).  Cheers!
