### ISSUE TITLE
Maps bug

### ISSUE THREAD

**Issue by hyperknot** [covidatlas/coronadatascraper#737]
## Description
Maps terminates with a bug because on county doesn't exist in data.locations.

## Steps to reproduce
1. `yarn timeseries -d 2020-04-07 -e 2020-04-07`
2. `yarn dev`
3. open map on http://localhost:3000/

Map breaks with 
```
Uncaught TypeError: Cannot read property 'level' of undefined
    at map.js:50
    at Array.filter (<anonymous>)
    at generateCountyFeatures (map.js:50)
    at setData (map.js:74)
    at populateMap (map.js:324)
    at handleLoaded (map.js:411)
    at map.js:425
    at XMLHttpRequest.<anonymous> (fetch.js:19)
```

I made a fix with console.log lines in "map-bug" branch.

The problematic county is 
```
{name: "Carson City", name_long: "Carson City, NV", fips: "32510", state_code_int: 32, state_code_postal: "NV", …}
```

I think we should both fix the maps code (possibly with a bit more DRY approach + figure out backend, why isn't that single County present in `data.locations`

**Comment by hyperknot** [comment]
Fixes here: 789d5cae...70a6fdd2

**Comment by jzohrab** [comment]
This sounds like something CI could catch.  @hyperknot for CI to catch it, would it be as simple as running the report and grepping the data?

**Comment by hyperknot** [comment]
Yes!

**Comment by jzohrab** [comment]
Closing as this has been addressed and the reports are now generated completely differently in Li.  Cheers! z
