### ISSUE TITLE
Add scraper for Ecuador

### ISSUE THREAD

**Issue by pablocarreraest** [covidatlas/coronadatascraper#747]
## Location name

Ecuador by provinces
## Source URL

[Ecuador Website Tracker](https://covid19ecuador.carreraestrada.com/)
[Ecuador my collection dataset](https://carreraestrada-my.sharepoint.com/:x:/p/pcarrerae/EXHxGZscdYRLsw5Q0YqvPJUBBXhH6yLnJIsc7UT3nRSB_Q?e=GuahZT)
[Ecuador government info](https://www.gestionderiesgos.gob.ec/informes-de-situacion-covid-19-desde-el-13-de-marzo-del-2020/)
[Ecuador Wiki data](https://en.wikipedia.org/wiki/2020_coronavirus_pandemic_in_Ecuador)
## Notes/comments

I will like to help you get more deep info location
of by cantons and parishes (Im currently working on).
Hope my work can be useful for you.
**I'm glad to help if you need me any format you need for the data**

**Comment by shaperilio** [comment]
Hello Pablo,

https://covid19ecuador.carreraestrada.com/ is your own project?

What is the source of the data?

**Comment by pablocarreraest** [comment]
Hi @shaperilio ,

> https://covid19ecuador.carreraestrada.com/ is your own project?

Yes my project is in [here](https://github.com/pablocarreraest/covid19ecuador).

> What is the source of the data?

The sources is the [National Service for Risk and Emergency Management of Ecuador](https://www.gestionderiesgos.gob.ec/informes-de-situacion-covid-19-desde-el-13-de-marzo-del-2020/) (Government data).

currently for update my data I use excel file to add the daily changes at [here](https://carreraestrada-my.sharepoint.com/:x:/p/pcarrerae/ESzMCHkl6tJDvSx8ahkOZs8BcPv9RcHJIDWXfCu0d0Ic0g?e=tgqLuj) and then transform to json file to my webpage.

I really want to add my collection to this API if you give me some guide how to add. I will work on it

**Comment by pablocarreraest** [comment]
close this issue because of the main source of our government data (the certainty of the data is very bad) they change day by day add and subtract as they please (or the organization of our government fails)
