### ISSUE TITLE
Add scraper for Poland

### ISSUE THREAD

**Issue by ciscorucinski** [covidatlas/coronadatascraper#748]
## Location name
Poland (PL)
via Primary Administrative Subdivisions (Provinces)

## Source URL
https://www.gov.pl/web/koronawirus/wykaz-zarazen-koronawirusem-sars-cov-2

### Related Info URLs
https://en.wikipedia.org/wiki/Voivodeships_of_Poland

## Notes/comments
- The website has pagination via the same URL. The default shows 10 values, but there are 16 administrative divisions.

- It seems like it uses Vue's pagination component. Not sure if there is a "hack" to get around this without puppeteer.

- No English version.

**Comment by qgolsteyn** [comment]
Closed with #799
