### ISSUE TITLE
Two last days only in JSON (by location)

### ISSUE THREAD

**Issue by a0s** [covidatlas/coronadatascraper#749]
Am I missed something? Could it be possible to restore access to full dataset? Now it returns two last days only from https://coronadatascraper.com/timeseries-byLocation.json

**Comment by lazd** [comment]
Nope, I messed up the deploy last night -- fat fingered a `d` (start date) instead of a `e` (end date) when I ran the timeseries. Re-deploying now!

**Comment by lazd** [comment]
Re-deployed, this should be fixed. Thanks!

**Comment by a0s** [comment]
@lazd btw, i can help in automatization of deployment process: ansible, raw docker, kubernetes - on your choice!
