### ISSUE TITLE
Map cannot display same id both as state and county

### ISSUE THREAD

**Issue by hyperknot** [covidatlas/coronadatascraper#753]
## Description
In BE, Brussels is present both as a county and a state. We need to add both values so that the map is complete and the counts are right. Right now, the framework removes Brussels as a county and only leaves it as a state.

```
The data is all there:
{
    cases: 2820,
    hospitalized: 1369,
    discharged: 778,
    state: 'iso2:BE-BRU',
    deaths: 448,
    county: 'iso2:BE-BRU'
  },
  {
    cases: 2820,
    hospitalized: 1369,
    discharged: 778,
    state: 'iso2:BE-BRU',
    deaths: 448
  },
```
But the map has a hole in it:
![image](https://user-images.githubusercontent.com/494223/79057101-a0374180-7c5d-11ea-9cb1-cbcd7d7a55ee.png)

## Steps to reproduce
1. Master branch, `yarn timeseries -d 2020-04-07 -e 2020-04-07 -l BE`
2. `yarn dev`
3. http://localhost:3000/#features.json > map > show counties only

## Expected behavior
The map should be displaying it on both layers.

**Comment by jzohrab** [comment]
Issue appears to be resolved.
