### ISSUE TITLE
Formalize state and county as first/second country subdivision field

### ISSUE THREAD

**Issue by shaperilio** [covidatlas/coronadatascraper#778]
The Belgium scraper maps "regions" to `state` and "provinces" to `county`. Provinces are equivalent to state; our data schema currently does not have a place for anything between country and province or anything smaller than city.

By "schema" I mean "whatever every other scraper does", because we don't have a schema defined yet.
@qgolsteyn

**Comment by hyperknot** [comment]
I think we should state it clear that it doesn't matter what state/county is called in each country, we are using "state" to mean first subdivision of country and "county" for the second subdivision.

**Comment by qgolsteyn** [comment]
I agree. We should formalize this in our doc. Leaving this open until this is addressed.

**Comment by shaperilio** [comment]
You mean there's a doc with a schema?

**Comment by qgolsteyn** [comment]
Yes: https://github.com/covidatlas/coronadatascraper/blob/master/docs/data_fields.md

**Comment by jzohrab** [comment]
I believe this is clear in the Li docs, closing. Cheers! jz
