### ISSUE TITLE
Update scraper for India

### ISSUE THREAD

**Issue by lazd** [covidatlas/coronadatascraper#789]
## Location name
IN

## Source URL
https://www.mohfw.gov.in/dashboard/index.php

## Notes/comments

Now has a new site with some JSON embedded in it

**Comment by ciscorucinski** [comment]
I see the data passed to the visualization, but where is the JSON?

**Comment by lazd** [comment]
It's deep in the JS...

**Comment by appastair** [comment]
> I see the data passed to the visualization, but where is the JSON?

https://www.mohfw.gov.in/dashboard/data/data.json

**Comment by camjc** [comment]
Is this still an issue? What is the diff vs prod?
