### ISSUE TITLE
Michigan Over Counting Total State Roll-up

### ISSUE THREAD

**Issue by MVLBAct** [covidatlas/coronadatascraper#793]

**Comment by lazd** [comment]
Can you investigate further and detail by how much? Does it involve Wayne County and Detroit?

**Comment by MVLBAct** [comment]
Hey Larry, sorry I did not do a good job of providing detail initially! It looks like it is over stating 6,758 cases. This is close to the Detroit case count, which is 6781. The table the scraper is pulling from: https://www.michigan.gov/coronavirus/0,9753,7-406-98163-520743--,00.html 
Has a "Total" roll-up, which looks like the accurate case count for the state.

**Comment by fordmaxson** [comment]
The city of detroit is part of Wayne county.  The people at michigan.gov decided they wanted to treat the city of detroit like its own county so they could see what things were like in city itself.
The scraper put "Detroit City" in the aggregate category of City.  But that leaves the remaining count for "Wayne County" low by that amount.  

The scraper has to either add the totals in "Detroit City" to Wayne County, or change "Detroit City" from a city aggregate to a county aggregate.

**Comment by jzohrab** [comment]
This is fixed in Li, closing.
