### ISSUE TITLE
If a county's name is the same as that of a province, it gets assigned the province's lat/long

### ISSUE THREAD

**Issue by shaperilio** [covidatlas/coronadatascraper#798]
## Steps to reproduce
1. Go to Panama scraper.
2. Uncomment lines marked with this issue number, right above return.
3. `yarn start -l PA`, then look at `data.csv`.

## Expected behavior
Although there are real situations where an entity exists as two administrative levels (e.g. San Francisco is both a city and county), the comparison should not be done only by name.

i.e. If we province information for a country but not county information, then all counties should simply be ignored. Data output from scrapers makes it explicit what the administrative level of an entity is.

Even if we cannot (or choose not to) display them on a map, county-level data should be available at the time series level.

@hyperknot

**Comment by hyperknot** [comment]
OK, today I hope to push the new lat/lon code, can you check back afterwards?

**Comment by shaperilio** [comment]
Yes, ping me.

**Comment by jzohrab** [comment]
This has been fixed in Li.  We use locationIDs everywhere.  Closing, cheers! z
