### ISSUE TITLE
Missing population data for Slovenia

### ISSUE THREAD

**Issue by lazd** [covidatlas/coronadatascraper#800]
## Location, date, and short issue description

Slovenia'

## Snippet/screenshot
```
<!-- If you can, please include a snippet of the file here, or a screenshot, to help us find it.-->
```
![image](https://user-images.githubusercontent.com/201344/79188189-3ccf2000-7dd3-11ea-8f7e-5e70018c6161.png)

**Comment by hyperknot** [comment]
Tracked in #775
