### ISSUE TITLE
locations.json creating duplicate location "name" due to county/city dup (Virginia #1)

### ISSUE THREAD

**Issue by fordmaxson** [covidatlas/coronadatascraper#811]
locations.json is creating multiple records with the exact same location "name" due to the following...

If you have the following:
Country | State | County | City
US         |  VA     | Bristol City  |   null
US         |   VA     | null              |  Bristol city
You can't concatenate and create "name" =
US, VA, Bristol City
US, VA, Bristol city
On my BI report I concatenate like...
US-VA-Bristol City-
US-VA--Bristol city
The hyphen delimiter always keeps it straight (even null gets a delimiter) if we have a county or a city.

Here is an example of the actual JSON.

![image](https://user-images.githubusercontent.com/38134430/79266197-2f627600-7e65-11ea-8633-318172475501.png)

And here is a complete list of locations with duplicates. 

![image](https://user-images.githubusercontent.com/38134430/79266302-5c168d80-7e65-11ea-9e31-15780e4d0ac4.png)

**Comment by hyperknot** [comment]
I've just added a big PR which fixes this for all counties, can you check it on current master? (Or just check it tomorrow when new data will be published.)

**Comment by lazd** [comment]
You're a magic man, @hyperknot! The release is going out right now.

@fordmaxson, let us know if the issue is fixed tomorrow. Thanks!

**Comment by fordmaxson** [comment]
Great job.  I concur that we have no duplicate "name" values anymore.  Thanks!
