### ISSUE TITLE
Add primary source scraper for China

### ISSUE THREAD

**Issue by camjc** [covidatlas/coronadatascraper#815]
## Location name
China

## Source URL
http://2019ncov.chinacdc.cn/2019-nCoV/ has a dashboard, not sure how to scrape yet.

## Notes/comments
We have regional data from JHU but would be good to replace with a primary source.

**Comment by appastair** [comment]
* **中国** 🇨🇳 : http://2019ncov.chinacdc.cn/2019-nCoV/config.js
 * 📐 GeoJSON: http://49.4.25.117/JKZX/yq_20200416.json
 * Data Source: National Health Commission, Provincial Health Committee
* **全球** 🌐: http://2019ncov.chinacdc.cn/2019-nCoV/globalConfig.js
 * 📐 GeoJSON: http://49.4.25.117/JKZX/gb_yq_20200416.json
 * Data Source: National Health Commission, "World Health Organization"

For such a busy interface, the data is quite compact! :mag: 

I've added the short, full and translated province names which can be used for lookup. THe majority of the remaining characters for translation are things like "Confirmed Cases", "Deaths"...

```
var provinceNames = {
    "shortName": {
        "北京市": "北京",
        "天津市": "天津",
        "上海市": "上海",
        "重庆市": "重庆",
        "河北省": "河北",
        "河南省": "河南",
        "湖北省": "湖北",
        "湖南省": "湖南",
        "江苏省": "江苏",
        "江西省": "江西",
        "辽宁省": "辽宁",
        "吉林省": "吉林",
        "黑龙江省": "黑龙江",
        "陕西省": "陕西",
        "山西省": "山西",
        "山东省": "山东",
        "四川省": "四川",
        "青海省": "青海",
        "安徽省": "安徽",
        "海南省": "海南",
        "广东省": "广东",
        "贵州省": "贵州",
        "浙江省": "浙江",
        "福建省": "福建",
        "台湾省": "台湾",
        "甘肃省": "甘肃",
        "云南省": "云南",
        "西藏自治区": "西藏",
        "宁夏回族自治区": "宁夏",
        "广西壮族自治区": "广西",
        "新疆维吾尔自治区": "新疆",
        "内蒙古自治区": "内蒙古",
        "香港特别行政区": "香港",
        "澳门特别行政区": "澳门"
    },
    "englishName": {
        "北京": "Beijing",
        "天津": "Tianjin",
        "上海": "Shanghai",
        "重庆": "Chongqing",
        "河北": "Chongqing",
        "河南": "Henan",
        "湖北": "Hubei",
        "湖南": "Hunan",
        "江苏": "Jiangsu",
        "江西": "Jiangxi",
        "辽宁": "Liaoning",
        "吉林": "Jilin",
        "黑龙江": "Heilongjiang",
        "陕西": "Shaanxi",
        "山西": "Shanxi",
        "山东": "Shandong",
        "四川": "Sichuan",
        "青海": "Qinghai",
        "安徽": "Anhui",
        "海南": "Hainan",
        "广东": "Guangdong",
        "贵州": "Guizhou",
        "浙江": "Zhejiang",
        "福建": "Fujian",
        "台湾": "Taiwan",
        "甘肃": "Gansu",
        "云南": "Yunnan",
        "西藏": "Tibet",
        "宁夏": "Ningxia",
        "广西": "Guangxi",
        "新疆": "Xinjiang",
        "内蒙古": "Inner Mongolia",
        "香港": "Hong Kong",
        "澳门": "Macao"
    }
};
```

**Comment by camjc** [comment]
There was a double `Chongqing` that I resolved, but the rest LGTM.
Made a PR to scrape the whole timeseries at https://github.com/covidatlas/coronadatascraper/pull/944

**Comment by appastair** [comment]
> There was a double `Chongqing` that I resolved, but the rest LGTM.

Oops...well-spotted with the Chongqing/Hebei mix-up. Sorry. :zipper_mouth_face:

**Comment by camjc** [comment]
Done in LI, open PR here but probably no point finishing it.
