### ISSUE TITLE
timeseries United Kingdom 2020-04-15 data fault

### ISSUE THREAD

**Issue by clausgp** [covidatlas/coronadatascraper#826]
## Location, date, and short issue description
2020-04-15
United Kingdom latest data seems to be repeated for all the dates in timeseries.csv

## File
https://coronadatascraper.com/timeseries.csv

**Comment by qgolsteyn** [comment]
Thank you for this report, I'll have a look at what went wrong

**Comment by jzohrab** [comment]
@clausgp thanks for the issue.  We're launching tonight, I'll check in tomorrow to see if this has been addressed.
