### ISSUE TITLE
Do not use Date() anywhere outside datetime.

### ISSUE THREAD

**Issue by shaperilio** [covidatlas/coronadatascraper#836]
Control timezone-related issues by disallowing this, since `new Date(blah)` returns something in the current timezone. 

Internally, we should be using UTC everywhere.

`generateTimeSeries()` is using `Date`, for example. My understanding is that this is not super urgent as long as release is being run on a machine that's on the same day as UTC.

@HerbCaudill

**Comment by shaperilio** [comment]
We should probably also stop using `process.env.SCRAPE_DATE` if we have `datetime.scrapeDate()`

**Comment by jzohrab** [comment]
This isn't relevant in Li, and we won't fix it in this project, which is being retired eventually.  Thanks, closing! z
