### ISSUE TITLE
US/FL may be throwing away data

### ISSUE THREAD

**Issue by shaperilio** [covidatlas/coronadatascraper#846]
The data source for this scraper has changed often.

1. It has changed from ArcGIS REST API to CSV. We should probably find out why, as REST API is preferred.

2. It contains logic like this:

```
parse.number(county.FLandNonFLDeaths || 0)
```

Which is not good, because it makes it difficult to catch the fact that apparently Florida changes field names as they please. As of just now, the scraper was broken here:

```
parse.number(county.FLResDeaths);
```

Because the field name appears to be different now:

```
parse.number(county.FLResDeaths || county.Deaths);
```

Spot checks of older dates show CSVs with fields like `T_positive` and `Tpositive`... we need to look closely at all this data and see if there's any coherency in the field names over time.

**Comment by jzohrab** [comment]
In Li, us-fl appears to have settled down.  A recent PR to Li fixed some data, see https://api.staging.covidatlas.com/status?format=html for successful scrape, and I've just pushed it to prod.  I believe this can be closed.
