### ISSUE TITLE
COVIDAtlas: united-states map starts in Africa.

### ISSUE THREAD

**Issue by jzohrab** [covidatlas/coronadatascraper#850]
https://staging.covidatlas.com/united-states

When I drag the map, US is shown correctly, but it starts in Africa.

Mind you, we _all_ started in Africa at some point back in time ... perhaps this is intentional.

**Comment by lazd** [comment]
Ha, yeah, coordinates for the middle of the US are wrong due to territories being included.

#696 will fix this.

**Comment by jzohrab** [comment]
Closing in favor of https://github.com/covidatlas/coronadatascraper/issues/696.
