### ISSUE TITLE
NJ scraper broken

### ISSUE THREAD

**Issue by lazd** [covidatlas/coronadatascraper#855]
## Location, date, and short issue description

iso2:US-NJ, iso1:US

## Source

https://maps.arcgis.com/sharing/rest/content/items/ec4bffd48f7e495182226eee7962b422?f=json

## File

coronadatascraper-cache/2020-4-19/411fff8d52252450316f6aa1048659f0.json

## Issue details

❌ Got error 502 trying to fetch https://opendata.arcgis.com/datasets/undefined_0.csv

## Additional context

Layer name must've changed?

**Comment by jzohrab** [comment]
Checking, might be quick.

**Comment by jzohrab** [comment]
Fixed in https://github.com/covidatlas/coronadatascraper/pull/922.

**Comment by jzohrab** [comment]
Fixed.
