### ISSUE TITLE
RI scraper broken

### ISSUE THREAD

**Issue by lazd** [covidatlas/coronadatascraper#857]
## Location, date, and short issue description

iso2:US-RI, iso1:US

## Source

https://health.ri.gov/data/covid-19/

## File

coronadatascraper-cache/2020-4-19/04bca6611c701019bc15b36425e93ca2.html

## Issue details

 ❌ Error processing iso2:US-RI, iso1:US:  TypeError: Cannot read property '0' of undefined

**Comment by jzohrab** [comment]
Taking a look at it now.

**Comment by jzohrab** [comment]
PR opened: #913 .

**Comment by jzohrab** [comment]
PR has been merged, will keep this open to verify.

**Comment by jzohrab** [comment]
Fixed.
