### ISSUE TITLE
WV scraper broken

### ISSUE THREAD

**Issue by lazd** [covidatlas/coronadatascraper#858]
## Location, date, and short issue description

iso2:US-WV, iso1:US

## Source

https://wabi-us-gov-virginia-api.analysis.usgovcloudapi.net/public/reports/187b4de8-78ef-40be-9510-7fa9a1ef89f2/modelsAndExploration

## File

coronadatascraper-cache/2020-4-19/b549098f7618dd395c3326938172408e.json

## Issue details

❌ Got error 401 trying to fetch https://wabi-us-gov-virginia-api.analysis.usgovcloudapi.net/public/reports/187b4de8-78ef-40be-9510-7fa9a1ef89f2/modelsAndExploration

**Comment by jzohrab** [comment]
They're using PowerBI at https://dhhr.wv.gov/COVID-19/Pages/default.aspx.

**Comment by jzohrab** [comment]
I left a request (haha) at their "contact us" form for raw data ... https://appengine.egov.com/apps/wv/wvgov/contactus  :-)

**Comment by jzohrab** [comment]
Fixed in https://github.com/covidatlas/coronadatascraper/pull/961.
