### ISSUE TITLE
OK scraper broken, new looker dashboard

### ISSUE THREAD

**Issue by lazd** [covidatlas/coronadatascraper#872]
## Location, date, and short issue description

iso2:US-OK, iso1:US

## Source

https://coronavirus.health.ok.gov/

**Comment by jzohrab** [comment]
You can also get CSVs by county from a dashboard:

https://looker-dashboards.ok.gov/embed/dashboards/63

e.g

```
County,Cases,Deaths,Recovered,ReportDate
OKLAHOMA,773,31,531,2020-04-30
TULSA,567,33,398,2020-04-30
CLEVELAND,419,28,290,2020-04-30
WASHINGTON,256,19,130,2020-04-30
TEXAS,131,1,35,2020-04-30
WAGONER,119,15,89,2020-04-30
...
```

**Comment by jzohrab** [comment]
Done in PR https://github.com/covidatlas/coronadatascraper/pull/920.

**Comment by jzohrab** [comment]
Done, merged.
