### ISSUE TITLE
US/MS scraper broken

### ISSUE THREAD

**Issue by lazd** [covidatlas/coronadatascraper#874]
## Location, date, and short issue description

iso2:US-MS, iso1:US

## Source

https://msdh.ms.gov/msdhsite/_static/14,0,420.html

## Issue details

❌ Error processing iso2:US-MS, iso1:US:  Error: Unexpected table headers
=

**Comment by jzohrab** [comment]
Started giving the above error as at `$ yarn start --location US/MS --date 2020-4-17`.  Looking into it.

**Comment by jzohrab** [comment]
Fixed, closing.
