### ISSUE TITLE
US/IN data out-of-date

### ISSUE THREAD

**Issue by edwlook** [covidatlas/coronadatascraper#904]
Looks like we're not scraping new data Indiana. We're about 2-3k behind.

This looks like a good data source: https://hub.mph.in.gov/dataset/covid-19-county-statistics/resource/8b8e6cd7-ede2-4c41-a9bd-4266df783145

**Comment by jzohrab** [comment]
Thank you very much @edwlook - we've been heads down and haven't had a chance to fix yet.  We got another issue today for Indiana, https://github.com/covidatlas/coronadatascraper/issues/966, so I'll close this in favor of that.  Cheers! jz
