### ISSUE TITLE
Data extraction by example 

### ISSUE THREAD

**Issue by okamoun** [covidatlas/coronadatascraper#907]
Hi we are developing a programming by example system to extract and integrate data.

We have applied our technic to the coronadatascraper data and we give free access to anyone who want to use it. 

our site is www.bailam.com

the tutorial for covid data is : https://www.bailam.com/covid19

**Comment by jzohrab** [comment]
Hi @okamoun , thank you very much for letting us know, and regards for a great project!  I've added you to our list of consumers.

We're still working on coronadatascraper, and its next-gen replacement, li (https://github.com/covidatlas/li).  I'd like to notify consumers about changes to the data collection and app, and wondered if I can get your email addresses.  You can send me a mail at jzohrab -at- gmail -dot- com.  If I don't hear from you, I'll assume that you don't want to be updated :-)

And if you haven't already, please do join our Slack (https://join.slack.com/t/sars-cov-2covid-19/shared_invite/zt-cr6ln0ph-6eDATfSUNDtFK3mlQxqYKw). We have a #consumers channel for others who are using our data.

Cheers and regards!
Jeff

**Comment by okamoun** [comment]
Hi my email dress is okamoun@bailam.com <mailto:okamoun@bailam.com>.
Thanks fro the good work you are doing

**Comment by jzohrab** [comment]
Thank you very much @okamoun , you're on my short BCC list. Closing this issue, and thank you for contacting us.  Have a great day! jz
