### ISSUE TITLE
Requesting consumer emails for CDS updates

### ISSUE THREAD

**Issue by jzohrab** [covidatlas/coronadatascraper#909]
Hi there

@martiL - https://github.com/martiL
@ndom91 - https://github.com/ndom91
@brauls - https://github.com/brauls
@Akuukis - https://github.com/Akuukis

(I believe this works ...)

We're still working on coronadatascraper, and its next-gen replacement, `li` (https://github.com/covidatlas/li).

I'd like to notify consumers about changes to the data collection and app, and wondered if I can get your email addresses.

You can message me at jzohrab -at- gmail -dot- com.

If I don't hear from you, I'll assume that you don't want to be updated.

And if you haven't already, please do join our Slack (https://join.slack.com/t/sars-cov-2covid-19/shared_invite/zt-cr6ln0ph-6eDATfSUNDtFK3mlQxqYKw).  We have a #consumers channel for others who are using our data.

Cheers all, and I hope you're well!

**Comment by ndom91** [comment]
This is awesome, we're rewriting our API in serverless functions as well so this could be a perfect match! I'll definitely keep my eyes on it.

**Comment by Akuukis** [comment]
Thanks! Email sent.

**Comment by jzohrab** [comment]
OK, closing, thanks for sending the info all. cheers!
