### ISSUE TITLE
Japan data is stale

### ISSUE THREAD

**Issue by zbraniecki** [covidatlas/coronadatascraper#921]
## Location, date, and short issue description

Data for Japan and its prefectures deteriorated and got stale on April 16.

## Issue details

Example from the timeseries JSON file:

```
  "2020-04-15": {
    "cases": 8100,
    "deaths": 146,
    "recovered": 853,
    "active": 7101
  },
  "2020-04-16": {
    "cases": 8559
  },
  "2020-04-17": {
    "cases": 9104
  },
  "2020-04-18": {
    "cases": 9646
  },
  "2020-04-19": {
    "cases": 10000
  },
  "2020-04-20": {
    "cases": 10000
  },
  "2020-04-21": {
    "cases": 10000
  }
  ...
```

Similar issue with Tokyo prefecture at least. I expect other JP sources.

**Comment by camjc** [comment]
Issue is arcgis 10,000 limit. There’s an open pr to fix.

**Comment by swsoyee** [comment]
Hi there, I'm maintaining a website of COVID-19 in Japan, the data are collected by myself, from real-time news report and also from MHLW every day. Maybe you could consider use my dataset.

https://github.com/swsoyee/2019-ncov-japan
If you need more detail, feel free to ask me.

Thank you

**Comment by jzohrab** [comment]
Hi @swsoyee , thank you very much for the offer!  We're currently only using official government and accredited sources (JHU, NYT, etc), so we won't take you up on the offer for _this_ project.  Best of luck, and thank you again!

We're having trouble keeping up with the changes in data sets, which is why our response to this is lagging.  Cheers! jz

**Comment by jzohrab** [comment]
This is already acknowledged in https://api.covidatlas.com/status?format=html:

![image](https://user-images.githubusercontent.com/1637133/89735505-f14f1a80-da30-11ea-99b8-18818ee1480b.png)

Closing as duplicate.  Thanks! jz
