### ISSUE TITLE
Locations not showing title

### ISSUE THREAD

**Issue by ladeane00** [covidatlas/coronadatascraper#924]
The keys are not strings anymore. They have iso written all over them now, rendering them unreadable text. Please fix.

**Comment by jzohrab** [comment]
Hi @ladeane00 , can you let me know what file you're referring to?  Which url you hit, file you downloaded, and when you got it?

I just ran this locally right now to check, and see the names in data.json, data.csv, report.json, locations.json, timeseries-byLocation.json, ... and many others.

Note: We have fairly recently moved to using iso codes for standardization -- it _vastly_ simplifies things on our end, or more accurately it makes many things possible -- but we should still support human-friendly names.

Thanks for the note! jz

**Comment by lazd** [comment]
Yeah, we had an error, but it's fixed now! Try again.
