### ISSUE TITLE
US/CO scraper broken

### ISSUE THREAD

**Issue by jzohrab** [covidatlas/coronadatascraper#928]
`yarn start --location US/CO`

  🐢  Cache miss for scraper: /US/CO/index.js; url: https://opendata.arcgis.com/datasets/fbae539746324ca69ff34f086286845b_0.csv; filepath: coronadatascraper-cache/2020-5-1/2dadf4f54d967d4e31058861ac745674.csv
  🚦  Loading data for https://opendata.arcgis.com/datasets/fbae539746324ca69ff34f086286845b_0.csv from server
  ❌ Got error 404 trying to fetch https://opendata.arcgis.com/datasets/fbae539746324ca69ff34f086286845b_0.csv
  ❌ Error processing iso2:US-CO, iso1:US:  TypeError: data is not iterable
    at Object.2020-03-20 (/Users/jeff/Documents/Projects/coronadatascraper/src/shared/scrapers/US/CO/index.js:131:28)

**Comment by jzohrab** [comment]
URL in the scraper gives: `{"errors":[{"title":"Resource Not Found","status":404,"message":"Not Found"}],"meta":{}}`

**Comment by jzohrab** [comment]
They have an HTML table at https://covid19.colorado.gov/covid-19-data.

**Comment by lazd** [comment]
Perhaps this explains #930
