### ISSUE TITLE
CO-US showing 0 cases from 2020-4-23 to 2020-4-27

### ISSUE THREAD

**Issue by lazd** [covidatlas/coronadatascraper#930]
## Location, date, and short issue description
https://staging.covidatlas.com/colorado-united-states

## Source

US-CO

## Snippet/screenshot

![image](https://user-images.githubusercontent.com/201344/80826385-f7fb0580-8b96-11ea-84e6-95c271beaa94.png)

**Comment by jzohrab** [comment]
With the fix, we're now like this:

![image](https://user-images.githubusercontent.com/1637133/80869239-627e7500-8c6d-11ea-941a-93dd7ddbbb3c.png)

While it's not non-zero, it's the best we can do, unless we back-fill, but we have bigger things to worry about. :-)
