### ISSUE TITLE
Using the coronadatascraper in a Shiny Apps R console

### ISSUE THREAD

**Issue by elaborative** [covidatlas/coronadatascraper#941]
Hello, just letting you know I am using your data (time series tidy format) in a Shiny app. https://ryancooper.shinyapps.io/Corona/ 
I am still beta testing and debugging some of the chart formats. Thanks for putting this project together. I am a data science student and this is my first attempt at a Shiny app so please let me know if anything appears incorrect, inaccurate, or broken! Thank you! - Ryan Cooper

**Comment by jzohrab** [comment]
Hey Ryan, thanks very much for this message.  Great to hear you're using it!  I'll add you to our list of consumers.  Could you shoot me your email -- (to jzohrab -at- gmail -dot- com) -- so I can potentially keep you updated of any changes in our work that might impact you?

Those visualizations are v interesting.  The correlations are super -- what standards are people using?

Thanks again!  Jeff

**Comment by jzohrab** [comment]
Added to list w/ email, thanks Ryan.  Cheers!
