### ISSUE TITLE
tested number is all NA today

### ISSUE THREAD

**Issue by lori99-data** [covidatlas/coronadatascraper#982]

**Comment by lori99-data** [comment]
some state and county don't have death and tested data on May 6th. For example NY state level missing tested, but there is death data on May 5th. Could anyone explain what happened? Thank you!

**Comment by jzohrab** [comment]
Hi @lori99-data - thanks for the heads up.  Can you let us know the file you're looking at, and a sample record?  Cheers! jz

**Comment by jzohrab** [comment]
Hm, not sure!  A couple possibilities : the source data published was
missing data, source was down, error on our side ... do you still have the
file with the error, what date, and can you give an example?

Cheers and thx for the issue, jz

**Comment by jzohrab** [comment]
Lack of clarification, closing!
