### ISSUE TITLE
Data for Indian States not found

### ISSUE THREAD

**Issue by deepak3081996** [covidatlas/coronadatascraper#984]
Indian state wise data is not got updated since 4th May 2020 for Indian states there is data till 4th May 2020, Please look into it to find why the data is not getting updated or tell us if this is done on purpose.

**Comment by camjc** [comment]
We have the fix in the li repo

src/shared/sources/in/index.js

We can back port, it’s just another ‘replace’

**Comment by deepak3081996** [comment]
thanks Cameron
Actually I'm directly parsing the json file available at this "https://coronadatascraper.com/timeseries-byLocation.json" link 

Can i please get  updated json file at the link specified

**Comment by lazd** [comment]
@camjc let's back port it for now, please!

**Comment by camjc** [comment]
@deepak3081996 Fixed now, output data should be resolved in the next release (in 5 hours from this post)

**Comment by deepak3081996** [comment]
<img width="943" alt="covidFault" src="https://user-images.githubusercontent.com/32619266/81501110-23e35d00-92f4-11ea-810a-7dfb8f5a99f0.png">


sorry but i couldn't found the fixed reflected in the web page, i shared the screenshot for 1 Indian state, i.e., Uttar Pradesh, still the data showing up is untill 4th May, Can you please look into it again
