### ISSUE TITLE
"tested" data for Washoe County, NV is impossible

### ISSUE THREAD

**Issue by mikelehen** [covidatlas/coronadatascraper#986]
## Location, date, and short issue description
Washoe County, NV (FIPS 32031) has impossible values for "tested" for many (all?) dates.  In many cases, the delta in "cases" from day-to-day is greater than the delta in "tested", which is impossible.  Since the county official website doesn't seem to report "total tests" or similar, I suspect the "tested" data is just bogus.

I don't know how you normally deal with this, but perhaps it's worth either contacting the county or blacklisting the "tested" data (and maybe re-check it every week or two?).  Or if this is outside your scope, we can just continue to blacklist it on our side.

## Source
The invalid "tested" entries seem to come from the underlying [arcgis dataset](https://services.arcgis.com/iCGWaR7ZHc5saRIl/arcgis/rest/services/CasesTable_public/FeatureServer/0/query?f=json&where=1%3D1&outFields=*&orderByFields=reportdt%20asc) that powers the [county website dashboard](https://www.washoecounty.us/health/programs-and-services/communicable-diseases-and-epidemiology/educational_materials/COVID-19.php), but the county website dashboard doesn't actually show "total tested" anywhere, so I think the data is probably garbage.

## File
https://coronadatascraper.com/timeseries-byLocation.json (but will show up in any of the timeseries datasets for Washoe)

## Issue details
The delta in "tested" from day-to-day is impossible, since it's often less than the delta in "cases".  E.g.:

>  "2020-05-03": {
>      "cases": 977,
>      "tested": 903,
>      ...
>  },
>  "2020-05-04": {
>      "cases": 988,
>      "tested": 906,
>      ...
>  },

There were 11 new confirmed cases, but only 3 tests? This is one example, but all of the "tested" data is likely wrong (see screenshot below).

## Snippet/screenshot
At https://covidactnow.org/ we are tracking "test positive rate" and for Washoe County, the current data looks like this:
![image](https://user-images.githubusercontent.com/206364/81482842-cfa28500-91ee-11ea-89e9-4d54f3c16e25.png)

Everything over 100% is impossible, and the rest is pretty suspect too.

**Comment by lazd** [comment]
@jzohrab @appastair can y'all look into this? Thanks!

**Comment by appastair** [comment]
I see what you mean, @mikelehen - [the data](https://services.arcgis.com/iCGWaR7ZHc5saRIl/arcgis/rest/services/CasesTable_public/FeatureServer/0/query?f=json&where=1%3D1&outFields=*&orderByFields=reportdt%20asc) is definitely off...although consistently being updated. :woman_shrugging:


```
{
"OBJECTID": 144,
...
"reportdt": 1589229462000,
"confirmed": 1100,
"recovered": 529,
"deaths": 39,
"active": 532,
"tested": 1035,
...
"reportedtPT": "5/11/2020 1:37 PM",
...
}
```

The [latest daily press release](https://covid19washoe.com/press-release/regional-information-center-update-may-11/) reports 14,029 tests.

I've attempted to contact them via [social media](https://twitter.com/Appastair/status/1260155778851168257) to see if they'll add the hidden, erroneous field to the dashboard. If that fails, I can attempt to contact them through another channel.

In the meantime, I'm not sure what the done thing is. Wait for correction or remove the field, @lazd ?

**Comment by jzohrab** [comment]
I'm removing the `tested` field, it's bogus.

**Comment by jzohrab** [comment]
Removed in PR https://github.com/covidatlas/coronadatascraper/pull/1045.

Thanks @mikelehen !
