### ISSUE TITLE
JHU time series stopped updating 5/9

### ISSUE THREAD

**Issue by ScottWOlson** [covidatlas/coronadatascraper#996]
The JHU export from Corona Data Scrapper that our service relies on has become unreliable and stopped completely on 5/9. There is no data as of 5/12:

https://coronadatascraper.com/#timeseries-jhu.csv

**Comment by jzohrab** [comment]
Thanks for the issue!

It looks like we didn’t publish yesterday, but we did earlier today.  I just checked https://coronadatascraper.com/#timeseries-jhu.csv and I see 2020-05-11.

I'll close this issue, as on its own it's resolved, but it highlights the need for better monitoring.  I've opened issue https://github.com/covidatlas/coronadatascraper/issues/997 for that.

Cheers and regards, jz
