### ISSUE TITLE
Li√®ge in name column in CSV (Tidy Format) file

### ISSUE THREAD

**Issue by pwrose** [covidatlas/coronadatascraper#999]
## Location, date, and short issue description
Li√®ge, Wallonia, Belgium

## File
https://coronadatascraper.com/timeseries-tidy.csv.zip

## Issue details
Li√®ge, how should special characters be presented in this file? UTF-8?

**Comment by jzohrab** [comment]
Hm, yes, it should be utf8. Still occurring?

I figure it’s just like the Belgians to name a city
Li-square-root-registered-trademark-ge. I’ve watched In Bruges several
times.

**Comment by pwrose** [comment]
This seems to be a problem in how Excel interprets special characters. 

It looks fine in a pandas dataframe.
